### ISSUE TITLE
页面载入出错，进入二级页面时，加载不出来

### ISSUE THREAD

**Issue by zhleao** [scriptscat/scriptcat#106]
![图片](https://user-images.githubusercontent.com/83908206/198958668-e14832f2-a35e-40e8-8d98-9e95be13a796.png)

**Comment by CodFrm** [comment]
发一下链接

**Comment by zhleao** [comment]
https://docs.scriptcat.org/docs/use#%E8%8E%B7%E5%8F%96%E8%84%9A%E6%9C%AC
&nbsp;


..FUTURE..
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scriptscat/scriptcat] 页面载入出错，进入二级页面时，加载不出来 (Issue #106)





 
发一下链接

**Comment by CodFrm** [comment]
我这里正常服务，可以尝试清理一下缓存，再试试吗？

**Comment by zhleao** [comment]
可以了


..FUTURE..
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scriptscat/scriptcat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [scriptscat/scriptcat] 页面载入出错，进入二级页面时，加载不出来 (Issue #106)





 
我这里正常访问，可以尝试清理一下缓存，再试试吗？
