### ISSUE TITLE
0.10 无法使用

### ISSUE THREAD

**Issue by hhuimie** [scriptscat/scriptcat#107]
浏览器: Edge 版本 101.0.1210.32 (正式版本) (64 位)
0.10 beta, beta.1 (zip版) 貌似都无法导入0.9.1的脚本, 完全没反应
也不能保存新建脚本, 点击保存没反应

**Comment by CodFrm** [comment]
导入是报了这个错误吗？0.10只能导入zip包

<img width="594" alt="image" src="https://user-images.githubusercontent.com/22783163/200748614-71eae210-13c7-4835-9e3d-111290f05418.png">

**Comment by CodFrm** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/22783163/200748808-3ce2e08a-4f38-45db-91c0-e52bfc3470a2.png">

保存有什么错误提示吗？

**Comment by hhuimie** [comment]
> 导入是报了这个错误吗？0.10只能导入zip包
> 
> <img alt="image" width="594" src="https://user-images.githubusercontent.com/22783163/200748614-71eae210-13c7-4835-9e3d-111290f05418.png">
> 
> 导入确实是有问题

不是, 是完全没反应, 打开console有以下错误
![视频_2022-11-09_135001](https://user-images.githubusercontent.com/4830177/200749793-35f143af-016c-45c0-a67e-03245c3c3731.gif)

![image](https://user-images.githubusercontent.com/4830177/200749722-f5b1fd96-8ec1-4a9e-9db8-3e282eeff862.png)

**Comment by hhuimie** [comment]
> <img alt="image" width="1042" src="https://user-images.githubusercontent.com/22783163/200748808-3ce2e08a-4f38-45db-91c0-e52bfc3470a2.png">
> 
> 保存有什么错误提示吗？
> 
> 貌似有时候会出现这个错误，晚些修复 <img alt="image" width="1398" src="https://user-images.githubusercontent.com/22783163/200749048-6dcf2f10-69a2-40ea-a524-7d18ad1ca28d.png">

保存是这样, 完全没反应
![视频_2022-11-09_135437](https://user-images.githubusercontent.com/4830177/200750675-d7469504-1d80-43c3-ac4c-c1e3ec38702d.gif)

**Comment by hhuimie** [comment]
扩展页面的错误是这样
![image](https://user-images.githubusercontent.com/4830177/200751042-4f0b3e53-6687-4c3b-816f-2f4233fe9f72.png)

**Comment by CodFrm** [comment]
哥哥是不是没有清理掉老版本的文件？干净的安装一次试试？

**Comment by CodFrm** [comment]
无法判断什么问题导致的，方便加群/tg远程看一下么？887697472

**Comment by hhuimie** [comment]
> 

可能是我下载的这个便携版edge的原因
之前在果核剥壳上下载的, 但是可能版本比较老, 我找不到相关网页了
我重新打包上传了边, 麻烦注意安全
蓝奏云, 限制我单文件100m, 所以分了包, 麻烦去掉后缀".apk"再解压
https://wwm.lanzoub.com/b03vg3o6j
密码:bfno

**Comment by CodFrm** [comment]
两个都下载失败，提示：

ERROR:ID102
edge1.7z.001.apk

<img width="251" alt="image" src="https://user-images.githubusercontent.com/22783163/200986532-46b6166d-ed55-4836-991d-ce51bdd86d34.png">

**Comment by hhuimie** [comment]
> 两个都下载失败，提示：
> 
> ERROR:ID102 edge1.7z.001.apk
> 
> <img alt="image" width="251" src="https://user-images.githubusercontent.com/22783163/200986532-46b6166d-ed55-4836-991d-ce51bdd86d34.png">

不好意思, 我也不知道啥原因, 换了123pan, 测试了下可以下载
https://www.123pan.com/s/clxuVv-J9MZv
提取码:Hs9R

**Comment by CodFrm** [comment]
修复，哥哥在此页下载修复版本试试

https://github.com/scriptscat/scriptcat/actions/runs/3434913049

**Comment by hhuimie** [comment]
> 修复，哥哥在此页下载修复版本试试
> 
> https://github.com/scriptscat/scriptcat/actions/runs/3434913049

行了, 辛苦了哦
