### ISSUE TITLE
浏览器插件自动更新，我写的后台脚本都没有了，有没有恢复的办法

### ISSUE THREAD

**Issue by RUInalan** [scriptscat/scriptcat#109]

**Comment by CodFrm** [comment]
f12-》储存-》indexeddb可以看到数据


另外哥哥可以看一下有没有报错么？

**Comment by CodFrm** [comment]
C:\Users\你的用户名\AppData\Roaming\Mozilla\Firefox\Profiles\9f4bsk27.default\indexedDB

看一下这个目录下有没有相关的数据文件

**Comment by CodFrm** [comment]
访问此页面可获得数据库文件edge://indexeddb-internals/

**Comment by CodFrm** [comment]
已找到原因，数据库升级新增了一个唯一字段，老版本会存在非唯一的情况

临时解决方案，清空此表：
![image](https://user-images.githubusercontent.com/22783163/203071512-f69b0144-c72a-4055-ae83-3b06819ed185.png)

本issue转移到#110处理
