### ISSUE TITLE
脚本猫与BiliEvolved的兼容性问题

### ISSUE THREAD

**Issue by PianCat** [scriptscat/scriptcat#11]
**关于哪一项功能**
与脚本的兼容性问题

**问题描述**
使用 [Bili Evolved](https://github.com/the1812/Bilibili-Evolved) 时，只要修改任意一个设置，都会在下一次载入脚本时全部崩溃无法载入

**插件版本**
0.6.3

**浏览器版本**
Chrome 94.0.4606.81

**错误信息**
[Error Logs Here](https://github.com/PianCat/APTSSF/blob/main/BiliEvolved_ScriptCat/www.bilibili.com-1634639719902.log)

**附加截图**
![Snipaste_2021-10-19_18-40-29](https://user-images.githubusercontent.com/50688679/137893834-06182340-d11a-4cc2-8656-0465546e1cb8.png)

**Comment by CodFrm** [comment]
> 现在是在 Github Actions 中 Build 吗？

对，稍等一下应该就能在github下载zip安装包了
