### ISSUE TITLE
edge 从0.9.x更新到0.10出现的兼容问题，需要重装解决

### ISSUE THREAD

**Issue by Exisi** [scriptscat/scriptcat#110]
### 更新问题说明
从 v9.x 更新到 v0.10.0 版本脚本会无法正常获取，在线安装和本地导入脚本都会失败，且本地安装的脚本数据都会消失，更新建议提前做好备份。插件重装后可以解决以下问题

![image](https://user-images.githubusercontent.com/64684842/202850893-b08d49be-fb3a-47c2-be92-606d08e89b95.png)

![image](https://user-images.githubusercontent.com/64684842/202850483-bba4ec6c-67a4-4b47-9179-14fbbdae1e38.png)
### 控制台错误
![image](https://user-images.githubusercontent.com/64684842/202850570-1406be34-82f7-4fcf-a01d-75b871fbcc16.png)
### 环境
Microsoft Edge 版本 107.0.1418.52 (64 位)

**Comment by Exisi** [comment]
好像是edge才有的问题，在 Chrome 上更新没有发现这个问题，挺奇怪的

**Comment by CodFrm** [comment]
环境还在么？我需要一份可以复现的数据

**Comment by CodFrm** [comment]
访问此页面可获得数据库文件edge://indexeddb-internals/

**Comment by Exisi** [comment]
> 已经重装了，谷歌插件商店不给下载旧版，感觉复原可能性微存🤣

**Comment by CodFrm** [comment]
😭怕是某个bug导致的这个问题，有点不敢更新edge的版本了

如果能复现可以提供一下复现方式，或者使用上面的链接下载数据库文件提交上来，我看一下

**Comment by ViCrack** [comment]
![图片](https://user-images.githubusercontent.com/18179821/202861462-631ebbb7-c029-48c2-ad1c-6c2a025f80e8.png)

firefox更新之后啥都没了。。。

不过还好edge的还没更新，及时备份导出来了。。。

**Comment by CodFrm** [comment]
@ViCrack 

可以看一下报错信息么？能不能导出数据库文件？

Firefox导出方法：C:\Users\你的用户名\AppData\Roaming\Mozilla\Firefox\Profiles\9f4bsk27.default\indexedDB

**Comment by CodFrm** [comment]
@Exisi 这个数据库文件是有问题的数据库文件么？

**Comment by ViCrack** [comment]
没有明显报错，除了我切换按钮的时候会报错close database

![图片](https://user-images.githubusercontent.com/18179821/202863718-7d976357-b94d-4fa2-8e94-089d4b7fb7d9.png)


从这个路径上没有找到indexedDB，而且直接发出来不知道会不会有隐私问题

C:\Users\你的用户名\AppData\Roaming\Mozilla\Firefox\Profiles\《随机id》.default\indexedDB


F12可以看到

![图片](https://user-images.githubusercontent.com/18179821/202863932-a3faaaa9-ebe7-4b9d-8901-f5b850c06fbf.png)
![图片](https://user-images.githubusercontent.com/18179821/202863999-13b5eb4b-a998-4a75-9765-40b5b9168317.png)
![图片](https://user-images.githubusercontent.com/18179821/202864009-e9a719f1-c352-4e7b-acfb-8f342c97615f.png)
![图片](https://user-images.githubusercontent.com/18179821/202864017-971cac4d-f1c8-4cc4-a059-f40a8039b541.png)
![图片](https://user-images.githubusercontent.com/18179821/202864028-3f80971e-9070-414e-8dd1-bd403fd1d226.png)
![图片](https://user-images.githubusercontent.com/18179821/202864041-2a8f59a6-e7da-4eae-aa6b-9383367970be.png)
![图片](https://user-images.githubusercontent.com/18179821/202864049-154f5ba0-ef98-4fb4-9bf7-919d04d0d5bb.png)
![图片](https://user-images.githubusercontent.com/18179821/202864064-1600b565-124a-436e-92aa-a5b2173e54bc.png)

**Comment by CodFrm** [comment]
@ViCrack 看起来数据没有丢失，但是我不知道为什么数据库无法打开连接

你可以通过telegram https://t.me/scriptscat 或者QQ群 887697472 私信我

[数据储存在哪里？](https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8%E5%9C%A8%E5%93%AA%E9%87%8C%EF%BC%9F)

**Comment by CodFrm** [comment]
firefox的数据目录我看了一下，在此目录下（windows应该类似）

about:support显示的配置文件夹/storage/default/moz-extension+++5497e20c-8be1-4ce0-acb3-8bcacc92f9dc

**Comment by CodFrm** [comment]
已找到原因，数据库升级新增了一个唯一字段，老版本会存在非唯一的情况

临时解决方案，清空此表：
<img width="358" alt="image" src="https://user-images.githubusercontent.com/22783163/203071190-8ef9a4f7-8f6b-4d0d-be87-8e6962aeddd8.png">

**Comment by CodFrm** [comment]
已修复，firefox已上架，Chrome请等待2-3天

https://github.com/scriptscat/scriptcat/commit/10a5c1973b7f2dbcbe3f1720f6a1f33b23b93949
