### ISSUE TITLE
只运行一个脚本但是显示数目为2是不是bug

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [scriptscat/scriptcat#112]
![image](https://user-images.githubusercontent.com/59086082/202897544-6c36584e-66fa-4d55-8464-03e027a72038.png)

**Comment by CodFrm** [comment]
可能有iframe，这个数字是脚本运行次数，不是脚本数量

**Comment by duoluodexiaoxiaoyuan** [comment]
哦懂了
