### ISSUE TITLE
[bug] WebDAV 方式备份恢复提示404

### ISSUE THREAD

**Issue by jae-jae** [scriptscat/scriptcat#113]
![image](https://user-images.githubusercontent.com/5620429/203244642-76facedb-7659-426f-925b-eafb877c2843.png)

如图，通过 WebDAV 方式备份成功之后，点击恢复按钮，提示 404，点击备份的删除按钮，也提示404。 

ScriptCat 版本号为： 0.10.2

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/actions/runs/3531925905
