### ISSUE TITLE
脚本猫怎么用vscode开发调试

### ISSUE THREAD

**Issue by 1665169869** [scriptscat/scriptcat#114]
我在脚本猫提供的视频里：[https://www.bilibili.com/video/BV16q4y157CP/?vd_source=8a975be3bbde6240e404b3c910410bf3](https://www.bilibili.com/video/BV16q4y157CP/?vd_source=8a975be3bbde6240e404b3c910410bf3)
并未发现如何使用vscode进行开发调试，vscode左下角的绿色远程扩展是啥？如何开启？

**Comment by CodFrm** [comment]
暂时无法开启调试，调试只能在页面中f12进行调试

后台脚本参考这个方式进行调试 https://docs.scriptcat.org/docs/dev/backgroud#%E8%84%9A%E6%9C%AC%E8%B0%83%E8%AF%95

**Comment by 1665169869** [comment]
> 暂时无法开启调试，调试只能在页面中f12进行调试
> 
> 后台脚本参考这个方式进行调试 https://docs.scriptcat.org/docs/dev/backgroud#%E8%84%9A%E6%9C%AC%E8%B0%83%E8%AF%95
你好
我指的是脚本猫的工具-开发调试选项里的功能怎么用

**Comment by CodFrm** [comment]
脚本猫的工具-开发调试 这个在哪里？好像并没有这个选项

**Comment by 1665169869** [comment]
> 脚本猫的工具-开发调试 这个在哪里？好像并没有这个选项

![image](https://user-images.githubusercontent.com/50762038/204200426-9c807985-0aa8-4acc-830d-c0fc39e79a57.png)

**Comment by CodFrm** [comment]
这个与这里一样的，只是视频演示是老版本
https://www.bilibili.com/video/BV16q4y157CP/?vd_source=8a975be3bbde6240e404b3c910410bf3

vs code无法实现脚本的调试，文案可能有些误导
