### ISSUE TITLE
GM_cookie.list is not a function

### ISSUE THREAD

**Issue by OopsSnap** [scriptscat/scriptcat#117]
![image](https://user-images.githubusercontent.com/42453713/205289678-e7c285de-0261-42ee-85fe-01d46731852a.png)

http://121.5.226.51/tampermonkey/hd2a.user.js
这个脚本作者推荐使用红猴

![image](https://user-images.githubusercontent.com/42453713/205289935-b774d9ac-53ca-471b-a174-6a4e7df20c31.png)

https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js

![image](https://user-images.githubusercontent.com/42453713/205291190-f39a71f0-b8cf-460c-a10c-c7f14b852e99.png)
![image](https://user-images.githubusercontent.com/42453713/205291242-09b5d10d-d7fc-4a03-ba2b-64becca353da.png)

菜单显示不完全

**Comment by CodFrm** [comment]
http://121.5.226.51/tampermonkey/hd2a.user.js
应该是API兼容问题：脚本猫没有提供GM_cookie.xxx的方法，只支持GM_cookie("xxxx")的形式，这个我下版本做下兼容，各种API调用混乱还是挺蛋疼的

https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js
bilibili这个看起来是脚本自身的警告，应该没有问题吧

https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js
菜单问题我排查一下

**Comment by OopsSnap** [comment]
> http://121.5.226.51/tampermonkey/hd2a.user.js 应该是API兼容问题：脚本猫没有提供GM_cookie.xxx的方法，只支持GM_cookie("xxxx")的形式，这个我下版本做下兼容，各种API调用混乱还是挺蛋疼的
> 
> https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js bilibili这个看起来是脚本自身的警告，应该没有问题吧
> 
> https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js 菜单问题我排查一下

第二个问题是没有，不知能否兼容油猴导出的存储数据，每个脚本要重新设置挺麻烦的

**Comment by CodFrm** [comment]
好的，会做兼容的，已经兼容了导入格式

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/actions/runs/3607127402

**Comment by OopsSnap** [comment]
> fix: https://github.com/scriptscat/scriptcat/actions/runs/3607127402

修复是修复了，不知道是不是TM beta有新特性，用tm stable和 scriptcat，第一个脚本都会报错timeout

**Comment by CodFrm** [comment]
主要这个脚本是加密的，我不清楚是什么问题

这个脚本有使用方法么？

**Comment by OopsSnap** [comment]
> 主要这个脚本是加密的，我不清楚是什么问题
> 
> 这个脚本有使用方法么？

就是解锁B站番剧的，只要打开番剧播放页面就可以了。比如https://www.bilibili.com/bangumi/play/ss39664

**Comment by CodFrm** [comment]
不太清楚了，这个页面的话，不用这脚本我也可以直接看
