### ISSUE TITLE
脚本描述信息的MD渲染问题

### ISSUE THREAD

**Issue by maxzhang666** [scriptscat/scriptcat#12]
rt

目前对于A标签的渲染依旧存在问题

来挂个ISSUE鞭笞一之

**Comment by CodFrm** [comment]
什么是脚本站的吧？https://github.com/scriptscat/scriptlist-frontend 应该往这边提

![image](https://user-images.githubusercontent.com/22783163/139648810-84f4e2f3-a45e-42db-9647-a07bc632c103.png)

我这样写没问题啊，哥哥

看看你的

**Comment by CodFrm** [comment]
脚本站和论坛讲分隔开来，两边的这个应该都要修改的

**Comment by maxzhang666** [comment]
挂错地了、、

**Comment by CodFrm** [comment]
> 挂错地了、、

没啥事，一样的😁
