### ISSUE TITLE
脚本同步做好了吗

### ISSUE THREAD

**Issue by HkwJsxl** [scriptscat/scriptcat#120]
大佬，脚本同步大概什么时候能做好

**Comment by CodFrm** [comment]
不是有的嘛，只是扩展自身不提供了，依赖第三方的

<img width="715" alt="image" src="https://user-images.githubusercontent.com/22783163/205786198-0a44a606-c136-45b9-bcb4-97ff9f69993c.png">

**Comment by HkwJsxl** [comment]
![image](https://user-images.githubusercontent.com/88998157/205787051-4144b4b9-57f1-47b5-8b1b-850aa81151ee.png)
![image](https://user-images.githubusercontent.com/88998157/205787106-3fafa1f4-1d9f-455d-9952-6ee61fa93ffa.png)
![image](https://user-images.githubusercontent.com/88998157/205787186-5de86371-1a55-4271-8d93-13991a14bbed.png)
谷歌浏览器，这是什么问题

**Comment by CodFrm** [comment]
这是我服务器的问题，我今天处理好，不好意思，可能之前改了字段都没注意到

**Comment by CodFrm** [comment]
fix
