### ISSUE TITLE
新版本后，脚本无法识别网址了

### ISSUE THREAD

**Issue by majormj** [scriptscat/scriptcat#123]
v0.10.4 版本，脚本无法识别网址生效 了，忘解决

**Comment by CodFrm** [comment]
可以给出脚本，或者match规则么？

**Comment by majormj** [comment]
> 可以给出脚本，或者match规则么？

是所有的脚本都识别不出来啊，之前所有的脚本。另外就是 取消云同步了真的好可惜，登录账号自动同步这个大概是比油猴最有意思的功能了

**Comment by CodFrm** [comment]
我没有理解，所有的脚本都识别不出来是什么意思？

云同步取消了，但是有网盘同步，支持百度云和webdav（坚果云等）。功能上是一样的，后续还会支持更多网盘

主要是受限于服务器资源和开发成本，不打算自己来做这个储存服务了

**Comment by majormj** [comment]
> 我没有理解，所有的脚本都识别不出来是什么意思？
> 
> 云同步取消了，但是有网盘同步，支持百度云和webdav（坚果云等）。功能上是一样的，后续还会支持更多网盘
> 
> 主要是受限于服务器资源和开发成本，不打算自己来做这个储存服务了

问题：脚本猫升级到新版本后，edge浏览器 所有脚本都失效了（脚本在目标页面不显示了，就是脚本猫的图标那里 不显示了），谷歌的还能正常识别。不知道是哪里的问题。

**Comment by majormj** [comment]
> 检查是不是edge没开启，或者隐藏了，最好截个图看看
> 
> <img alt="image" width="354" src="https://user-images.githubusercontent.com/22783163/206900294-e1b5fb53-52f7-4804-87cf-28eff13f238f.png">

![image](https://user-images.githubusercontent.com/120294654/206901155-0774fdf0-adb4-4cce-8620-ce52721dc225.png)

**Comment by CodFrm** [comment]
```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        *://*/*
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
})();
```
新建这个脚本，访问任意页面呢？访问这个页面确实是不会匹配的

**Comment by majormj** [comment]
> 

![image](https://user-images.githubusercontent.com/120294654/206902050-56693fc3-5f4a-4eb5-ac10-54e57b0831c2.png)

**Comment by CodFrm** [comment]
可以看看这里的日志嘛？需要开发人员模式

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/22783163/206908208-1f9025cf-c277-4d5c-9e52-6ee7e03be818.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/22783163/206908219-2b7a6857-ce4f-4382-a623-884368bb8eaa.png">

**Comment by majormj** [comment]
> 可以看看这里的日志嘛？需要开发人员模式
> 
> <img alt="image" width="1238" src="https://user-images.githubusercontent.com/22783163/206908208-1f9025cf-c277-4d5c-9e52-6ee7e03be818.png">
> 
> <img alt="image" width="807" src="https://user-images.githubusercontent.com/22783163/206908219-2b7a6857-ce4f-4382-a623-884368bb8eaa.png">

![image](https://user-images.githubusercontent.com/120294654/206908513-feb8dbbc-595c-4b1d-9745-892c65db38a8.png)

**Comment by majormj** [comment]
![image](https://user-images.githubusercontent.com/120294654/206908709-581c9bb0-ebd9-4c28-af1f-f89e761555c3.png)

**Comment by CodFrm** [comment]
可能明白了，是有一个脚本的match错误了，导致全部失败

**Comment by majormj** [comment]
> 可能明白了，是有一个脚本的match错误了，导致全部失败
> 
> 临时处理方式：删除对应脚本

能看到是哪个脚本的match吗

**Comment by majormj** [comment]
> > 可能明白了，是有一个脚本的match错误了，导致全部失败
> > 临时处理方式：删除/修正对应脚本
> > 具体是哪个，就看哪个脚本使用了这个表达式 <img alt="image" width="201" src="https://user-images.githubusercontent.com/22783163/206908892-be3c3634-2f02-46aa-a68c-502be055986d.png">
> 
> ![image](https://user-images.githubusercontent.com/120294654/206909509-9aaec409-3661-44c7-9451-02360cbb7fa8.png) 应该不是是你说的这个问题，我ba把所有脚本都删除了，只留这一个还是不行

![image](https://user-images.githubusercontent.com/120294654/206909571-0485acce-b3f3-4f5f-86b9-519f23551b87.png)
控制台仍然这样显示

**Comment by CodFrm** [comment]
重启浏览器/扩展呢？还是这样嘛？奇怪了

**Comment by majormj** [comment]
> 重启浏览器/扩展呢？还是这样嘛？奇怪了

![image](https://user-images.githubusercontent.com/120294654/206951569-75037bff-3083-4fc7-97da-52f07b4d4d26.png)
重启了还是不行，是不是百度网盘同步脚本的问题

**Comment by CodFrm** [comment]
不确定，也可能是百度网盘同步了一个有问题的脚本，可以点击看一下这块的代码么？

<img width="728" alt="image" src="https://user-images.githubusercontent.com/22783163/206957254-9dcb97b5-0013-4796-9887-78b794187624.png">

**Comment by CodFrm** [comment]
报错的地方我大概知道，应该是match那块，屏蔽应该就好，但是不清楚这个是什么脚本，直接屏蔽应该会导致这个脚本无法正常使用

**Comment by majormj** [comment]
> 报错的地方大概知道，应该是match那块，屏蔽就好，但是不清楚这个是什么脚本，直接屏蔽会导致这个脚本无法正常使用

有QQ吗  交流方便一点  675402219

**Comment by majormj** [comment]
> 不确定，也可能是百度网盘同步了一个有问题的脚本，可以点击看一下这块的代码么？
> 
> <img alt="image" width="728" src="https://user-images.githubusercontent.com/22783163/206957254-9dcb97b5-0013-4796-9887-78b794187624.png">

![image](https://user-images.githubusercontent.com/120294654/206965338-c2f04710-f290-4cc4-b6e0-0c5280347c43.png)

**Comment by CodFrm** [comment]
应该是同一个问题导致的脚本无法导入

**Comment by Chinesered** [comment]
是的，所有脚本都突然无法使用了

**Comment by CodFrm** [comment]
@Chinesered 你可以使用此版本，或者也将你的错误贴出来试试 https://github.com/scriptscat/scriptcat/actions/runs/3673307388
