### ISSUE TITLE
GM_addElement is not a function

### ISSUE THREAD

**Issue by BolinChan** [scriptscat/scriptcat#124]
[JavScript](https://sleazyfork.org/scripts/435360-javscript/code/JavScript.user.js) 脚本无法正常使用，提示 *GM_addElement is not a function at DOC.addEventListener.once (JavScript.user.js:1755:21)*.
iframe 内调用 `GM_addElement` 的报错致使指令菜单 `控制面板` 未生效

Violentmonkey / TamperMonkey 内正常运行
**[NSFW]** [JavBus](https://www.javbus.com/) / [JavDB](https://javdb.com/) 任意页面复现

**Comment by CodFrm** [comment]
使用0.11.0-beta.1以上的版本试试

该函数在0.11.0-beta.1才开始支持

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/actions/runs/3718908054
