### ISSUE TITLE
脚本同步自动关闭问题

### ISSUE THREAD

**Issue by Jeremy-stu** [scriptscat/scriptcat#125]
明明启用了脚本同步至WebDAV，过一段时间就关闭了

**Comment by CodFrm** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/22783163/207369428-cd7977aa-29e9-4826-8544-c69304683eeb.png">

筛选一下，看看有没有日志

**Comment by Jeremy-stu** [comment]
> <img width="1437" alt="image" src="https://user-images.githubusercontent.com/22783163/207369428-cd7977aa-29e9-4826-8544-c69304683eeb.png">
> 
> 筛选一下，看看有没有日志

![FireShot Capture 007 - Home - ScriptCat - liilgpjgabokdklappibcjfablkpcekh.png](https://user-images.githubusercontent.com/76563274/207373932-b2ce63a4-5ca0-4a64-b2b6-092e14bb33e4.png)
从九号开始就不同步了

**Comment by CodFrm** [comment]
看起来是产生了一次网络错误导致同步失败，然后不再同步了

这个问题会在后续版本进行优化，失败将失败的任务放到一个队列，定时重试，不再自动关闭同步。

**Comment by duoluodexiaoxiaoyuan** [comment]
同步webDav的作用是什么呢

**Comment by CodFrm** [comment]
@duoluodexiaoxiaoyuan webdav是一个文件协议，可以上传/下载/删除文件，例如坚果云就支持webdav

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/releases/tag/v0.11.0
