### ISSUE TITLE
弹出菜单显示似乎有些问题

### ISSUE THREAD

**Issue by CJCchester** [scriptscat/scriptcat#129]
同一个脚本，同一个页面。
如下是油猴的截图：
![image](https://user-images.githubusercontent.com/87079803/208884168-860c8ee0-01c7-4f4d-b8a2-ec5d2d52d699.png)
如下是猫的截图（已关闭油猴）：
![image](https://user-images.githubusercontent.com/87079803/208886789-70cc4a28-127d-480a-b032-3b4dd4f6bcf8.png)
油猴的菜单鼠标悬停在脚本标题可以看到h5脚本执行了三次（这个功能希望猫也加上）但油猴的菜单显示正常，而猫的h5脚本的菜单重复显示了多次

**Comment by CodFrm** [comment]
可以将页面链接提供以下么

**Comment by CJCchester** [comment]
> 可以将页面链接提供一下么

b站的任意视频页面，比如https://www.bilibili.com/video/BV1114y1M7pT

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/actions/runs/4459658919
