### ISSUE TITLE
[白名单功能]希望增加像油猴一样的按钮设置某个脚本在某些页面不加载

### ISSUE THREAD

**Issue by 42795748** [scriptscat/scriptcat#13]

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptcat/issues/144

<img width="364" alt="image" src="https://user-images.githubusercontent.com/22783163/226162091-bb786065-efd6-484e-8c15-33b3ddb57df6.png">

https://github.com/scriptscat/scriptcat/actions/runs/4459474443
