### ISSUE TITLE
已安装脚本序号能否变动

### ISSUE THREAD

**Issue by qhq** [scriptscat/scriptcat#131]
如题，现在好像已安装脚本里序号是一直往后的，比如我装了20个脚本删掉了，再装序号就从21，22往后。
能否像Tampermonkey那样，序号仅现有脚本编号。装了20个，序号就是从1-20。排序那拖动顺序时，对应的序号也会发生变化，以方便重排。

**Comment by CodFrm** [comment]
现在的序号是id，这样的话，就是变成顺序了，也可以

**Comment by CodFrm** [comment]
perf: https://github.com/scriptscat/scriptcat/actions/runs/4520381808
