### ISSUE TITLE
在Mac下的Chrome无法正常使用

### ISSUE THREAD

**Issue by jikefan** [scriptscat/scriptcat#132]
## 使用环境
- Mac Big Sur11.4
- Chrome Version 108.0.5359.124 (Official Build) (x86_64)
- Scriptcat版本0.11.0
## 问题
- 我自己新建的脚本，编写测试代码并启动。scriptcat无法识别
<img width="360" alt="image" src="https://user-images.githubusercontent.com/50569006/211179750-09da522e-32b9-483b-9e33-045ba2f4d316.png">
- 插件home目录能够识别
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/50569006/211179784-ab6b9e4c-fd8f-49d0-8ace-39e29bba62f0.png">

## 我的脚本代码如下
``` javascript
// ==UserScript==
// @name         Beautify Man Pages
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  美化man.he.net 页面的内容
// @author       Jikefan
// @match        http*://man.he.net/*
// @run-at       document-body	
// ==/UserScript==

const myBodyStyle = () => {
    return 'font-size:12px';
}

(function() {
    'use strict';

    let body = document.getElementsByTagName('body')[0];
    
    body.style = myBodyStyle();
    alert('识别出来了');
})();
```

## 最后吐槽
不光是自己写的脚本没法检测出来，有时候下载的脚本虽然检测出来了，但是scriptcat就是不执行脚本，就是不工作。太烦了，于是只能用scriptcat来写代码，然后放油猴运行了。但是scriptcat的界面实在太友好了，所以希望尽快解决这个问题。

**Comment by jikefan** [comment]
## 问题解决了
`// @match        http*://man.he.net/*`
这个http后面的*去掉就行了

**Comment by CodFrm** [comment]
match实现与其它管理器的可能有些不同，这种格式的不兼容 下个版本处理一下

**Comment by CodFrm** [comment]
你执行的网站是`http://man.he.net/`么？

**Comment by jikefan** [comment]
> 
是的
