### ISSUE TITLE
WebDAV无法同步更新

### ISSUE THREAD

**Issue by Jeremy-stu** [scriptscat/scriptcat#133]
更新脚本后云同步没有更新，结果又把旧版同步过来了，然后脚本检测到更新又会更新......一直循环导致每天都会跳出来更新某个脚本的界面

**Comment by CodFrm** [comment]
测试webdav未出现此情况，可以将日志筛选出来看看么？或者试试百度网盘/OneDrive
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/22783163/212464193-8c5b55d3-7f99-422b-b73f-511302fb5f3f.png">

**Comment by Jeremy-stu** [comment]
> 测试webdav未出现此情况，可以将日志筛选出来看看么？或者试试百度网盘/OneDrive
> <img width="1436" alt="image" src="https://user-images.githubusercontent.com/22783163/212464193-8c5b55d3-7f99-422b-b73f-511302fb5f3f.png">
> 

![Snipaste_2023-01-14_17-41-30.png](https://user-images.githubusercontent.com/76563274/212466008-d91f8679-51e1-4ce9-8f2a-620576a20005.png)
![Snipaste_2023-01-14_17-41-48.png](https://user-images.githubusercontent.com/76563274/212466011-17177d51-45a5-40b6-a295-7f92308383ae.png)

**Comment by CodFrm** [comment]
大概看明白了，可以这样试试：

先删除掉脚本、然后等待同步将脚本同步下来，然后再删除这个同步的脚本，然后再安装脚本

这个问题应该是同步的地方有两份脚本导致的（一份新的一份旧的）我看看怎么修复这个问题

**Comment by CHxCOOH** [comment]
实测 OneDrive 同步也有一样的问题，更新完同步一下又用旧版覆盖了…

其实也可以直接让用户选择“同步（合并）”、“上传”、“下载”？

**Comment by CodFrm** [comment]
@CHxCOOH 应该是同一个问题，试试上面说的步骤
