### ISSUE TITLE
greasyfork不显示已安装，能不能增加一键搜索当前网站脚本

### ISSUE THREAD

**Issue by AzureBlue0219** [scriptscat/scriptcat#134]
主页希望可以显示greasyfork，github等脚本网站
![网页捕获_16-1-2023_152324_iikmkjmpaadaobahmlepeloendndfphd](https://user-images.githubusercontent.com/48849383/212620805-3938345a-c469-49e9-9bd4-476de0b95bbe.jpeg)
以及greasyfork不会像油猴一样显示已安装
![网页捕获_16-1-2023_152550_greasyfork org](https://user-images.githubusercontent.com/48849383/212621656-2e9ac811-3a75-41da-abc4-c29bb2adafe9.jpeg)
还有可不可以加上一件搜索当前网站脚本
![2023-01-16_152847](https://user-images.githubusercontent.com/48849383/212621819-9d5ef80d-ac96-4f53-bbec-7362c3722f3f.png)
感谢开发者

**Comment by CodFrm** [comment]
`greasyfork不会像油猴一样显示已安装`看起来是bug，我只吃过gf的

`搜索当前网站脚本`，之前有不少用户提过，现在有计划内置

可以先试试这个方案，我觉得也是极好：https://github.com/scriptscat/scriptcat/issues/69

**Comment by AzureBlue0219** [comment]
> `greasyfork不会像油猴一样显示已安装`看起来是bug，我只吃过gf的
> 
> `搜索当前网站脚本`，之前有不少用户提过，现在有计划内置
> 
> 可以先试试这个方案，我觉得也是极好：#69

这个方案挺方便，也挺漂亮。但是个人感觉不是很方便，网站只显示一次，我不能随时使用这个功能（使用他的插件应该可以），以及如果不小心关闭的话不知道如何再次寻找，希望您可以优化一下。
我看到脚本排序有人提了，希望能增加批量操作

**Comment by CodFrm** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/22783163/226162401-821bd9ed-05ee-42ac-920d-ec5303183a10.png">

现在点击此处会跳转到 https://scriptcat.org/search?domain=bilibili.com 的域名搜索

**Comment by CodFrm** [comment]
`greasyfork不会像油猴一样显示已安装` 这个问题可能是与其他的扩展冲突了，因为gf不支持scriptcat的方法，只能mock tampermonkey的方法，两个扩展都存在的时候可能就冲突了
