### ISSUE TITLE
responseType: "document" 不支持

### ISSUE THREAD

**Issue by Kn0wns** [scriptscat/scriptcat#136]
```js
GM_xmlhttpRequest({
    method: "GET",
    url: "https://bbs.kanxue.com/",
    responseType: "document",
    onload: xhr => console.log(xhr),
    onerror: () => console.log('网络错误')
});
```

![image](https://user-images.githubusercontent.com/76414050/212901183-7717e527-b3e5-4b90-af81-bbd0e4b935f5.png)

**Comment by CodFrm** [comment]
看起来是后台脚本的运行环境，后台脚本暂时不支持document，可以加入后续更新计划

**Comment by loadkk** [comment]
> 看起来是后台脚本的运行环境，后台脚本暂时不支持document，可以加入后续更新计划
普通脚本运行也是失败的，请求是正常发出并且响应也没问题
![image](https://user-images.githubusercontent.com/76414050/213163955-19b9a021-e189-4144-a418-d47ee389b910.png)

**Comment by CodFrm** [comment]
这样运行还是在后台脚本的环境中，普通脚本是指的有@match的脚本，例如：

```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        https://bbs.tampermonkey.net.cn/
// @grant        GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
    url: "https://bbs.tampermonkey.net.cn/",
    responseType: "document",
    onload(data) {
        console.log(data.response);
    }
})
```

然后打开链接：https://bbs.tampermonkey.net.cn/

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/22783163/213180850-02297ac0-e2a1-4b89-a2f9-4acdfc38024c.png">

**Comment by CodFrm** [comment]
后台脚本，暂时不打算也不太好支持此功能

需要的话，可以考虑通过三方库去解析responseText成document
