### ISSUE TITLE
更新时30秒太短

### ISSUE THREAD

**Issue by plokid** [scriptscat/scriptcat#137]
如题，更新时30秒后会关闭更新页面，没有时间去仔细看看更新了什么
或许有方法我不知道？

**Comment by CodFrm** [comment]
30s确实是有点短了，下版本优化一下

由系统检查的更新有倒计时，如果是自己手动更新不会有

手动更新方式，点击最后更新这一栏

<img width="701" alt="image" src="https://user-images.githubusercontent.com/22783163/213179745-74524e15-4cf6-4780-947d-1e5ace047969.png">

**Comment by plokid** [comment]
请问能不能在自动更新页面加一个停止计时按钮？

**Comment by CodFrm** [comment]
延长至60s，第一次点击将暂停，第二次点击关闭
