### ISSUE TITLE
【问题/BUG】脚本猫的@icon没被写入进GM_info.script

### ISSUE THREAD

**Issue by 1665169869** [scriptscat/scriptcat#139]
当我在脚本中设置了`@icon`属性后
`//@icon             https://docs.scriptcat.org/img/logo.png`
使用GM_info.script的时候发现icon不在该对象里
但同样的代码我使用油猴的话就一切正常，如图：
**脚本猫**
![image](https://user-images.githubusercontent.com/50762038/213860172-47370496-49c8-4a2d-9348-159e4774673a.png)
**油猴**
![image](https://user-images.githubusercontent.com/50762038/213860125-f59821a0-c3fb-48f5-9311-9e21db5b4c8a.png)

**Comment by CodFrm** [comment]
暂时没有写入太多的信息，下个版本完善
