### ISSUE TITLE
与脚本 AC-Baidu 的兼容性问题

### ISSUE THREAD

**Issue by PianCat** [scriptscat/scriptcat#14]
复现概率：
100%复现

复现方式：
当使用脚本 [AC-Baidu](https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97) 进入对应页面的时候，并不会成功加载脚本功能

插件版本：
0.7.2

浏览器版本：
Chrome 96.0.4664.45 (x64)

[Log Here](https://raw.githubusercontent.com/PianCat/APTSSF/main/AC-Baidu_ScriptCat_Log/www.baidu.com-1637071546502.log)

**Comment by PianCat** [comment]
虽然不知道有没有用，但是还是先放个Log上来

**Comment by CodFrm** [comment]
可以给一个页面的url吗？

**Comment by PianCat** [comment]
> 可以给一个页面的url吗？

使用百度搜索任意关键词都会触发该bug

**Comment by CodFrm** [comment]
![image](https://user-images.githubusercontent.com/22783163/142558653-8b93ae25-dc5a-4b2a-bdf4-f2c94227aa09.png)

貌似是正常的，哥哥可以看看你的截图么？

看报错信息有点像是脚本改动错了，是不是哥哥修改过脚本？

**Comment by PianCat** [comment]
> ![image](https://user-images.githubusercontent.com/22783163/142558653-8b93ae25-dc5a-4b2a-bdf4-f2c94227aa09.png)
> 
> ![image](https://user-images.githubusercontent.com/22783163/142558702-b25a4794-731f-4038-a09c-33b85c869c48.png)
> 
> 貌似是正常的，哥哥可以看看你的截图么？
> 
> 看报错信息有点像是脚本改动错了，是不是哥哥修改过脚本？

怪事，晚点我试试重新安装脚本，我记得没动过脚本来着

**Comment by CodFrm** [comment]
@PianCat 怎么样了哥哥？

**Comment by PianCat** [comment]
> @PianCat 怎么样了哥哥？

重装插件之后好像正常了

**Comment by cesaryuan** [comment]
好像现在还是不支持诶
版本：
AC-baidu-重定向优化百度搜狗谷歌必应搜索_favicon_双列：26.03
script-cat版本：0.9.4

![image](https://user-images.githubusercontent.com/35998162/195751234-bebd1cdb-8687-45fc-ab54-62c08239e8a9.png)

**Comment by CodFrm** [comment]
> @CodFrm 好像现在还是不支持诶 版本： AC-baidu-重定向优化百度搜狗谷歌必应搜索_favicon_双列：26.03 script-cat版本：0.9.4
> 
> ![image](https://user-images.githubusercontent.com/35998162/195751234-bebd1cdb-8687-45fc-ab54-62c08239e8a9.png)

正常的呀，检查一下是不是网络问题 require没加载成功，重新安装试试 后续优化一下这个问题
