### ISSUE TITLE
firefox 109.0 (64 位)国际版无法安装0.11.1版本

### ISSUE THREAD

**Issue by W-Karl-Marx** [scriptscat/scriptcat#140]
提示如图 
![图片](https://user-images.githubusercontent.com/35687330/213929510-4e47ce58-bdd5-4362-b53c-d8eda732997b.png)

**Comment by CodFrm** [comment]
是使用的什么文件安装的呢？Firefox可以直接从商城下载，但是因为审核原因，还在跟进中，最近过年一直没时间，好像都被下架了

**Comment by W-Karl-Marx** [comment]
>

**Comment by W-Karl-Marx** [comment]
> 

用的zip文件，确实商店直接下载会方便

**Comment by CodFrm** [comment]
zip文件需要使用调试方式安装，没有打包成firefox支持的扩展文件（后面再试试）

<img width="308" alt="image" src="https://user-images.githubusercontent.com/22783163/214495402-ca31d7cc-e766-445c-aada-a8e6dd97a21f.png">

<img width="858" alt="image" src="https://user-images.githubusercontent.com/22783163/214495437-78c19f51-09b9-4a06-a190-512481c8ab3f.png">

**Comment by W-Karl-Marx** [comment]
> zip文件需要使用调试方式安装，没有打包成firefox支持的扩展文件（后面再试试）
> 
> <img alt="image" width="308" src="https://user-images.githubusercontent.com/22783163/214495402-ca31d7cc-e766-445c-aada-a8e6dd97a21f.png">
> 
> <img alt="image" width="858" src="https://user-images.githubusercontent.com/22783163/214495437-78c19f51-09b9-4a06-a190-512481c8ab3f.png">

好的 谢谢大佬
