### ISSUE TITLE
「BUG」删除脚本后总是自动恢复

### ISSUE THREAD

**Issue by chaofanx** [scriptscat/scriptcat#141]
开启了脚本猫的各种云同步，onedrive, 删除一个脚本后一段时间后总是会自动恢复回来

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptcat/issues/133 应该是同一个问题

**Comment by chaofanx** [comment]
> #133 应该是同一个问题

看起来是，我试试这个操作

**Comment by chaofanx** [comment]
> #133 应该是同一个问题

还是会自动恢复，而且我不是更新脚本，就是彻底删除这个脚本，每次删掉一段时间后就恢复了

**Comment by chaofanx** [comment]
还是会出现。。

**Comment by chaofanx** [comment]
现在版本还是存在这个问题

**Comment by CodFrm** [comment]
@chaofanx v0.14.1版本么？

有几台设备开启了同步呢？看看该脚本的日志，另外可以进onedrive里看看同步源文件，删除时源文件有没有删除
