### ISSUE TITLE
已删除的脚本又恢复

### ISSUE THREAD

**Issue by lawchou** [scriptscat/scriptcat#143]
启用同步至坚果云webdav，勾选了同步删除。办公电脑和家里电脑同步至同一个webdav账号，已经删除的脚本会再次出现。
![微信截图_20230213093713](https://user-images.githubusercontent.com/73280921/218351918-59c37cab-706f-44cd-9437-709652192897.png)

**Comment by CodFrm** [comment]
0.11.2版本么？

**Comment by lawchou** [comment]
您好，您的邮件我已收到！

**Comment by CodFrm** [comment]
``

**Comment by lawchou** [comment]
您好，您的邮件我已收到！
