### ISSUE TITLE
脚本全部丢失, 请问在数据库找到相关脚本文件?

### ISSUE THREAD

**Issue by hhuimie** [scriptscat/scriptcat#145]
rt, 0.9.1版本, 浏览器所有扩展也不见了, 目前能在本地找到leveldb和blob, 但是打开是乱码
请教如何在本地打开数据库, 有没有什么软件之类的, 如何找到对应脚本
非常感谢!
![image](https://user-images.githubusercontent.com/4830177/219527322-88c7af27-a976-436d-837f-6e3d561ad990.png)
![image](https://user-images.githubusercontent.com/4830177/219527515-f94433c9-6906-469a-ac89-a0ed9b2594ca.png)
![image](https://user-images.githubusercontent.com/4830177/219527527-17d64019-43d3-470a-9e87-57c0e895a747.png)

**Comment by CodFrm** [comment]
先把这些数据备份出来吧，然后用其它浏览器安装扩展，再把这些数据拷贝过去

访问这个页面（edge为例子）：edge://indexeddb-internals/ 可查看所有的indexeddb数据存储目录和下载备份

是因为浏览器的原因么？所有扩展都没了？

**Comment by hhuimie** [comment]
> 先把这些数据备份出来吧，然后用其它浏览器安装扩展，再把这些数据拷贝过去
> 
> 访问这个页面（edge为例子）：edge://indexeddb-internals/ 可查看所有的indexeddb数据存储目录和下载备份
> 
> 是因为浏览器的原因么？所有扩展都没了？

是浏览器问题
我尝试了你的做法, 不行, copy过去, 然后扩展打开, 本地的文件就消失了, 恢复默认

**Comment by hhuimie** [comment]
恢复了, 用同样的浏览器版本, 加上直接回复所有浏览器数据可以了, 虽然还有些小bug
谢谢你~
