### ISSUE TITLE
定时脚本使用 GM_openInTab() 会多次打开

### ISSUE THREAD

**Issue by zhongsir98** [scriptscat/scriptcat#147]
初步判断 一个GM_openInTab 会打开三次页面，（chrome \edge  其他未测试）

// ==UserScript==
// @name         定时任务，作为打开页面功能
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @crontab      0 21 * * * 
// @grant        GM_openInTab
// ==/UserScript==

return new Promise((resolve, reject) => {
    // Your code here...
    GM_openInTab('https://www.baidu.com')
    resolve();
});

**Comment by CodFrm** [comment]
没有复现成功，点击立即运行一次呢？

**Comment by zhongsir98** [comment]
我也复现不出了，这还薛定谔了；
调试运行完全正常的，这几日正式使用都碰上了

**Comment by CodFrm** [comment]
好像是更新脚本导致的，老版本没有停止计时器

**Comment by CodFrm** [comment]
更新此版本试试 https://github.com/scriptscat/scriptcat/actions/runs/4315194067
