### ISSUE TITLE
问题：已关闭的脚本 仍然在执行

### ISSUE THREAD

**Issue by hanfeicode** [scriptscat/scriptcat#149]
我写了一个脚本 每分钟 桌面提醒之类的
1、开启按钮选择关闭 但是每分钟还执行通知
2、有时候还执行好几次

无奈之下只能删除这个脚本，貌似删除了重新新建的脚本就会正常点，大家有遇到的吗

**Comment by CodFrm** [comment]
应该与 #147 是类似的问题，可以重启扩展试试，最近会修复

**Comment by CodFrm** [comment]
更新此版本试试 https://github.com/scriptscat/scriptcat/actions/runs/4315194067
