### ISSUE TITLE
慕课课程页面不停显示异常脚本

### ISSUE THREAD

**Issue by CJCchester** [scriptscat/scriptcat#150]
网址：https://www.icourse163.org/learn/CSU-1206894807
显示：
![image](https://user-images.githubusercontent.com/87079803/223450296-34c51649-1944-47b1-aa9a-62fb2deb0353.png)
我把脚本都关了只开着脚本猫还是不停显示，关了脚本猫就正常了

**Comment by CodFrm** [comment]
所以最后啥原因呢？脚本没关干净？
