### ISSUE TITLE
match 与 TM 不兼容

### ISSUE THREAD

**Issue by i-CraftY** [scriptscat/scriptcat#151]
```js 
//@match url1
//@match url2 
...
```

图示
![1](https://user-images.githubusercontent.com/42453713/223588496-b25c2c6a-e4be-4951-a23a-2581467f24e7.png)
url是整个图片
url1-url3都在url所在的html页面
TM可以在url中匹配url1、url2和url3
SC匹配不到
### 具体规则是这样的
```js
// @match        */clientWeb/quesiton/questionList.jsp?*
// @match        */clientWeb/quesiton/questionForward.jsp?*
```
但是
```js
// @match    http*://wvpn.xxx.edu.cn/*/clientWeb/quesiton/questionList.jsp?*
```
这样又是可以的

**Comment by CodFrm** [comment]
SC的match需要有http前缀

可以试试这样： `//@match *://*/clientWeb/quesiton/questionList.jsp?*`

**Comment by i-CraftY** [comment]
> SC的match需要有http前缀
> 
> 可以试试这样： `//@match *://*/clientWeb/quesiton/questionList.jsp?*`

解决了

**Comment by CodFrm** [comment]
尽量按照(Match patterns)[https://docs.scriptcat.org/docs/dev/meta/#match]来
