### ISSUE TITLE
crontab 出错

### ISSUE THREAD

**Issue by i-CraftY** [scriptscat/scriptcat#152]
`// @crontab      */5 10-16 * * 2-0`

按照表达式下次运行时间应该是星期二到星期天的10-16点，每隔5分钟。

发现的问题是把范围起始日期设置为当天前的时间(*/5 10-16 * * 1-0)，就会直接到下一个起始运行。可以复现

![QQ截图20230308124637](https://user-images.githubusercontent.com/42453713/223622069-c60b6f8a-1941-4268-a7f1-0c8f34aa632e.png)
![QQ截图20230308125842](https://user-images.githubusercontent.com/42453713/223623570-9f7f656b-eb7c-42f5-aaa6-f7a59cd81ac1.png)

**Comment by CodFrm** [comment]
好像确实是一个bug，可以先尝试这样：`// @crontab      */5 10-16 * * 2-6,0`

**Comment by CodFrm** [comment]
目前复现不出来了，并且作者说解决了，我先更新包试试
