### ISSUE TITLE
几个影响体验的bug

### ISSUE THREAD

**Issue by i-CraftY** [scriptscat/scriptcat#154]
issues提交有点频繁了😬

## 1、储存过长，操作按钮消失
![QQ截图20230312173625](https://user-images.githubusercontent.com/42453713/224537531-923ba045-10f6-49dd-90ff-04b36f15ad2d.png)
## 2、不知道什么原因造成的，点脚本储存会卡死
可能是存储比较大。
东方永页机https://github.com/hoothin/UserScripts/tree/master/Pagetual
## 3、这不算bug，稍微影响体验
跨域有没有允许所有域名的方法，每次到一个新的域名都要点同意，就像上面翻页脚本一样

**Comment by CodFrm** [comment]
发现问题，解决问题，才能变得更好

1、2我看看优化一下

3、没有允许所有域名的方法，如果允许所以的话，这样限制就没意义了，如果同时有多次弹出的话，管理器会合并这些请求，并显示一个允许所有域的按钮由用户确定

**Comment by i-CraftY** [comment]
> 发现问题，解决问题，才能进步
> 
> 1、2我看看优化一下
> 
> 3、没有允许所有域名的方法，如果允许所以的话，这样限制就没意义了，如果同时有多次弹出的话，管理器会合并这些请求，并显示一个允许所有域的按钮由用户确定

好像还有点问题，面板可不可以多列显示或者修改下逻辑。
问题是有多个脚本match到了域名，但是不能全部显示，并且已开启和未开启脚本貌似并没用优先级上的差异。

**Comment by CodFrm** [comment]
不能全部显示是什么意思？应该会全显示的，已开启和未开启有顺序的呀，已开启的会在前面

可以截个图吗？

**Comment by i-CraftY** [comment]
![动画](https://user-images.githubusercontent.com/42453713/224715800-c662ef54-69de-4ecd-b25b-db338b3f8d59.gif)



~~图有点大，哥哥忍一下~~

显示的数量是脚本运行数吗，可以看到点一下就增加，但是看不到脚本。用油猴测试是正常的，不会增加。

可能和frame有关，途中左边和右边都是不同的frame

**Comment by CodFrm** [comment]
显示的数量是脚本运行的次数（因为有的是iframe），后续我加一个，具体哪个脚本运行了多少次

之前说的`不能全部显示`是什么意思？应该会全显示的，已开启和未开启有顺序的呀，已开启的会在前面

**Comment by i-CraftY** [comment]
> 显示的数量是脚本运行的次数（因为有的是iframe），后续我加一个，具体哪个脚本运行了多少次
> 
> 之前说的`不能全部显示`是什么意思？应该会全显示的，已开启和未开启有顺序的呀，已开启的会在前面

就是上图中只可以看见两个，实际上还有第三个。附一张油猴的
![QQ截图20230314201948](https://user-images.githubusercontent.com/42453713/224999227-07983ce1-ae66-450e-810c-32156762d554.png)

**Comment by CodFrm** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/22783163/225225925-cbaa4ad4-2245-4c11-8b5a-30ed3b48bb5f.png">

哥哥屏幕多大？我这里可以正常显示

**Comment by i-CraftY** [comment]
> <img alt="image" width="600" src="https://user-images.githubusercontent.com/22783163/225225925-cbaa4ad4-2245-4c11-8b5a-30ed3b48bb5f.png">
> 
> 哥哥屏幕多大？我这里可以正常显示

不是这个，这个是点存储就卡死
是这个https://scriptcat.org/script-show-page/616,里面存了一张图片的base64编码
分辨率是2240x1400，14英寸

**Comment by i-CraftY** [comment]
现在可以打开了，显示不下
![QQ截图20230315144424](https://user-images.githubusercontent.com/42453713/225228094-fb1139a3-b69f-4738-a8e5-841a017475fa.png)

**Comment by CodFrm** [comment]
卡顿问题可以试试这个，但是按钮不显示出来的问题这个没有复现出来

https://github.com/scriptscat/scriptcat/actions/runs/4449614460/jobs/7814037084

**Comment by i-CraftY** [comment]
> 卡顿问题可以试试这个，但是按钮不显示出来的问题这个没有复现出来
> 
> https://github.com/scriptscat/scriptcat/actions/runs/4449614460

我好像找到稳定复现的方法了
https://www.ikandy.fun/vodplay/49038-1-1/  这里就有iframe
```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        *://*mmiyue.com*
// @match        *://*vodplay*
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
})();
```

**Comment by CodFrm** [comment]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/22783163/226117838-7991bf77-d24a-4ad3-9d50-08adf909a21c.png">

修复了 https://github.com/scriptscat/scriptcat/actions/runs/4456211658

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptcat/actions/runs/4456439721 这个吧
