### ISSUE TITLE
移动端最新play版火狐怎么安装？

### ISSUE THREAD

**Issue by gkongy** [scriptscat/scriptcat#156]
找不到安装接口

**Comment by Furrylang** [comment]
![Screenshot_2023-03-24-12-54-14-019-edit_org mozilla firefox_beta](https://user-images.githubusercontent.com/42689675/227427770-af106a76-ff91-4fbe-abf7-24b8ce15a166.jpg)
自己去建造个收藏夹 把想要的扩展加进去即可 这个扩展目前不支持火狐 建议用暴力猴 同样开源 支持安卓

**Comment by CodFrm** [comment]
@Furrylang 怪不得经常有人收藏

后续我对Firefox android兼容一下

**Comment by CodFrm** [comment]
我没有看见自定义附加组件收藏集这个选项，是需要特定版本么？

**Comment by Furrylang** [comment]
@CodFrm 需要beta版本
![Uploading Screenshot_2023-06-15-14-55-33-096_org.mozilla.firefox_beta-edit.jpg…]()
