### ISSUE TITLE
为什么脚本猫页面没有新建脚本选项?

### ISSUE THREAD

**Issue by wayrboy** [scriptscat/scriptcat#16]
为什么脚本猫页面没有新建脚本选项?

**Comment by CodFrm** [comment]
有的呀，这是第一个入口：
![image](https://user-images.githubusercontent.com/22783163/143685640-43abc495-c17b-4f9a-ba9a-80c30a6b84e9.png)

这是第二个入口：
![image](https://user-images.githubusercontent.com/22783163/143685661-363cf146-aec1-474c-a2a0-79411c8c919c.png)

**Comment by wayrboy** [comment]
哦,谢谢没仔细看,刚开始学习油猴脚本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scriptscat/scriptcat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月27日(星期六) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [scriptscat/scriptcat] 为什么脚本猫页面没有新建脚本选项? (Issue #16)





 
有的呀，这是第一个入口：
 
 
这是第二个入口：
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CodFrm** [comment]
哥哥加油，等待下一个油猴王！

**Comment by wayrboy** [comment]
ggnb
