### ISSUE TITLE
备份列表出错

### ISSUE THREAD

**Issue by ChitaGideon** [scriptscat/scriptcat#160]
点击 备份列表 和备份  报错

获取备份文件失败: Error: {"error":{"code":"InvalidAuthenticationToken","message":"CompactToken validation failed with reason code: 80049228.","innerError":{"date":"2023-03-23T08:31:39","request-id":"96edd453-b738-4f51-a41f-74346fcc54f2","client-request-id":"96edd453-b738-4f51-a41f-74346fcc54f2"}}}

在设置里，点击启用脚本同步   保存，居然显示成功
这种怎么解决？

**Comment by ChitaGideon** [comment]
v0.11.3

**Comment by CodFrm** [comment]
下午服务器出了点问题，现在再试试呢？

**Comment by ChitaGideon** [comment]
嗯 可以了
