### ISSUE TITLE
Uncaught (in promise) Error: MetaData信息错误

### ISSUE THREAD

**Issue by zip11** [scriptscat/scriptcat#161]
插件运行使用一段时间，在chrome扩展插件里面有错误按钮，
不知道是 脚本的错误，还是插件的错误

提示错误信息
Uncaught (in promise) Error: MetaData信息错误

上下文
src/background.html
堆叠追踪
src/background.js:1 (匿名函数)

`

**Comment by CodFrm** [comment]
插件的问题

应该是脚本的Userheader部分格式不正确

**Comment by zip11** [comment]
把脚本Userheader部分额外的注释 //  删除，用了会，不报错了

**Comment by CodFrm** [comment]
可以看一下报错的脚本内容么？

**Comment by CodFrm** [comment]
缺少某些header的情况下会导致这个问题，后续再优化看一下

**Comment by zip11** [comment]
> 可以看一下报错的脚本内容么？

太长发不出去，就是文件头申请权限最后一行，只写注释，不写申请权限的文本，就会报错，删除注释就好了

**Comment by zip11** [comment]
> 可以简化一下，可以复现就行，或者截图，这样说我还是不太明白

// @grant        none
// 注释会出错
// ==/UserScript==

注释这行存在就会报错，删除就没有问题

**Comment by CodFrm** [comment]
添加了数据校验，不合法的header会提示具体原因
