### ISSUE TITLE
我的脚本怎么全没了

### ISSUE THREAD

**Issue by mlstudyhard** [scriptscat/scriptcat#162]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/118589469/228735060-16264af5-c88b-4ed2-91c7-22cff246fb6f.png">

**Comment by CodFrm** [comment]
什么浏览器？请提供详细点的信息，图片也挂了

**Comment by mlstudyhard** [comment]
谷歌浏览器，昨晚上还好好的，今天才打开电脑全没了






37662465
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scriptscat/scriptcat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [scriptscat/scriptcat] 我的脚本怎么全没了 (Issue #162)





 
什么浏览器？请提供详细点的信息，图片也挂了

**Comment by mlstudyhard** [comment]
> ~什么浏览器？请提供详细细节的信息，图片也挂了~
> 
> 看一下f12开发者工具中的IndexedDB有没有数据，或者f12的console中有没有报错信息

<img width="415" alt="image" src="https://user-images.githubusercontent.com/118589469/228744432-7f4dc92a-d510-43f5-8082-1eaccb324839.png">

**Comment by mlstudyhard** [comment]
然后怎么办

**Comment by CodFrm** [comment]
在扩展的页面中打开f12

我看是不是数据库报错，还是什么原因。

另外日志中有数据么？

没有报错，也没有数据的话，可能是你误删了。。。

**Comment by ViCrack** [comment]
我这更新之后也没了，用的是firefox 111.0.1版本

但是edge还有的，而且扩展也更新到了0.12.0版本


IndexedDB有脚本数据，但是控制台没报错，啥也没输出（刷新过、重启过浏览器）

![图片](https://user-images.githubusercontent.com/18179821/229670898-16c47750-75da-4f79-9c62-80d95594fb82.png)


点击备份会报错
![图片](https://user-images.githubusercontent.com/18179821/229671108-acb44b25-5d08-4c70-8404-abc8b056c8f8.png)


用的是坚果云同步，而且发现firefox有一些脚本同步也无法成功，不知道是不是同步这块出的问题

我现在准备卸载后从edge迁移了

**Comment by CodFrm** [comment]
@ViCrack 是从 0.11.x版本升级到0.12.0么？

**Comment by ViCrack** [comment]
是这样的，因为扩展是有自动更新的，所以我一般都是用最新版本。

还有就是firefox浏览器也更新到最新版了，也就是今天早上才发现的事情

**Comment by CodFrm** [comment]
后续还有反馈，可以保留环境在tg联系我：

https://t.me/scriptscat

集中到这个issue吧：https://github.com/scriptscat/scriptcat/issues/172
