### ISSUE TITLE
拖动排序后 ，升序降序 依旧是重新排序前

### ISSUE THREAD

**Issue by AzureBlue0219** [scriptscat/scriptcat#164]
拖动排序后 ，升序降序 依旧是重新排序前
![2023-04-10_092029](https://user-images.githubusercontent.com/48849383/230807262-6438ca82-9e63-4c94-9cc7-0afeb6bf38ed.png)
还有能不能增加多选批量删除，以及加个回收站？

**Comment by CodFrm** [comment]
多选批量删除和回收站工作量有点大，后续安排

**Comment by CodFrm** [comment]
多选批量删除已实现，回收站功能暂不计划，在每次删除前都会有提示确认

**Comment by AzureBlue0219** [comment]
> 多选批量删除已实现，回收站功能暂不计划，在每次删除前都会有提示确认

谢谢，辛苦了
