### ISSUE TITLE
报错信息的改进建议

### ISSUE THREAD

**Issue by zip11** [scriptscat/scriptcat#169]
插件运行使用一段时间，在chrome扩展插件里面有错误按钮，
由于脚本太多不知道是 那个脚本的造成的错误，建议报错添加脚本名字信息

提示错误信息
Refused to set unsafe header "Content-Length"

上下文
src/background.html
堆叠追踪
src/vendor-27545368.js:2 (匿名函数)

**Comment by CodFrm** [comment]
这个错误好像是同步webdav库的，自定义了Content- Length，暂时没什么好办法处理

**Comment by zip11** [comment]
> 这个错误好像是同步webdav库的，自定义了Content- Length，暂时没什么好办法处理

应该是webdav同步，不影响正常使用

**Comment by CodFrm** [comment]
如果是脚本的错误日志建议使用 GM_log 处理，可以在管理面板的日志模块查询

chrome的错误暂时不进行处理了
