### ISSUE TITLE
在firefox下脚本【github增强】无法正常工作

### ISSUE THREAD

**Issue by IamApoorStudent** [scriptscat/scriptcat#170]
脚本地址：https://greasyfork.org/zh-CN/scripts/412245-github-%E5%A2%9E%E5%BC%BA-%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD
正常工作状态（tampermonkey下安装该脚本）：
![图片](https://user-images.githubusercontent.com/95626659/232184559-84e1c8b4-5d49-4f04-8649-8f17a3e6309c.png)
脚本猫状态：
![图片](https://user-images.githubusercontent.com/95626659/232184603-4b4bb981-9b29-46d0-b57f-b025ee1247f6.png)
![图片](https://user-images.githubusercontent.com/95626659/232184608-425e50af-2c3c-4777-83fa-97ea4bb2abfe.png)

**Comment by CodFrm** [comment]
貌似是因为github的安全策略导致的，但chrome没问题

这段时间在忙其它东西，先记录了

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/actions/runs/5099310400

修复方式有点暴力，看看后续有没有其他方案
