### ISSUE TITLE
插件会自动清空脚本

### ISSUE THREAD

**Issue by henrypeng7** [scriptscat/scriptcat#172]
如题，过一段时间就会自动脚本删除了，现在连续两天了，找不到原因

**Comment by CodFrm** [comment]
不是吧 看看日志

**Comment by henrypeng7** [comment]
> 不是吧看日志
> 
> 全部删除，还是部分？开启了同步功能么？
![image](https://user-images.githubusercontent.com/106166753/232704979-664c7626-fe06-4e4f-9955-980d280b9a4b.png)


全部删除，我去看了开启了同步功能，然后关了重新安装脚本，马上就没了

**Comment by henrypeng7** [comment]
现在安装新脚本直接不显示了，安装不了，得重新安装scriptcat了

**Comment by henrypeng7** [comment]
> <img alt="图像" width="1406" src="https://user-images.githubusercontent.com/22783163/232735067-e1767f4e-05cd-4737-ba19-17061dfc8ec8.png">
> 
> 这里的日志呢？
> 
> 其他看在管理页面的控制台，有什么报错

![image](https://user-images.githubusercontent.com/106166753/232768183-57b42bb8-7063-4016-8034-05cc28422490.png)
我重新安装过，就只有这些日志

**Comment by CodFrm** [comment]
不知道是不是都是windows用户遇到，有没有mac/linux用户遇到

初步判断是indexeddb的问题，但是不知道怎么引起的

**Comment by LoadingP** [comment]
![image](https://user-images.githubusercontent.com/50085558/232958167-d034b032-249a-432a-800e-b6752b10103a.png)
我也是，今天打开发现脚本被全部清空，不知道发生了什么

**Comment by henrypeng7** [comment]
> 好吧，需要错误时间的日志
> 
> 哥哥是更新了扩展么？还是一打开就是这样

一打开就是这样，扩展应该是自动更新的

**Comment by henrypeng7** [comment]
> 好吧，需要错误时间的日志
> 
> 哥哥是更新了扩展么？还是一打开就是这样

新情况，安装了过后已安装列表无脚本，但是是有的

**Comment by CodFrm** [comment]
@henrypeng7 @LoadingP  看一下日志呢？管理面板的那个日志

**Comment by henrypeng7** [comment]
> @henrypeng7 @LoadingP 看一下日志呢？管理面板的那个日志呢

![image](https://user-images.githubusercontent.com/106166753/232965288-6e1ee40c-e0b0-4792-906f-df070d8f4895.png)
更新脚本看起来蛮正常

**Comment by CodFrm** [comment]
看起来是正常的，方便加一个联系方式，远程看看吗？

**Comment by aduil** [comment]
嘤嘤嘤，最近版本自动更新后我之前的脚本全给清掉了

**Comment by CodFrm** [comment]
@aduil 有什么错误么？f12，看看有没有日志

**Comment by aduil** [comment]
> @aduil 有什么错误么？f12，看看有没有日志

现在就跟新安装的一样，console没报错，indexdb 里面scripts是空的。我是win10，没使用同步，电脑上同时装了 Edge 和 Edge Dev，两个浏览器的扩展里面都空掉了，两个浏览器里面本来还不一样的。

**Comment by CodFrm** [comment]
@aduil 你的硬盘空间足够么？

两台电脑？都被清空了？是只有脚本猫扩展还是有其他扩展呢？

**Comment by aduil** [comment]
> @aduil 你的硬盘空间足够么？
> 
> 两台电脑？都被清空了？是只有脚本猫扩展还是有其他扩展呢？

磁盘空间是够的，同一台电脑上安装的Edge 和 Edge Dev，其他扩展像OmegaProxy的数据是好的，不过它存储数据的方案不一样

**Comment by CodFrm** [comment]
后续还有反馈，可以保留环境在tg联系我：

https://t.me/scriptscat

**Comment by Chachekkk** [comment]
已安装的脚本能正常使用但是无法显示
![image](https://user-images.githubusercontent.com/30924313/236637135-09c69e1a-996a-4299-b8e3-f4a02027324c.png)
无法安装新的脚本
![image](https://user-images.githubusercontent.com/30924313/236637167-a19d5ba3-6e0c-45bb-b935-30fb37b285d1.png)

**Comment by CodFrm** [comment]
@Chachekkk f12看看应用程序中的indexeddb的scripts表

刚刚有位用户反馈，有一行的数据不知道为什么变为了null，我后面先做一下异常处理

**Comment by Day-T** [comment]
我的日志里面没有任何内容，但是也是indexdb里面这个位子有两行null

**Comment by CodFrm** [comment]
近期发现了这个问题，不确定会不会导致脚本清空，但是可能会导致`read large value`的问题

https://github.com/scriptscat/scriptcat/commit/4832a80b5a3c553563367892adcdf85e9832fc98
