### ISSUE TITLE
能否增加导出单个脚本？

### ISSUE THREAD

**Issue by AzureBlue0219** [scriptscat/scriptcat#175]
有的记录脚本需要存储个备份，但是只能导出全部太不方便

**Comment by zhangzong666** [comment]
你s吗？可以单个导入啊！非要单个导入！

**Comment by CodFrm** [comment]
楼上说得也确实有道理，不过单独导出可以让导出文件更小，也从根源上防止某些不希望导出的脚本泄漏

现在的解决办法是导出压缩包，然后手动删除压缩包里不希望导出的脚本

这个需求优先级比较低，以后再实现，有兴趣的也可以来pr

**Comment by CodFrm** [comment]
选择导出已实现

**Comment by AzureBlue0219** [comment]
> 选择导出已实现

谢谢，辛苦了
