### ISSUE TITLE
@nocors metadata block

### ISSUE THREAD

**Issue by sjehuda** [scriptscat/scriptcat#177]
Please pardon me for writing in English.  My Chinese is not fluent enough, yet.

---

Discussion at https://openuserjs.org/discuss/nocors_metadata_block

I think it would be useful to add `@nocors` metadata block (similarly to `@noframes`) which would be productive in the sense of coding and consequently make userscript managers to behave in a uniform fashion.

[no-www](https://openuserjs.org/scripts/sjehuda/no-www) is using `GM.xmlHttpRequest` which doesn't seem to be supported with all userscript managers (this issue was solved by [@makyen](https://github.com/greasemonkey/greasemonkey/issues/3160#issuecomment-1456758080), but please ignore this fact for the sake of the argument).

Example script
```js
// ==UserScript== 
// @name        no-www
// @namespace   org.openuserjs.sjehuda.no-www
// @description www. is deprecated. Redirect to URL without www.
// @author      Schimon Jehudah, Adv.
// @homepageURL https://no-www.org/
// @supportURL  https://openuserjs.org/scripts/sjehuda/no-www/issues
// @updateURL   https://openuserjs.org/meta/sjehuda/no-www.meta.js
// @copyright   2023, Schimon Jehudah (http://schimon.i2p)
// @license     MIT; https://opensource.org/licenses/MIT
// @run-at      document-start
// @include     *
// @grant       GM.xmlHttpRequest
// @version     23.03
// ==/UserScript==

if (!location.host.startsWith('www.')) return; // exit (else, continue)

var newURL = location.href.replace('://www.','://');

GM.xmlHttpRequest({
  method: 'GET',
  url: newURL,
  onprogress: console.log('Checking for no-www...'),
  onload: function(response) {
    if (response.finalUrl == newURL) {
      location.href = newURL;
    } else {
      console.log('Please contact webmaster to remove www. https://no-www.org/');
    }
  },
  onerror: function(response) {
    console.log('Error requesting for no-www')
  }
})
```

On another note, if `@nocors` would be introduced, this script canbe even shorter by using the "Fetch" API.
```js
fetch(newURL)
  .then((response) => {
     if (request.reseponseURL == newURL) {
       window.open(newURL,'_self');
     }
  })
```

Of note: This suggestion has been rejected by https://github.com/violentmonkey/violentmonkey/issues/1781

**Comment by CodFrm** [comment]
My English is not that good either 😂. If there are any misunderstandings, please correct me.

---

Regarding the `GM.xmlHttpRequest`, ScriptCat also supports it, but you need to declare `GM_xmlhttpRequest` instead of `GM.xmlHttpRequest`, which should be considered as a bug.

We focus more on the `@nocors` metadata block. I understand that this is a syntax sugar type of thing, and I think this kind of thing should be achieved by requiring a library with @require, and the script manager should focus more on allowing the script to break through some restrictions on the page.

**Comment by CodFrm** [comment]
Is the Falkon web browser a non-Chrome/Firefox series? Shouldn't this be a problem with the Greasemonkey extension or the Falkon browser, it has nothing to do with @nocors metablocks. In addition, I think it can be implemented by encapsulating GM_xmlHttpRequest through @require, but using @nocors will split the Greasemonkey script ecology.

**Comment by sjehuda** [comment]
> using @nocors will split the Greasemonkey script ecology.

My purpose is to raise a shared discussion with all of the
makers of userscript managers, and get this applied in a coordinate
manner.

I'm interested in compatibility.

P.s
Yes, the problem is with Falkon (either itself or its extension).

**Comment by CodFrm** [comment]
If other managers implement it, I will follow up immediately. I don't plan to implement it at this stage.
