### ISSUE TITLE
能否添加个按钮，直接打开网页跳转到网盘备份和CAT_fileStorage的对应目录？

### ISSUE THREAD

**Issue by ChitaGideon** [scriptscat/scriptcat#182]
能否添加个按钮，直接打开网页跳转到网盘备份或CAT_fileStorage的对应目录？

我已经搞不清我自己备份的是网盘的哪个账号了

**Comment by CodFrm** [comment]
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/22783163/236244231-a96fc9c1-1663-4c4c-a43b-0e0e8977b123.png">

这个页面嘛？新增一个按钮，`打开目录`

**Comment by ChitaGideon** [comment]
对，还有一个在设置里的，启用同步到onedrive ，搞不清两者有什么区别，或者有没有不同目录

**Comment by ChitaGideon** [comment]
那如何从同步里恢复呢？我现在都是从备份列表里选，然后恢复；从来没从同步里恢复过。

**Comment by CodFrm** [comment]
同步恢复，直接启用同步保存即可

<img width="453" alt="image" src="https://user-images.githubusercontent.com/22783163/236598055-ec2f3fb7-1aa6-4720-b36f-b34ac912d29d.png">

**Comment by CodFrm** [comment]
CAT_fileStorage的实现方案还在考虑中，预计到0.14、15的样子了

然后有些网盘其实不太好打开目录，他们的目录是以id来显示的，然后坚果云的话是webdav，打开目录实际是webdav的url，而且路径也是id的形式，如果有办法取的话倒还好，判断一下url就行，没有的话就没办法了。

暂时简单的实现了一个接口欢迎大佬们来补充。

**Comment by ChitaGideon** [comment]
> CAT_fileStorage的实现方案还在考虑中，预计到0.14、15的样子了
> 
> 然后有些网盘其实不太好打开目录，他们的目录是以id来显示的，然后坚果云的话是webdav，打开目录实际是webdav的url，而且路径也是id的形式，如果有办法取的话倒还好，判断一下url就行，没有的话就没办法了。
> 
> 暂时简单的实现了一个接口欢迎大佬们来补充。

能指定目录吗？ 不管是webdav,还是其他网盘

**Comment by CodFrm** [comment]
可以的，不过过两个版本，后面再实现吧

**Comment by CodFrm** [comment]
关于CAT_fileStorage这个的讨论转移到此issue：https://github.com/scriptscat/scriptcat/issues/138
