### ISSUE TITLE
希望能管理跨域

### ISSUE THREAD

**Issue by shiyunjie45** [scriptscat/scriptcat#184]
开启过跨域的网站,过一段时间后想取消允许跨域,找不到入口,希望可以有个地方可以配置管理跨域规则

**Comment by CodFrm** [comment]
<img width="589" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/b07baa40-fbc4-4ae4-8b59-50a3f54bf52b">

现在点击设置即可
