### ISSUE TITLE
求求求：OneDrive好像导入不了！

### ISSUE THREAD

**Issue by zhangzong666** [scriptscat/scriptcat#185]

**Comment by CodFrm** [comment]
备份文件么？OneDrive可以连接么？进入扩展的开发者工具，看看network

**Comment by zhangzong666** [comment]
> 备份文件么？OneDrive可以连接么？进入扩展的开发者工具，看看network

但是百度可以同步！

**Comment by CodFrm** [comment]
那可能是OneDrive不能访问了吧，最近OneDrive在国内确实不稳定

**Comment by zhangzong666** [comment]
> 那可能是OneDrive不能访问了吧，最近OneDrive在国内确实不稳定

知道了，麻烦您也检查一下！

**Comment by CodFrm** [comment]
你看看onedrive能否访问：https://onedrive.live.com/
