### ISSUE TITLE
备份的本地压缩文件导入到油猴没有数据

### ISSUE THREAD

**Issue by AzureBlue0219** [scriptscat/scriptcat#187]
油猴备份导入则没有问题，是不互通还是？

**Comment by CodFrm** [comment]
应该是互通的，可能是bug，我后续处理一下

**Comment by CodFrm** [comment]
我这里测试可以，有示例么？

**Comment by AzureBlue0219** [comment]
> 我这里测试可以，有示例么？

![2023-05-22_190935](https://github.com/scriptscat/scriptcat/assets/48849383/9b02ed71-725b-4e02-83f7-f3d5d6880324)
1，导出的压缩包
![2023-05-22_190855](https://github.com/scriptscat/scriptcat/assets/48849383/1a29f496-3d5b-42cb-a529-08b1c1a8be77)
![2023-05-22_190907](https://github.com/scriptscat/scriptcat/assets/48849383/042d7cb2-029b-4d26-916c-0db634828290)
2，3，导入到油猴之后。
![2023-05-22_191025](https://github.com/scriptscat/scriptcat/assets/48849383/560cb496-d80c-4585-8cd5-3df600b3d26f)
![2023-05-22_191035](https://github.com/scriptscat/scriptcat/assets/48849383/aebb636d-adf0-484f-865f-31fa1b43595b)
4，5脚本猫

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/actions/runs/5097810136

**Comment by CosilC** [comment]
> > 我这里测试可以，有示例么？
> 
> ![2023-05-22_190935](https://user-images.githubusercontent.com/48849383/239891458-9b02ed71-725b-4e02-83f7-f3d5d6880324.png) 1，导出的压缩包 ![2023-05-22_190855](https://user-images.githubusercontent.com/48849383/239891621-1a29f496-3d5b-42cb-a529-08b1c1a8be77.png) ![2023-05-22_190907](https://user-images.githubusercontent.com/48849383/239891722-042d7cb2-029b-4d26-916c-0db634828290.png) 2，3，导入到油猴之后。 ![2023-05-22_191025](https://user-images.githubusercontent.com/48849383/239891904-560cb496-d80c-4585-8cd5-3df600b3d26f.png) ![2023-05-22_191035](https://user-images.githubusercontent.com/48849383/239891920-aebb636d-adf0-484f-865f-31fa1b43595b.png) 4，5脚本猫

大佬,这能显示脚本运行情况的是什么脚本啊

**Comment by CodFrm** [comment]
@CosilC 你是说的这个脚本么？Bilibili Evolved
https://scriptcat.org/script-show-page/522
