### ISSUE TITLE
不能很好的兼容油猴

### ISSUE THREAD

**Issue by changzhongxinxin** [scriptscat/scriptcat#19]
自动无缝翻页这个脚本，有一个双击左边空白选项（默认打开好像），点击后（点击一下想要关闭）就会多一个你将要打开的选项（关闭的选项），然后在点击回去（打开的选项)脚本数就涨，再点击回去(关闭的选项）脚本数接着涨。目前就发现了这一个脚本有这毛病。
![snipaste_20211230_175503](https://user-images.githubusercontent.com/68383493/147742281-f80ada5e-eac1-4e55-bb89-57af263ec4ee.png)
![snipaste_20211230_175529](https://user-images.githubusercontent.com/68383493/147742284-743155b2-3597-4ff4-8a7b-a6f649d65593.png)
![snipaste_20211230_175628](https://user-images.githubusercontent.com/68383493/147742289-093c7b89-4a51-4779-9b04-2c16ed5505a3.png)

**Comment by CodFrm** [comment]
出现问题的网页是那个呢？方便贴上来吗？

**Comment by changzhongxinxin** [comment]
蓝奏云😄


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月31日(周五) 上午9:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [scriptscat/scriptcat] 不能很好的兼容油猴 (Issue #19)




 
出现问题的网页是那个呢？方便贴上来吗？
 
&mdash;

**Comment by CodFrm** [comment]
bd1612105d4fd13af48c5152e379270dbfc60932 修复

**Comment by changzhongxinxin** [comment]
老哥，密码忘了咋办，没有找回密码啊😱


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月3日(周一) 晚上9:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [scriptscat/scriptcat] 不能很好的兼容油猴 (Issue #19)




 
Closed #19.
 
&mdash;

**Comment by CodFrm** [comment]
@changzhongxinxin az尴尬了 事情太多了，就还没写找回密码，过两个星期开发一下，可以先给我发邮件告诉我账号，我手动处理一下：yz@ggnb.top

**Comment by CodFrm** [comment]
@changzhongxinxin 密码为了保密性，你可以加密发我，使用的`bcrypt` https://www.jisuan.mobi/p163u3BN66Hm6JWx.html

**Comment by changzhongxinxin** [comment]
打不开，算了，先不登录了，等老哥以后弄了找回密码在登吧，脚本也都同步了😀


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月7日(周五) 中午1:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [scriptscat/scriptcat] 不能很好的兼容油猴 (Issue #19)




 
@changzhongxinxin 密码为了保密性，你可以加密发我，使用的bcrypt https://www.jisuan.mobi/p163u3BN66Hm6JWx.html
 
&mdash;
