### ISSUE TITLE
[bug]js依赖不能使用，存在问题。

### ISSUE THREAD

**Issue by yang10560** [scriptscat/scriptcat#190]
我引入

```js

// @require    https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js

 async function digestMessage(r) {
        const hash = CryptoJS.SHA256(r);
        return hash.toString(CryptoJS.enc.Hex);
    }
```

不能够直接使用CryptoJS,提示不存在。但在tampermonkey管理器是可以使用的。看了你网站api文档并没有说什么，还是说要别的引入方法呢？

**Comment by CodFrm** [comment]
关于引入那里，有完整的示例么？

我现在先看看该脚本在百度上的运行情况

**Comment by CodFrm** [comment]
我这里没有报错，脚本猫会产生什么结果呢？也许是bug，因为网络波动导致js文件没有下载下来，可以在工具，脚本资源看一下是不是有加载成功：
<img width="1291" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/ed8e7da7-34d7-480d-a305-de8349231691">

<img width="502" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/22bfabc8-3910-44b7-895c-9b9cef7c6e35">

**Comment by CodFrm** [comment]
示例问题修复了，但是脚本依旧无法使用，我使用tampermonkey在百度中好像也有问题

**Comment by CodFrm** [comment]
百度中无法使用是我的广告屏蔽插件导致的，关闭都可以正常使用了
