### ISSUE TITLE
学习通的脚本猫运行不了，怎么解决

### ISSUE THREAD

**Issue by 1326836302qwe** [scriptscat/scriptcat#192]
// @match        *://*/thread*
// @match        *://*/forum.php?mod==viewthread*
// @match        *://*/forum.php?mod=viewthread*
// @match        *://*/forum/forum.php?mod=viewthread*
// @match        *://*/forum/thread*
// @match        *://*/bbs/forum.php?mod=viewthread*
// @match        *://*/forum.php?mod=post*

**Comment by 1326836302qwe** [comment]
点刷题一直在加载页面

**Comment by CodFrm** [comment]
前面的@match是什么意思？

**Comment by 1326836302qwe** [comment]
> 前面的@match是什么意思？
> 
> 页面有显示脚本？
> 
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/22783163/242213706-7f799179-1655-48f1-9a12-b46aa7e7b64f.png">

有显示脚本

**Comment by 1326836302qwe** [comment]
> 前面的@match是什么意思？
> 
> 页面有显示脚本？
> 
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/22783163/242213706-7f799179-1655-48f1-9a12-b46aa7e7b64f.png">



> 前面的@match是什么意思？
> 
> 页面有显示脚本？
> 
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/22783163/242213706-7f799179-1655-48f1-9a12-b46aa7e7b64f.png">

他显示是运行，但是打开网页是404，更新之后就成这样了

**Comment by CodFrm** [comment]
> 他显示是运行，但是打开网页是404，更新之后就成这样了

那大概是页面的问题，和脚本猫与脚本无关
