### ISSUE TITLE
【建议】脚本猫的脚本详情首页支持锚点链接

### ISSUE THREAD

**Issue by 1665169869** [scriptscat/scriptcat#193]
为了不影响观感，我把赞助二维码放到了最下面，希望脚本猫支持markdown语法的锚点链接跳转

![image](https://github.com/scriptscat/scriptcat/assets/50762038/7a2e7129-33f7-48b2-9088-df17f6b256f4)

![image](https://github.com/scriptscat/scriptcat/assets/50762038/18df5354-fdc0-4b5b-b590-fe842c3a3d4b)

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptlist-frontend/commit/0b56a3f778a16a25feb513f8cc8bab48480b6d52

已支持
