### ISSUE TITLE
定时脚本永远卡在“运行中”状态，无法执行

### ISSUE THREAD

**Issue by yuijker** [scriptscat/scriptcat#196]
操作系统：Win10 22H2
浏览器版本：edge 114.0.1823.37
脚本猫版本：0.13.0
问题描述：
当每天启动浏览器后，脚本猫的定时脚本将执行一次。然而，定时脚本全都显示“运行中”状态，没有执行完成的提示，甚至日志中也没有失败的记录。只有进入编辑界面-运行-调试后才能正常执行后台脚本。
截图：

![image](https://github.com/scriptscat/scriptcat/assets/72558803/48636725-ff90-494f-beca-36456d48ea91)

以6月2日的日志为例，定时脚本并没有留下执行完成的日志：
![image](https://github.com/scriptscat/scriptcat/assets/72558803/9583305d-7e72-4df9-aeb5-c191ee24bbd8)

手动调试时，定时脚本却成功运行：
![image](https://github.com/scriptscat/scriptcat/assets/72558803/32f2ae62-6ba6-43f5-ae48-9570d269a666)

![image](https://github.com/scriptscat/scriptcat/assets/72558803/28ef62f5-c949-4aa1-b322-65d677b7de94)

日志界面：
![image](https://github.com/scriptscat/scriptcat/assets/72558803/44b07675-fefd-4025-b16a-05a9e02d1a4a)

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptcat/issues/195 与此问题一致，更新到0.13.1解决，edge商店暂时还在审核中
