### ISSUE TITLE
GM_xmlhttpRequest 不兼容，无法发送自定义的请求头

### ISSUE THREAD

**Issue by ViCrack** [scriptscat/scriptcat#20]
在scriptcat中使用如下代码指定headers

```
GM_xmlhttpRequest({
        method: 'GET',
        url: 'http://xxxx',
       headers:    {
            referer:  "http://microsoft.com",
            origin:   "http://microsoft.com"
       }
```
发现它会把Origin和Referer请求头变成
```
X-Cat-20379D59-3753-4Bc2-9Aac-7Fd1601C4454-Origin: http://microsoft.com
X-Cat-20379D59-3753-4Bc2-9Aac-7Fd1601C4454-Referer: http://microsoft.com
```
而且还莫名多了一个X-Cat-xxx-Scriptcat的出来
`X-Cat-20379D59-3753-4Bc2-9Aac-7Fd1601C4454-Scriptcat: true`

导致最终请求失败。

而我换成用tampermonkey去验证了一下，发送的请求头则都是标准和正确的值，也没有多余的X-Cat-xxx-Scriptcat出现。

这是为什么，需要如何避免？

> Firefox最新版，后台脚本

**Comment by CodFrm** [comment]
![image](https://user-images.githubusercontent.com/22783163/147799512-6a412882-7404-42a4-8ca4-f6b389f37d94.png)

v0.7.7 么？我chrome测试正常，Firefox我在元旦的时候看一看，可能是浏览器兼容问题

**Comment by CodFrm** [comment]
```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @grant GM_xmlhttpRequest
// @match        https://bbs.tampermonkey.net.cn/
// ==/UserScript==

// 在此处键入代码……
GM_xmlhttpRequest({
        method: 'GET',
        url: 'https://bbs.tampermonkey.net.cn/',
       headers:    {
            referer:  "http://microsoft.com",
            origin:   "http://microsoft.com"
       }
});
```

**Comment by ViCrack** [comment]
是0.7.7，好像只有后台脚本才有这情况，还有在脚本编辑器 点`操作->调试`的时候 (换到了edge来测试)

![图片](https://user-images.githubusercontent.com/18179821/147799973-1082f431-c7b7-4be6-ba89-4b5848a6afe9.png)

[https://github.com/scriptscat/scriptcat/blob/c136f66bb20f4ab86e713b9fa5992ec641a9e6c7/src/apps/grant/background.ts#L74](https://github.com/scriptscat/scriptcat/blob/c136f66bb20f4ab86e713b9fa5992ec641a9e6c7/src/apps/grant/background.ts#L74)

**Comment by CodFrm** [comment]
发现了，是调试的时候会这样，不过运行是可以的，我元旦的时候修复一下

```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @grant GM_xmlhttpRequest
// @background
// ==/UserScript==

// 在此处键入代码……
GM_xmlhttpRequest({
        method: 'GET',
        url: 'https://bbs.tampermonkey.net.cn/',
       headers:    {
            referer:  "http://microsoft.com",
            origin:   "http://microsoft.com"
       }
});
```

**Comment by CodFrm** [comment]
修复 328ca1864a87dafa0b4e022cdd0dd7a52883a5ba

**Comment by ViCrack** [comment]
@CodFrm 

在0.8.0版本 Firefox
![图片](https://user-images.githubusercontent.com/18179821/148893829-628621f5-5897-4745-bfa4-2133b5f00975.png)

后台脚本还是会发送错误和多余的请求头
![图片](https://user-images.githubusercontent.com/18179821/148893719-3f048334-aef0-4989-a58f-931bc0daa5c3.png)

**Comment by CodFrm** [comment]
@ViCrack chrome系没问题，Firefox我再看看 尴尬了

**Comment by CodFrm** [comment]
修复，这两天就更新，Firefox审核很快
