### ISSUE TITLE
脚本不生效

### ISSUE THREAD

**Issue by LIHAQI** [scriptscat/scriptcat#205]
https://greasyfork.org/zh-CN/scripts/430116-notion-zh-cn-notion%E7%9A%84%E6%B1%89%E5%8C%96%E8%84%9A%E6%9C%AC
平时使用的一个notion汉化脚本在油猴可以使用，但是在scriptcat中不生效

**Comment by CodFrm** [comment]
<img width="1436" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/fa8a806a-d6e2-41eb-88c3-ff3faccda5cd">

感谢反馈，最终效果是这样的么？哥哥尝试升级到beta版本试试，我用beta好像可以的

https://github.com/scriptscat/scriptcat/actions/runs/5319188625

**Comment by CodFrm** [comment]
怎么感觉好像是脚本的问题，我使用tampermonkey，也会出现无法翻译的问题，重启扩展后恢复

然后使用脚本猫 v0.13.1 版本，有时候也可以正常翻译

<img width="1432" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/dc8e7e34-6027-4d51-95d7-9a0a5b2f9c47">

**Comment by LIHAQI** [comment]
> 怎么感觉好像是脚本的问题，我使用tampermonkey，也会出现无法翻译的问题，重启扩展后恢复
> 
> 然后使用脚本猫 v0.13.1 版本，有时候也可以正常翻译
> 
> <img alt="image" width="1432" src="https://user-images.githubusercontent.com/22783163/247024768-dc8e7e34-6027-4d51-95d7-9a0a5b2f9c47.png">

这个就不清楚了，我用tampermonkey一直可以的，脚本猫v0.13.1不行，我试试beta版本吧，谢谢大佬了。

**Comment by CodFrm** [comment]
重启扩展呢？开发者模式，重新加载

<img width="945" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/91e41110-f6da-4d0a-8432-06d639125dc3">

**Comment by CodFrm** [comment]
这是我tampermonkey失效的情况，重启恢复：

<img width="1428" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/79ebd581-f1af-4044-b9f8-82d720fbf2cb">
