### ISSUE TITLE
[功能建议] 基于域名的脚本搜索

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [scriptscat/scriptcat#208]
来自 [ViolentMonkey](https://github.com/violentmonkey/violentmonkey)
在 [哔哩哔哩](https://bilibili.com) 网站点击 `GF` 后可以跳转到类似于 https://greasyfork.org/zh-CN/scripts/by-site/bilibili.com
点击 `OUJS` 是跳转到 https://openuserjs.org/?q=bilibili.com
其中 `bilibili.com` 域名可通过 `location.host` 获取

![图片](https://github.com/scriptscat/scriptcat/assets/52521836/767883d4-90c0-4dfa-863f-5d6731aba0cc)

**Comment by CodFrm** [comment]
<img width="320" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/295f10ae-8ece-41a4-9ac3-21ea55323a60">

右上角菜单点击获取脚本也可以搜索

**Comment by CodFrm** [comment]
哈哈哈 `只能在脚本猫社区` 是有些私心的
