### ISSUE TITLE
插件显示不出来了

### ISSUE THREAD

**Issue by baiwei666** [scriptscat/scriptcat#209]
有时脚本会显示不出来，也无法运行，想重新下载脚本，又只能更新，说明脚本是存在的，但不显示

**Comment by baiwei666** [comment]
![image](https://github.com/scriptscat/scriptcat/assets/18593778/2c6126da-c550-41dc-8510-7823e02c54ee)

**Comment by baiwei666** [comment]
百度网盘同步也失败，请问大佬要如何解决

**Comment by CodFrm** [comment]
好像是读取的值过大了导致的失败，看看能不能操作indexedb，看看有没有什么报错之类，可以参考

https://github.com/scriptscat/scriptcat/issues/172#issuecomment-1537651920

这个问题应该是这个导致的 https://github.com/scriptscat/scriptcat/commit/4832a80b5a3c553563367892adcdf85e9832fc98

**Comment by baiwei666** [comment]
![image](https://github.com/scriptscat/scriptcat/assets/18593778/b53b8fd4-1c2c-448a-bdaa-0130e72f65b1)
大佬，我这个也没有显示

**Comment by baiwei666** [comment]
![image](https://github.com/scriptscat/scriptcat/assets/18593778/5d2a7648-4b24-418c-ac4e-f8aa13dee7da)
但scripts下的namespace又有

**Comment by baiwei666** [comment]
> 大佬，我这个也没有显示，但scripts下的namespace又有

**Comment by CodFrm** [comment]
namespace下有几条数据？

看看updatetime呢

**Comment by baiwei666** [comment]
> namespace下有几条数据？
> 
> 看看updatetime呢

namespace下有8条数据，跟我原来的脚本数目一致，没有显示null的条目

updatetime下没有条目

**Comment by CodFrm** [comment]
@baiwei666 有更新比较频繁的脚本么？

**Comment by baiwei666** [comment]
> @baiwei666 有更新比较频繁的脚本么？把那个更新频繁的脚本删除再试试

没有啊
