### ISSUE TITLE
如果导入？

### ISSUE THREAD

**Issue by ChitaGideon** [scriptscat/scriptcat#21]
我tampermonkey，一堆脚本，想迁移过来。
tampermonkey 能很方面的导出到压缩包，但我还不清楚怎么导入压缩包。
是不是还没这功能

**Comment by CodFrm** [comment]
压缩包的话，元旦开发好，暂时只支持json

**Comment by CodFrm** [comment]
拖到了今天：48d197c826504018e093e745377c2eb8bba5bf40
