### ISSUE TITLE
百度网盘登录掉了以后无法重新登陆，不弹出登录窗口，除非重新安装脚本猫插件！我是用的360浏览器最新版（浏览器版本14.1.1116.0，内核版本108.0.5359.125）

### ISSUE THREAD

**Issue by hktkqwe123** [scriptscat/scriptcat#210]
百度网盘登录掉了以后无法重新登陆，不弹出登录窗口，除非重新安装脚本猫插件！我是用的360浏览器最新版（浏览器版本14.1.1116.0，内核版本108.0.5359.125）！！！！！！

**Comment by CodFrm** [comment]
在备份这边，点击备份或者查看目录呢？会有报错吗？

<img width="1276" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/8733be5a-1d3c-4991-a4be-a1ee58db1967">

**Comment by CodFrm** [comment]
我复现出来了，备份那边会提示错误，但是同步没有任何反应，临时解决方案：

控制台中输入：

```js
delete localStorage["netdisk:token:baidu"]
```

**Comment by CodFrm** [comment]
当然会解决

**Comment by CodFrm** [comment]
fix: https://github.com/scriptscat/scriptcat/actions/runs/5397017545

**Comment by jiongjiongJOJO** [comment]
> 我复现出来了，备份那边会提示错误，但是同步没有任何反应，临时解决方案：
> 
> 控制台中输入：
> 
> ```js
> delete localStorage["netdisk:token:baidu"]
> ```
> 
> 不知道你的环境还有没有保存，可以发截图看一下错误信息

@CodFrm 建议增加一个重新授权的按钮
