### ISSUE TITLE
New metablock @filetype

### ISSUE THREAD

**Issue by sjehuda** [scriptscat/scriptcat#211]
I think it would be most appropriate to incorporate the capability of the program [Open in Browser](https://github.com/Rob--W/open-in-browser) into metablocks as follows:

```
// @filetype text/xml text/html
// @filetype application/xml text/html
// @filetype application/rss+xml text/html
// @filetype application/atom+xml text/html
```

`@filetype`: `@mimetype` would be good too
`text/html`: `text/plain` would be good too

## About
This is a request to add new API ~~to GM.xmlHttpRequest, or to the core of the Greasemonkey extension,~~ that can influence a change in `document.contentType`.

## Preface
I have wrote a userscript that converts structured data files (i.e. XML and JSON) into human readable HTML files.

Overhaul, the program works as expected; documents are processed and forged successfully into HTML.

All the extra functionalities work well when `document.contentType` (read only) _does not_ contain `xml`.

However, when `document.contentType` has `xml`, any code that contains `querySelector` would fail because the `document` is believed to be whatever `document.contentType` has determined upon initial request (an XML file), and, apparently, the web browser doesn't check `document` once it has been loaded.

An error message from the program suggests the file processed is XML when in reality it is an HTML, hence hinders other functions to be executed:

## Expected Behavior
Execute actions on document as as HTML.

## Actual Behavior
Browser blocks HTML actions (throws errors) because it is believed to be an XML.

## Script
https://greasyfork.org/en/scripts/465932-newspaper-native-rss-reader

## Test Page
https://lzone.de/liferea/blog/feed.xml `application/xml`

## Note
More information at https://github.com/greasemonkey/greasemonkey/issues/3164

**Comment by CodFrm** [comment]
This is an interesting script, I looked at Tampermonkey and Violentmonkey, it seems to be working, but Scriptcat is not working, let me first solve this problem 😂.

In addition, can we solve this problem from other aspects? For example, Web Component, the style of this attribute will inherit from custom-card, but this seems troublesome

<img width="1411" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/06befe80-973e-4412-9f5a-93ee8647af21">

**Comment by sjehuda** [comment]
Video preview of the script in action in a page that `document.contentType` doesn't contain `xml`.

https://github.com/violentmonkey/violentmonkey/assets/19249089/e8c2770a-5ebd-4c7b-b42f-0bb3639565e5

**Comment by CodFrm** [comment]
This is the document of Web Component: https://developer.mozilla.org/en-US/docs/Web/API/Web_components, my idea is to use its shadow DOM feature to change the outer `custom-card` style Inheritance, but I'm not sure if I can solve this problem, and it's very troublesome.

What's weird is that some elements have `element.style` and some don't.

In short, see if there is any other solution to this problem. If not, I will consider trying to add the metablock @filetype you mentioned (but maybe in this form: https://github.com/scriptscat/scriptcat/issues/54)

**Comment by sjehuda** [comment]
I have managed to overcome this setback, namely by passing the HTML element `newDocument` and processing it in all ways feasible (see `preProcess`) and then replacing `document` by `newDocument`. See [v24.04.06 vs. v24.04.08](https://greasyfork.org/scripts/465932-newspaper/diff?v1=1356285&v2=1355403).

There was also another matter which required to create an element and change CSS Stylesheet in order to get the expected behaviour, because JavaScript attribute `style` does not work with `document.contentType` that ends with **XML**. See [v24.04.08 vs. v24.04.09](https://greasyfork.org/scripts/465932-newspaper/diff?v1=1356499&v2=1356285).

The only functionality which remains not to work upon XML is mode switcher (bright and dark) due to attribute `style`, yet it _might_ be possible to fix.
