### ISSUE TITLE
沉浸式翻译无法使用（immersivetranslate）

### ISSUE THREAD

**Issue by Mikachu2333** [scriptscat/scriptcat#214]
如题，官方网站如下
https://immersivetranslate.com

调试后发现问题提示如下，其在篡改猴（edge、firefox）中均正常运行：
![图片](https://github.com/scriptscat/scriptcat/assets/63829496/df866e22-1c2e-44f3-b3e5-955095216605)

**Comment by CodFrm** [comment]
发现两个兼容性问题，已处理
