### ISSUE TITLE
match匹配网站无法正确执行脚本

### ISSUE THREAD

**Issue by lihengdao666** [scriptscat/scriptcat#217]
请联系我私下沟通
-------------------------
尊嘟假嘟 o_O

**Comment by CodFrm** [comment]
<img width="387" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/47e973bd-c5e4-48b5-a7bf-d09d2b43f43c">

op点击了排除运行导致的，再点击一下回复就好了
