### ISSUE TITLE
部分脚本不能保存设置

### ISSUE THREAD

**Issue by JiaoYeTan** [scriptscat/scriptcat#22]
![BPB({1TW4T%A LV5XJ~KV0](https://user-images.githubusercontent.com/36872913/147809336-f6e09a61-27e5-48e7-8016-934ab51c2555.png)
默认
![$HQYA44Z1~OL_P`QG6H6KMG](https://user-images.githubusercontent.com/36872913/147809354-0a8bd9b8-7bda-4bb7-a560-39cc1734a28e.png)
改成123点确定后还是
![FOAM6C5WJ@L~}@T%@WM6VOI](https://user-images.githubusercontent.com/36872913/147809359-9e51145c-3bc2-4291-8a7f-ac44b2baf96b.png)
油猴上就没这问题

脚本链接: https://gist.github.com/Nerver4Ever/953447c9ecd330ffc0861d4cbb839369

**Comment by CodFrm** [comment]
修复 https://github.com/scriptscat/scriptcat/commit/9eb92cca14df9d48a7b5800c49bc903a8b480de5
