### ISSUE TITLE
关于排序崩溃的bug，难以描述，详见gif

### ISSUE THREAD

**Issue by Mikachu2333** [scriptscat/scriptcat#223]
![screenshots](https://github.com/scriptscat/scriptcat/assets/63829496/5bf564b4-2ea4-491d-bf89-179502e4b8d7)

多点击几次上面的各类排序标签就有极大概率出现，刷新后临时正常，然后点点又不正常了……

**Comment by CodFrm** [comment]
页面崩溃白屏了？

**Comment by Mikachu2333** [comment]
另外一个奇怪问题就是扩展猫在mozilla的站点上无法工作
![图片](https://github.com/scriptscat/scriptcat/assets/63829496/d0c43820-854e-4263-bd2f-964c60c91c48)
![图片](https://github.com/scriptscat/scriptcat/assets/63829496/2b7bfbed-d825-4b72-8682-589f29a77473)
![图片](https://github.com/scriptscat/scriptcat/assets/63829496/698dc22a-6a01-453e-9a47-71f29a8cf9d7)

**Comment by CodFrm** [comment]
在mozilla的站点上无法工作 这个问题，貌似是浏览器的限制，禁止了在这个页面上运行扩展

就像chrome浏览器的扩展也无法在chrome商店上运行一样：https://chrome.google.com/webstore/detail/scriptcat/ndcooeababalnlpkfedmmbbbgkljhpjf?hl=zh-CN&authuser=0

**Comment by Mikachu2333** [comment]
> 在mozilla的站点上无法工作 这个问题，貌似是浏览器的限制，禁止了在这个页面上运行扩展
经确认确实是这样的

**Comment by CodFrm** [comment]
无法复现

**Comment by Mikachu2333** [comment]
无法复现+1，似乎已被修复，具体原因仍不明晰
