### ISSUE TITLE
CAT_fileStorage  重置 onedrive

### ISSUE THREAD

**Issue by ChitaGideon** [scriptscat/scriptcat#224]
点重置感觉没啥用；
再点保存显示成功。  
但根本没有提示新的auth；不懂成功了啥。
调用api  提示  红色 储存错误

**Comment by CodFrm** [comment]
重置就是改为未设置，调用这个API存储时将会提示储存未设置的错误

红色就授权失败了，储存无法连接，和未设置一个效果

**Comment by ChitaGideon** [comment]
> 如果有网盘的授权信息，点击保存不会再去申请授权，会复用现有的授权
> 
> 重置就是改为未设置，调用这个API存储时将会提示储存未设置的错误
> 
> 红色就授权失败了，储存无法连接，和未设置一个效果

如果我需要换个onedrive授权怎么办呢？

我这边显示授权成功`使用中`了，但调用api却显示红色失败，该怎么处理呢

**Comment by CodFrm** [comment]
@ChitaGideon 这样的话，是有点问题，无法切换，后续版本优化一下这个问题

现在的话，可以去localStorage删除一下数据

**Comment by ChitaGideon** [comment]
现在是显示
<img width="694" alt="image" src="https://github.com/scriptscat/scriptcat/assets/1167456/173bbf97-390a-4123-a682-9ac3162c7d4e">
就是调用api， 这个地方会报错；
今天试了试 好像没变红了；但api也没调用成功，onload一直没执行；
```
     CAT_fileStorage("list", {
            baseDir: "test-dir",
            onload(list) {
                console.log('CAT_fileStorage!!!',list);
}});
CAT_fileStorage("upload", {
    path: "test.txt",
    data: new Blob(["Hello World"]),
    onload() {
        console.log('success test')
    }})
```

**Comment by ChitaGideon** [comment]
又是这个错误
<img width="431" alt="image" src="https://github.com/scriptscat/scriptcat/assets/1167456/5e803e4b-ea36-4b67-8a2f-eab128ff60cc">

**Comment by CodFrm** [comment]
目前的错误处理有点问题，只要出现了错误就会把这里变为错误状态，不太合理，应该只有token之类的授权错误才这样。下个版本处理一下

**Comment by CodFrm** [comment]
试试这个包：https://github.com/scriptscat/scriptcat/actions/runs/5972635761/job/16203489052

修复了上面的问题，会返回code=8表示网络之类的错误

**Comment by ChitaGideon** [comment]
> 试试这个包：https://github.com/scriptscat/scriptcat/actions/runs/5972635761/job/16203489052
> 
> 修复了上面的问题，会返回code=8表示网络之类的错误

账号信息验证失败: Error: {"error":{"code":"invalidRequest","message":"Invalid request","innerError":{"date":"2023-09-01T01:56:27","request-id":"ff1979fb-7c66-4042-a331-584e06a7e087","client-request-id":"ff1979fb-7c66-4042-a331-584e06a7e087"}}}

我用的是onedrive  e5账号，是不是因为这个？

**Comment by CodFrm** [comment]
@ChitaGideon 不太清楚，试试普通的账号呢？

**Comment by CodFrm** [comment]
@ChitaGideon 另外可以在background.html看到具体的请求内容，可以截图看一下

<img width="1305" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/f80b283a-fc55-405d-8373-c43435c08701">

**Comment by ChitaGideon** [comment]
用普通个人账号好像是没问题的；
用e5账号，或者可能一些onedrive business的账号，请求会出错。
<img width="629" alt="image" src="https://github.com/scriptscat/scriptcat/assets/1167456/fce16b8f-6655-4b70-943c-e061e329cdc5">

**Comment by CodFrm** [comment]
那这可能得再研究研究了，我没有e5账号

**Comment by ChitaGideon** [comment]
> 那这可能得再研究研究了，我没有e5账号

我可以给你一个子账号，拿去玩，给我个邮箱什么的，我发给你

**Comment by CodFrm** [comment]
@ChitaGideon 可以试试，邮箱 yz@ggnb.top

**Comment by ChitaGideon** [comment]
> @ChitaGideon 可以试试，邮箱 [yz@ggnb.top](mailto:yz@ggnb.top)

邮件应该发出了，没收到的话，告诉我

**Comment by CodFrm** [comment]
@ChitaGideon 没有收到

**Comment by ChitaGideon** [comment]
> @ChitaGideon 没有收到

我单独又发了一次，再看看

**Comment by CodFrm** [comment]
@ChitaGideon 收到了，谢谢哥哥，我周末看看

**Comment by ChitaGideon** [comment]
@CodFrm   这个部分有进展没，还是有什么太麻烦的问题？

**Comment by CodFrm** [comment]
忘记了，不好意思，我明天看看，尴尬，最近在完善脚本猫其它的东西

**Comment by CodFrm** [comment]
@ChitaGideon [approot 应用文件夹](https://learn.microsoft.com/zh-cn/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online)，脚本猫的数据是存在这个目录下的，不知道是无权限还是什么问题，这个请求得到的是400

我找到了其他软件的相关内容，可能需要哥哥参考设置一下权限，另外尝试一下请求能否成功：https://github.com/remotely-save/remotely-save/issues/11

```bash
curl --location 'https://graph.microsoft.com/v1.0/me/drive/special/approot::/children' \
--header 'authorization: Bearer onedrive的token，localStorage中有存储'
```

**Comment by ChitaGideon** [comment]
@CodFrm  权限么，之前只有两个；
现在已经授权这些了： 看对不对
<img width="1076" alt="QQ20231128-112834@2x" src="https://github.com/scriptscat/scriptcat/assets/1167456/64004a87-341d-4048-af7d-0c6bb2a348e8">

我试了 第二个
```
curl --location 'https://graph.microsoft.com/v1.0/drive/special/approot/children' \
--header 'authorization: Bearer onedrive的token，localStorage中有存储'
```
没有报错了
```
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users('70124245-51bc-46f1-b8a9-d93c827f34c9')/drive/special('approot')/children","value":[]}%
```

**Comment by CodFrm** [comment]
创建文件上传会话400了，[通过上传会话上传大文件](https://learn.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online)，不知道是否是需要`应用程序 | Sites.ReadWrite.All`这个权限

```
curl --location 'https://graph.microsoft.com/v1.0/drive/special/approot:/scriptcat-backup.zip:/createUploadSession' \
--header 'authorization: Bearer xxxx' \
--data-raw '{"item":{"@microsoft.graph.conflictBehavior":"replace","description":"description","fileSystemInfo":{"@odata.type":"microsoft.graph.fileSystemInfo"},"name":"scriptcat-backup-2023-11-28T11-49-53.zip"}}'
```

**Comment by CodFrm** [comment]
@ChitaGideon 我这边成功上传了，但是没有看见文件，不知道管理员可以看见么？`scriptcat-backup-2023-11-28T13-56-44.zip`

**Comment by ChitaGideon** [comment]
@CodFrm   管理员看不到，看看返回啥信息？

**Comment by CodFrm** [comment]
@ChitaGideon 成功上传了，也能下载和读取到，但是我到网页上看不见文件，哥哥可以试试这个版本：https://github.com/scriptscat/scriptcat/actions/runs/7014891823

**Comment by CodFrm** [comment]
@ChitaGideon 好像是如此了，没有找到其它相关资料说明

**Comment by CodFrm** [comment]
我去提问了，看看能不能得到答复

https://answers.microsoft.com/zh-hans/msteams/forum/all/%e6%88%91%e4%bd%bf%e7%94%a8oauth2%e9%80%9a/7c37e9b9-a314-4dda-9b95-915931de1d74

**Comment by CodFrm** [comment]
是我调用API的问题，切换成 `https://graph.microsoft.com/v1.0/me/drive/special/approot` 可以了

哥哥可以再试试这个版本：https://github.com/scriptscat/scriptcat/actions/runs/7016763000
