### ISSUE TITLE
油猴脚本“斗鱼直播增强”不能运行

### ISSUE THREAD

**Issue by Nothingtodoforma** [scriptscat/scriptcat#225]
https://greasyfork.org/zh-CN/scripts/394497-douyuex-斗鱼直播间增强插件

**Comment by CodFrm** [comment]
试试最新的v0.15.0版本呢？

**Comment by Nothingtodoforma** [comment]
能更新edge插件商店嘛，github我一下载，系统就会删除...

**Comment by CodFrm** [comment]
需要等2周左右的审核，可以用解压zip的方式来安装

https://docs.scriptcat.org/docs/use/#%E5%8A%A0%E8%BD%BD%E8%A7%A3%E5%8E%8B%E7%BC%A9%E6%96%B9%E5%BC%8F%E5%AE%89%E8%A3%85%E6%89%A9%E5%B1%95

**Comment by Nothingtodoforma** [comment]
我试了，不能用，好像系统删除了什么东西（win10，未使用各种管家），不能用。我又去谷歌插件商店安装的，但是安装后，edge就会出现不同版本号的两个插件，而且我还要重新导入脚本
![image](https://github.com/scriptscat/scriptcat/assets/49300630/fe74e3a8-a824-48ff-aa96-f6645100dbac)
![image](https://github.com/scriptscat/scriptcat/assets/49300630/706a2092-c535-4c45-bfdf-c8bfa78e0c42)

**Comment by Nothingtodoforma** [comment]
我发现原因了，不知道为什么没启用，我记得我昨天安装的时候是开启的
![image](https://github.com/scriptscat/scriptcat/assets/49300630/ef99abf0-5ffa-48a6-a345-171d0966f524)

**Comment by CodFrm** [comment]
是不是不小心关掉了 😄
