### ISSUE TITLE
频繁提示 脚本正在试图访问跨域资源

### ISSUE THREAD

**Issue by YujiaCheng1996** [scriptscat/scriptcat#228]
使用[东方永页机](https://greasyfork.org/scripts/438684-pagetual/code/Pagetual.user.js)等自动翻页类脚本时，每访问一个新网站都会弹出提示，脚本中已有`// @connect      *`，能不能增加 允许全部域名 选项？

**Comment by CodFrm** [comment]
在v0.15.1中添加了这个，可以手动添加一个*表示允许全部

<img width="1055" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/adabdeb7-1138-4e09-ab57-5192982236ac">

**Comment by YujiaCheng1996** [comment]
等上架
