### ISSUE TITLE
希望在这个界面做出性能优化

### ISSUE THREAD

**Issue by you-hengh** [scriptscat/scriptcat#231]
<img width="1621" alt="image" src="https://github.com/scriptscat/scriptcat/assets/34816426/117c3dac-69bf-48aa-8f5c-9705df7ef3f9">

地址:chrome-extension://ndcooeababalnlpkfedmmbbbgkljhpjf/src/install.html?uuid=230e202c-613a-48fc-ac87-bf7f3f8c91a8

希望能在这个页面做出性能优化, **加载的页面太长, 滑动页面造成卡顿**

如果打不开上述地址, 可以在安装脚本猫插件的环境下访问这里:
https://greasyfork.org/zh-CN/scripts/445241-mr%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B-%E8%87%AA%E5%8A%A8%E5%AE%BD%E5%B1%8F%E6%A8%A1%E5%BC%8F-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80-%E6%99%BA%E8%83%BD%E8%BF%9E%E6%92%AD-%E6%89%93%E9%80%A0%E5%B1%9E%E4%BA%8E%E8%87%AA%E5%B7%B1%E7%9A%84b%E7%AB%99

安装插件后会弹出上述地址

期望结果:

滑动页面不会卡顿

**Comment by CodFrm** [comment]
很流畅呀

https://github.com/scriptscat/scriptcat/assets/22783163/bf9940dd-6521-4b93-a226-8e207a753931

**Comment by CodFrm** [comment]
是电脑配置问题吗？你的配置如何？

**Comment by you-hengh** [comment]
> 是电脑配置问题吗？你的配置如何？

还好吧 卡顿不明显, 但还是希望能实现功能

**Comment by CodFrm** [comment]
这个页面结构很简单了，比较占性能的就编辑框了，但是编辑框没能力去优化性能，实现什么功能呢？

**Comment by you-hengh** [comment]
> 这个页面结构很简单了，比较占性能的就编辑框了，但是编辑框没能力去优化性能，实现什么功能呢？

具体就是在代码过长的编辑器里滑动的时候 会有些卡顿, 现象是这样  如何优化 我也不好说 不知道能否参考虚拟列表的原理, 把内容分为可见和不可见的部分  我只是说个思路  抛砖引玉  大佬们可以再想想 真不好弄就算了

**Comment by CodFrm** [comment]
哥哥是在什么环境下打开的这个页面呢？（浏览器版本、操作系统、cpu配置等）

主要没有那个能力去优化这个编辑器，另外我觉得大概率不是配置和页面的问题。最近我用edge浏览器，也经常的卡

**Comment by you-hengh** [comment]
> 哥哥是在什么环境下打开的这个页面呢？（浏览器版本、操作系统、cpu配置等）
> 
> 主要没有那个能力去优化这个编辑器，另外我觉得大概率不是配置和页面的问题。最近我用edge浏览器，也经常的卡

浏览器:Chrome 117.0.5938.62
操作系统: macOS 13.5.2
CPU: M1 max
内存: 32GB
脚本猫: 0.15.1

这并不是一个急迫的问题, 如果开发团队有时间愿意研究一下, 当然是最好的了

**Comment by CodFrm** [comment]
这个配置比我还高不少，大概率是其他问题了😣

**Comment by CodFrm** [comment]
哥哥可以录个视频来看看，是怎么样的卡的么？

**Comment by you-hengh** [comment]
> 哥哥可以录个视频来看看，是怎么样的卡的么？

主要表现就是上下滑动的时候(可能速度较快的时候)会不流畅, 我对修复这个卡顿不是很抱希望, 暂时就这样吧
