### ISSUE TITLE
在中国大学慕课网页上脚本不会正常运行

### ISSUE THREAD

**Issue by xiaoxizi98** [scriptscat/scriptcat#232]
用一个匹配所有网页的弹窗脚本进行测试，在其他网页都会弹窗但在中国大学慕课不会弹窗，且脚本猫显示脚本已经生效。是不是有网页白名单，在白名单网页上不运行脚本。

**Comment by CodFrm** [comment]
发一下脚本与链接

也可能与对应的网站有关系

**Comment by xiaoxizi98** [comment]
脚本地址：https://scriptcat.org/script-show-page/616
网页地址：https://www.icourse163.org/learn/USTC-1463123169?tid=1470908445#/learn/announce（任意课程页面都可以，需要登录才可以访问。）

**Comment by CodFrm** [comment]
其它会弹窗的网页的链接有么？

**Comment by xiaoxizi98** [comment]
上面的脚本不是弹窗的脚本，是从该脚本发现在慕课页面不能执行。弹窗脚本是我自己写来测试用的，您可以试一下。
***************************
// ==UserScript==
// @name         测试
// @version      1.0.0
// @match        *://*
// ==/UserScript==

alert(123)
***************************

**Comment by CodFrm** [comment]
也可以的

<img width="1425" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/33f4dc53-d725-4cea-9b58-46f1059b8d06">

**Comment by CodFrm** [comment]
直接在页面上刷新 看看可不可以？

**Comment by xiaoxizi98** [comment]
我刚也试了一下 不登录状态下是可以弹窗，登录之后进入课程界面就不会弹窗。

**Comment by xiaoxizi98** [comment]
应该是匹配 https://www.icourse163.org/learn/* 才不执行，不登录的话网页跳转到 https://www.icourse163.org/course/USTC-1463123169?tid=1470908445 所以可以弹窗了。

**Comment by CodFrm** [comment]
https://www.icourse163.org/learn/USTC-1463123169?tid=1470908445#/learn/announce

像这样？好像是的，我排查一下

**Comment by CodFrm** [comment]
是脚本运行框架注入速度导致的这个问题，哥哥试试这个版本可不可以 https://github.com/scriptscat/scriptcat/actions/runs/6211417667/job/16860580690

**Comment by xiaoxizi98** [comment]
这个版本可以了👍
