### ISSUE TITLE
苹果商店的的脚本猫是真的假的

### ISSUE THREAD

**Issue by Wei-Winter** [scriptscat/scriptcat#234]
我看ios商店有个脚本猫是大哥上架的吗，我安装了之后脚本都不生效

**Comment by CodFrm** [comment]
是的，兼容性问题很多，准备下架了，暂时还没精力去处理这些iOS兼容问题

**Comment by CodFrm** [comment]
好像也不知道能不能下架之后再上架，就先放那里了，不会玩这😭

**Comment by CodFrm** [comment]
只是能运行，但是如果需要GM权限，因为iOS对background的限制，一些API没有提供等等问题，很多GM函数都无法运行，没学过iOS开发，目前如何去解决也还不清楚
