### ISSUE TITLE
脚本删掉后还在

### ISSUE THREAD

**Issue by eqjs** [scriptscat/scriptcat#235]
脚本删掉后还在，脚本猫删掉重新下载已安装脚本显示没有脚本

![1](https://github.com/scriptscat/scriptcat/assets/124772251/e41e79bb-0e4d-4dd6-8621-4afc7f5cfded)

**Comment by eqjs** [comment]
![image](https://github.com/scriptscat/scriptcat/assets/124772251/3edee5d7-8797-4d3d-b8a8-dec990aa47cf)

**Comment by CodFrm** [comment]
确定不是存在其它脚本管理器么

**Comment by HKL2580** [comment]
主页怎么打不开了

**Comment by CodFrm** [comment]
@HKL2580 dns出现了些问题，还在处理，晚些再看看

**Comment by CodFrm** [comment]
传闻有过edge扩展删除的bug

新版EDGE卸载插件无效问题解决方式
https://bbs.tampermonkey.net.cn/thread-2186-1-1.html
(出处: 油猴中文网)
