### ISSUE TITLE
请问这个是订阅错误吗？

### ISSUE THREAD

**Issue by hsqoo** [scriptscat/scriptcat#24]
![image](https://user-images.githubusercontent.com/25947497/148227177-a4c399db-eaf2-42fe-acbc-105f74063706.png)

**Comment by CodFrm** [comment]
检查更新错误，可以看看这个安装链接还有没有效

**Comment by hsqoo** [comment]
我配置是这样的，链接可以访问

// @connect      hsqoo.github.io
// @scriptUrl    https:/hsqoo.github.io/1.user.js

**Comment by CodFrm** [comment]
可以贴上全部的内容和链接看看吗？

**Comment by hsqoo** [comment]
![image](https://user-images.githubusercontent.com/25947497/148230528-8518ebbe-8f8f-490c-8b56-960be056ca51.png)
我希望是一天或者6小时自动同步代码

**Comment by hsqoo** [comment]
UserSubscribe  这个没有写上去是吗

**Comment by CodFrm** [comment]
https://docs.scriptcat.org/dev/subscribe.html

开头和结尾使用`UserSubscribe`，默认是一天同步一次，关于订阅脚本的同步时间，我想后续应该可以提供一个描述来设置

**Comment by hsqoo** [comment]
谢谢大佬

**Comment by hsqoo** [comment]
我想实现的功能是 自动订阅 一个后台脚本

**Comment by CodFrm** [comment]
订阅是为多脚本服务的，如果是单个脚本，直接写好一个后台脚本就行，更新的话，会自动检查更新的，默认设置为1天。

如果你有多个脚本，就可以用订阅功能，现在也是默认一天检查更新一次

**Comment by CodFrm** [comment]
检查更新还需要一个 .meta.js 后缀的文件，或者指定更新链接为脚本链接本身：https://docs.scriptcat.org/dev/meta.html#updateurl

另外也可以去脚本市场发布，会自动配置一个更新的：https://scriptcat.org/search
