### ISSUE TITLE
Firefox无法打开设置页面

### ISSUE THREAD

**Issue by crxruixuan** [scriptscat/scriptcat#242]
问题：Firefox无法打开设置页面
问题呈现：

https://github.com/scriptscat/scriptcat/assets/85326108/0b29fe0f-291f-406a-8f6f-0bdb6fbeb319

错误报告：
[console-export-2023-11-18_10-48-3.txt](https://github.com/scriptscat/scriptcat/files/13398759/console-export-2023-11-18_10-48-3.txt)

**Comment by CodFrm** [comment]
什么版本的firefox与扩展呢？

![image](https://github.com/scriptscat/scriptcat/assets/22783163/5a1654e9-646b-444b-867f-e65948f31d8e)

我这边可以
![image](https://github.com/scriptscat/scriptcat/assets/22783163/eac53d8c-f95c-4cd6-87e9-766e4eb97127)

**Comment by raycho2005** [comment]
扩展:0.15.1
浏览器：
![图片](https://github.com/scriptscat/scriptcat/assets/85326108/fb56178a-8b9e-4f70-ae6d-65a9b40ab37d)

重新安装插件就暂时正常了

**Comment by CodFrm** [comment]
那有可能是脚本数据影响的，我先记录一下

**Comment by CodFrm** [comment]
有知道安装了啥脚本么?

**Comment by raycho2005** [comment]
bilibili evolved
自动无缝翻页
 CSDN广告完全过滤

**Comment by CodFrm** [comment]
安装这些，会复现么？

**Comment by CodFrm** [comment]
暂时未复现，先close了
