### ISSUE TITLE
ScriptCat GM.setValue 不能持久化？

### ISSUE THREAD

**Issue by k99k5** [scriptscat/scriptcat#243]
https://github.com/magicdawn/bilibili-app-recommend/issues/51#issuecomment-1693051515

配置一直存不下来（）

**Comment by k99k5** [comment]
看了一下，应该是@grant的问题

@grant GM.setValue是无效的

@grant GM_setValue就可以了

**Comment by CodFrm** [comment]
是没有处理GM.setValue的权限授予，这是一个兼容性的问题

**Comment by k99k5** [comment]
> 是没有处理GM.*的权限授予，这是一个兼容性的问题
@connect 好像也没处理？我看log好像axios访问不了

**Comment by CodFrm** [comment]
connect这个处理了的，有复现代码吗？

**Comment by k99k5** [comment]
> connect这个处理了的，有复现代码吗？

bilibili-app-recommend 我有点查不出来了（最后结果就是APP推荐获取不了

**Comment by CodFrm** [comment]
怎么使用和复现呢？我去看看

**Comment by CodFrm** [comment]
我把grant改成这样后，好像可以，不过我也没用过这个脚本，不清楚正常情况是怎么样

```js
// @grant        GM_getValue
// @grant        GM_openInTab
// @grant        GM_setClipboard
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @grant        GM_addStyle
// @grant        GM.getValue
// @grant        GM.openInTab
// @grant        GM.setClipboard
// @grant        GM.setValue
// @grant        GM.xmlHttpRequest
// @grant        GM.addStyle
```

**Comment by k99k5** [comment]
> 我把grant改成这样后，好像可以，不过我也没用过这个脚本，不清楚正常情况是怎么样
> 
> ```js
> // @grant        GM_getValue
> // @grant        GM_openInTab
> // @grant        GM_setClipboard
> // @grant        GM_setValue
> // @grant        GM_xmlhttpRequest
> // @grant        GM_addStyle
> // @grant        GM.getValue
> // @grant        GM.openInTab
> // @grant        GM.setClipboard
> // @grant        GM.setValue
> // @grant        GM.xmlHttpRequest
> // @grant        GM.addStyle
> ```

就手机端的API调用失败了
![image](https://github.com/scriptscat/scriptcat/assets/18001536/87ac76bd-e11f-4334-b288-21ab7a52a377)，
 
这个API https://app.bilibili.com/x/v2/feed/index

**Comment by CodFrm** [comment]
这个功能在哪里呢？

**Comment by CodFrm** [comment]
<img width="558" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/ba3de221-3968-436e-bc4c-3ee615900e88">

是这个栏目么？我这里可以显示

**Comment by k99k5** [comment]
> <img alt="image" width="558" src="https://private-user-images.githubusercontent.com/22783163/289239225-ba3de221-3968-436e-bc4c-3ee615900e88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDU1ODksIm5iZiI6MTcwMjEwNTI4OSwicGF0aCI6Ii8yMjc4MzE2My8yODkyMzkyMjUtYmEzZGUyMjEtMzk2OC00MzZlLWJjNGMtM2VlNjE1OTAwZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA3MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MDdhMjQxNTEzNTE1YzE2YmZiMmE2NDlkNzU4MjFjMmM3NzRlMzJlMjlhZmY4YWQyYTI2ZWI2YTZjMTU2NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZHDW28WyDfT6LGmMMVhUIUiEnD7R6yN159f0_kPhZo">
> 是这个栏目么？我这里可以显示

对，我这个一直是出不来的，暴力猴没这个问题

**Comment by k99k5** [comment]
> > <img alt="image" width="558" src="https://private-user-images.githubusercontent.com/22783163/289239225-ba3de221-3968-436e-bc4c-3ee615900e88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDU1ODksIm5iZiI6MTcwMjEwNTI4OSwicGF0aCI6Ii8yMjc4MzE2My8yODkyMzkyMjUtYmEzZGUyMjEtMzk2OC00MzZlLWJjNGMtM2VlNjE1OTAwZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA3MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MDdhMjQxNTEzNTE1YzE2YmZiMmE2NDlkNzU4MjFjMmM3NzRlMzJlMjlhZmY4YWQyYTI2ZWI2YTZjMTU2NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZHDW28WyDfT6LGmMMVhUIUiEnD7R6yN159f0_kPhZo">
> > 是这个栏目么？我这里可以显示
> 
> 对，我这个一直是出不来的，暴力猴没这个问题
浏览器是Edge 119.0.2151.97
![image](https://github.com/scriptscat/scriptcat/assets/18001536/bfdf87ac-b523-4064-9bcb-3e27c9c564cc)

**Comment by CodFrm** [comment]
这个错误感觉是网络问题导致的 不是扩展，直接访问这个URL呢？

**Comment by k99k5** [comment]
> 这个错误感觉是网络问题导致的 不是扩展，直接访问这个URL呢？

正常的，我用postman测了一下也是好的，没携带Referer头就是正常的

**Comment by CodFrm** [comment]
@k99k5 哥哥看看background中的network有没有发送这个请求：

打开浏览器的开发者模式，然后点扩展的background.html

<img width="360" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/60e02133-53ec-4b1f-8d54-04b0f01255ca">

<img width="894" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/fc4cd7c5-5a8f-4a33-a627-19e48a8287e0">

使用GM_xmlhttpRequest发送的请求可以在这里看到

<img width="822" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/c75d8575-d037-4386-88d5-309702bffc46">

**Comment by k99k5** [comment]
好像没走，我更新下脚本看看

**Comment by k99k5** [comment]
> @k99k5 哥哥看看background中的network有没有发送这个请求，我这里加上上面的`@grant`看起来是没问题的，脚本版本为0.19.5，浏览器：版本 120.0.2210.61 (正式版本) (arm64)
> 
> 打开浏览器的开发者模式，然后点扩展的background.html
> 
> <img alt="image" width="360" src="https://private-user-images.githubusercontent.com/22783163/289404488-60e02133-53ec-4b1f-8d54-04b0f01255ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjE0ODEsIm5iZiI6MTcwMjI2MTE4MSwicGF0aCI6Ii8yMjc4MzE2My8yODk0MDQ0ODgtNjBlMDIxMzMtNTNlYy00YjFmLThkNTQtMDRiMGYwMTI1NWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyMTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OWFiMmMyNTYxZjA5YWY4ZTlkZWFkMWJlM2IwMTRjMTUxOTU4ZTRhM2M1Yjg0YjE2NzY4NThmZDM3MDM5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oLptALl932d177OkL6CNlm4Fqlh8trSq_fa_TeMF9Y4"> <img alt="image" width="894" src="https://private-user-images.githubusercontent.com/22783163/289404510-fc4cd7c5-5a8f-4a33-a627-19e48a8287e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjE0ODEsIm5iZiI6MTcwMjI2MTE4MSwicGF0aCI6Ii8yMjc4MzE2My8yODk0MDQ1MTAtZmM0Y2Q3YzUtNWE4Zi00YTMzLWE2MjctMTllNDhhODI4N2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyMTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMjA1ZWUyZDJiMGI0OGQyODhiMjg1MWZjOGQ5OGM5ZTZiN2Y4M2JiMzYwOGZmZjA4YWZkZGJiMTQxYTZlZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lB4oyvo2MbS7O2fj-xC2P2a7iOZ7L3RDE0mC3vAnpKg">
> 使用GM_xmlhttpRequest发送的请求可以在这里看到
> 
> <img alt="image" width="822" src="https://private-user-images.githubusercontent.com/22783163/289404560-c75d8575-d037-4386-88d5-309702bffc46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjE0ODEsIm5iZiI6MTcwMjI2MTE4MSwicGF0aCI6Ii8yMjc4MzE2My8yODk0MDQ1NjAtYzc1ZDg1NzUtZDAzNy00Mzg2LTg4ZDUtMzA5NzAyYmZmYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyMTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNzkwZWJkNDVjNGFkOGYxYzc5YmY1M2Q4N2ZkYzE1OGRlM2Q4ZTg1MTNiYzM1ZGU3MTYxMjA2YzM0NjY0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LnDBdWHtYA3A50Xfu8Yv9juWE19q9joEuWakdk3G618">

还真是有BUG没走，更新完好了

**Comment by k99k5** [comment]
@CodFrm 老哥有空兼容GM.*这个就完事了应该

**Comment by k99k5** [comment]
@CodFrm 发生了一件很奇妙的事，我笔记本安装同一个脚本没问题，PC上就是background.html连请求都不显示

**Comment by CodFrm** [comment]
已处理，我觉得还是统一使用GM_*的好，后续考虑加些lint规则
