### ISSUE TITLE
@match 端口匹配错误

### ISSUE THREAD

**Issue by DreamNya** [scriptscat/scriptcat#244]
脚本猫`@match http://localhost:3000/`会匹配到`http://localhost:8080/`

截图：
![ce796a348f1d90ab268b55f996b507a4](https://github.com/scriptscat/scriptcat/assets/34838824/dc2e68f0-1d1c-404d-a559-8c3eb7294680)
![6bca961bd77138d5270a545a904844ea](https://github.com/scriptscat/scriptcat/assets/34838824/0cae3846-98fd-4e83-8c0f-27ecc2f0d994)
![cc2b20eb66459b7e38b31d07fdd77d1b](https://github.com/scriptscat/scriptcat/assets/34838824/7fb46a1e-2166-47cf-af7c-2724e80c2e96)

**Comment by CodFrm** [comment]
```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        http://localhost:8000/zh-CN/
// @match        http://localhost:300/zh-CN/
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
})();
```
刚刚试了一下，tampermonkey上述代码匹配到。。。。。所以脚本猫之前对这个也进行了处理，这应该算是一个feature

不过为了规范，我觉得还是纠正过来好点，不规范的东西都西内！

**Comment by cyfung1031** [comment]
> 刚刚试了一下，tampermonkey上述代码匹配到。。。。。所以脚本猫之前对这个也进行了处理，这应该算是一个feature
> 
> 不过为了规范，我觉得还是纠正过来好点，不规范的东西都西内！

#880 重提了
SC的 `@match` 是兼容TM的 `@match`
所以这个不规范要保留
