### ISSUE TITLE
定时脚本的运行日志在哪看。

### ISSUE THREAD

**Issue by NickLau2023** [scriptscat/scriptcat#246]
写了个定时脚本测试，功能是向自己的服务器定时上报数据。
发现第一次运行成功了，但后续在服务器上都没有收到过数据。
界面上会正常显示下次什么时候运行（我设置了每分钟运行一次）。
但运行日志无显示，请教下是否是我用法不对？
![image](https://github.com/scriptscat/scriptcat/assets/143786904/3842851b-9b56-4908-bca8-2b64cdb36230)

**Comment by CodFrm** [comment]
把筛选条件清空，就可以看到这105条了

<img width="1203" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/177db5e5-a064-4397-a86e-a360591657a8">

点击`应用至/运行状态`可以自动跳转到日志页，另外变更了筛选条件后，需要手动点一下右上角的查询

<img width="1255" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/2eb41d55-7789-4d1e-bd3c-bf498c6b0c03">

**Comment by NickLau2023** [comment]
感谢回复，把筛选条件清空后，可以看到日志了。但是发现了其它更多的问题
1、我的脚本没有正确运行。
2、不该运行的任务运行了
代码如下：

`
// ==UserScript==
// @name         定时脚本
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @grant        GM_xmlhttpRequest
// @author       You
// @crontab      * * * * *
// ==/UserScript==

return new Promise((resolve, reject) => {
    // 打开百度网站
    window.location.href = "https://www.baidu.com/";
    // 获取网页源码
    var pageSource = document.documentElement.outerHTML;
    
    // 构造要发送的数据
    var data = new URLSearchParams();
    data.append('id', '3');
    data.append('content', pageSource.length);

    // 发送 POST 请求
    GM_xmlhttpRequest({
        method: "POST",
        url: "http://127.0.0.1/task/setTask",
        data: data.toString(),
        headers: {
            "Content-Type": "application/x-www-form-urlencoded"
        },
        onload: function(response) {
            console.log("网页源码发送成功");
            console.log(response.responseText);
        },
        onerror: function(error) {
            console.error("网页源码发送失败", error);
        }
    });
    resolve();
});
`
但是日志中没有对应的记录
![image](https://github.com/scriptscat/scriptcat/assets/143786904/83e1200b-302c-48e2-a40b-9af66ca0d381)

![image](https://github.com/scriptscat/scriptcat/assets/143786904/cbd5603d-a5d1-404c-9143-a4afac12b890)

**Comment by CodFrm** [comment]
关闭的那个脚本的日志并不是运行日志，是检查更新的一个告警，版本号不符合semver规范

脚本有问题，后台脚本/定时脚本中不能这么玩，这样直接导致整个沙盒环境被破坏了，需要重启扩展/浏览器才行。后面得限制一下这种方法的调用。

```js
window.location.href = "https://www.baidu.com/";
```

**Comment by CodFrm** [comment]
可以打开开发者模式，然后看看background.htm

<img width="886" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/53f06b8e-ed4d-45a1-80e7-954505979faa">

**Comment by NickLau2023** [comment]
window.location.href = "https://www.baidu.com/";

那实现打开某个指定网站的功能，在沙盒环境里要怎么写呀。
我看了api列表，好像没有这块相关的。

麻烦指点下，谢谢！

**Comment by CodFrm** [comment]
用`GM_openInTab`，打开一个新窗口，然后再写一个普通的用户脚本匹配url进行操作

或者使用`GM_xmlhttpRequest`去模拟请求获取数据
