### ISSUE TITLE
setInterval浏览器经常性、周期性崩溃

### ISSUE THREAD

**Issue by ncdn** [scriptscat/scriptcat#248]
具体参见 

https://bbs.tampermonkey.net.cn/thread-5567-1-1.html

**Comment by CodFrm** [comment]
使用的什么版本，光这块代码看起来没问题，也有可能是网页自己的问题，可以用类似工具看看内存占用

<img width="493" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/26491658-d225-407d-9077-1464dd511580">

<img width="556" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/46a6413f-7f86-420a-b24f-d3a43ecc0208">

**Comment by CodFrm** [comment]
还有开发者工具中的内存分析



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ncdn ***@***.***&gt;
发送时间: 2023年12月21日 17:59
收件人: scriptscat/scriptcat ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [scriptscat/scriptcat] setInterval浏览器经常性、周期性崩溃 (Issue #248)





 
具体参见
 
https://bbs.tampermonkey.net.cn/thread-5567-1-1.html

**Comment by ncdn** [comment]
使用版本为 0.15.1
页面占用并不高，但6-12小时间要么页崩，要么浏览器崩，正常开着浏览页面又没事

**Comment by ncdn** [comment]
![image](https://github.com/scriptscat/scriptcat/assets/19751929/415ad075-307e-4366-85d8-30e9fb5593da)

**Comment by ncdn** [comment]
![image](https://github.com/scriptscat/scriptcat/assets/19751929/c0e9c235-3d09-4fee-8d01-e504200313fa)

**Comment by CodFrm** [comment]
不使用浏览器扩展，直接控制台运行这个代码呢？

正常开着浏览页面是有开插件么？

另外可以看看cpu与内存的占用监控。

**Comment by CodFrm** [comment]
大概和扩展无关，先close了
