### ISSUE TITLE
希望添加手动单个更新和全部更新这个功能(用来更新脚本)

### ISSUE THREAD

**Issue by xz00311** [scriptscat/scriptcat#252]
希望添加手动单个更新和全部更新这个功能(用来更新脚本)

**Comment by CodFrm** [comment]
点击最后更新列和前面的选择框可以的
<img width="1265" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/8f457f2d-c888-408e-bc07-a6a8ea67418d">
