### ISSUE TITLE
多设备webdav同步，无法同步删除

### ISSUE THREAD

**Issue by YujiaCheng1996** [scriptscat/scriptcat#254]
多台电脑（大于3台）连接同一个webdav同步，都勾选了同步删除，但是我在一台电脑删除某个脚本后另一台电脑上的脚本还在，于是会反复的自动安装被删除的脚本，没有办法彻底删除。

**Comment by CodFrm** [comment]
扩展都是最新版本么？我没有复现出来

可以在设置里看到脚本的uuid，然后进入webdav的文件夹，根据这个uuid搜索一下

<img width="1268" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/6402fc78-c604-45d0-aee3-5e1516220743">

看看这个文件里面的内容，有没有标记删除

<img width="834" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/199256f3-2168-4ed1-b86d-3b6142226075">

<img width="550" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/3eb4f7c6-214b-4655-82df-e3c7350f38a2">

**Comment by CodFrm** [comment]
好像复现了，我看看，临时处理方式：手动把数据全删了（扩展里的脚本、webdav里这个脚本的数据）

**Comment by CodFrm** [comment]
处理了，试试这个版本：https://github.com/scriptscat/scriptcat/actions/runs/8045523955/job/21970967296
