### ISSUE TITLE
订阅脚本，在周期到的时候，会自动重复安装脚本

### ISSUE THREAD

**Issue by Kenny-Liu** [scriptscat/scriptcat#257]
订阅脚本更新，在周期到的时候，会自动重复安装脚本

![image](https://github.com/scriptscat/scriptcat/assets/9946527/80cd6971-7ec6-4475-8bbe-d9c555ced3ca)
![image](https://github.com/scriptscat/scriptcat/assets/9946527/8779894a-c27c-4dd2-a133-401ce2693e88)

**Comment by CodFrm** [comment]
每个周期都会嘛？

**Comment by Kenny-Liu** [comment]
@CodFrm 只要订阅脚本的版本更新的时候就会把订阅脚本里的scripturl都重新再安装一遍，此时已安装脚本里就会出现重复的脚本

**Comment by CodFrm** [comment]
哥哥试试这个版本 https://github.com/scriptscat/scriptcat/actions/runs/8045203812
