### ISSUE TITLE
当前页面运行中的脚本数量显示不正确

### ISSUE THREAD

**Issue by MisaLiu** [scriptscat/scriptcat#261]
如题，目前该页面只有一个脚本正在运行，但是却显示了两个

![image](https://github.com/scriptscat/scriptcat/assets/62408957/a3ecbb6b-f72e-422d-8957-53c2382bc897)

**Comment by CodFrm** [comment]
那个数字是脚本的运行次数，当页面中有iframe，就会产生这种情况

https://github.com/scriptscat/scriptcat/issues/112

**Comment by MisaLiu** [comment]
🤔 对于一般用户来说这里的数量应该对应的就是「当前页面中正在运行的脚本数量」吧？感觉逻辑有些对不上

**Comment by CodFrm** [comment]
> 🤔 对于一般用户来说这里的数量应该对应的就是「当前页面中正在运行的脚本数量」吧？感觉逻辑有些对不上

运行的脚本数量，可以直接看列表中脚本数量看出来，运行次数就不好看了。不过至于为什么这样，只能说是历史原因，脚本管理器大多都是这个做法😅
