### ISSUE TITLE
edge打开浏览器不会自动执行后台脚本

### ISSUE THREAD

**Issue by FBIshouxi** [scriptscat/scriptcat#263]
Microsoft Edge
版本 122.0.2365.66 (正式版本) (64 位)
edge打开浏览器不会自动执行后台脚本

**Comment by CodFrm** [comment]
你的脚本是怎么样的呢？

**Comment by FBIshouxi** [comment]
找到原因了，edge开机后会自动执行并且停在后台， 所以每次打开浏览器， 都不是启动浏览器，就不会执行

**Comment by FBIshouxi** [comment]
右下角小图标，关闭edge, 再重新打开就可以看到执行了

**Comment by FBIshouxi** [comment]
但是如果不让浏览器在后台运行，是不是定时脚本也就没用了？我的是每次进入浏览器就会获取有道云cookie的脚本，每次打开浏览器都得执行一次

**Comment by CodFrm** [comment]
是的 如果不让浏览器在后台运行，定时脚本会失效的

后台脚本是浏览器打开的第一次执行

定时脚本是定时执行
