### ISSUE TITLE
内存占用异常

### ISSUE THREAD

**Issue by visiLi** [scriptscat/scriptcat#266]
新版本会造成访问B站等视频网站时内存占用飙升造成网页崩溃

**Comment by CodFrm** [comment]
有搭配什么脚本呢？

使用浏览器的任务管理工具看看具体占用

<img width="493" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/973d2083-79c7-4ce9-b248-e902321b346f">

<img width="623" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/d76b7f36-0152-4ca7-a884-599947a2e214">

**Comment by visiLi** [comment]
![微信截图_20240314102605](https://github.com/scriptscat/scriptcat/assets/42717403/33dcb209-fa7d-4643-8e4d-5913767471ca)
脚本数量是43个

**Comment by visiLi** [comment]
经过测试

**Comment by visiLi** [comment]
> 经过测试，怀疑是【Bilibili Evolved (Preview)】插件

B站笔记快捷键←↓→

**Comment by CodFrm** [comment]
试试关闭插件后，再看看内存，我这里感觉就是b站自己占用的内存比较大

不过占用3G多确实离谱了

**Comment by CodFrm** [comment]
另外，是不是在这个页面窗口没有刷新过？一直是点推荐内容看的？

**Comment by visiLi** [comment]
关闭插件就好了。貌似不纯粹是脚本的问题！
捂脸

**Comment by visiLi** [comment]
> 另外，是不是在这个页面窗口没有刷新过？一直是点推荐内容看的？

我会刷新的

**Comment by visiLi** [comment]
使用油猴没有出现此类问题

**Comment by CodFrm** [comment]
> 使用油猴没有出现此类问题

必现么？就正常浏览b站，老版本的脚本猫没有出现么？

麻烦再提供一下操作系统和浏览器版本，我先尝试复现

**Comment by visiLi** [comment]
正在测试浏览器

**Comment by visiLi** [comment]
版本	Windows 11 专业版
版本	23H2
安装日期	‎2024/‎3/‎2
操作系统版本	22631.3155
体验	Windows Feature Experience Pack 1000.22684.1000.0

使用的是猫眼浏览器

**Comment by visiLi** [comment]
> 版本 Windows 11 专业版 版本 23H2 安装日期 ‎2024/‎3/‎2 操作系统版本 22631.3155 体验 Windows Feature Experience Pack 1000.22684.1000.0
> 
> 使用的是猫眼浏览器 内核:123.0.6312.37

占用就是上边的图片

**Comment by visiLi** [comment]
刚刚用谷歌浏览器
内核版本：122.0.6261.95
![微信截图_20240314123113](https://github.com/scriptscat/scriptcat/assets/42717403/19e32073-01e3-48d2-9d76-034d77bf73f9)

**Comment by visiLi** [comment]
> 刚刚用谷歌浏览器 内核版本：122.0.6261.95 ![微信截图_20240314123113](https://private-user-images.githubusercontent.com/42717403/312700053-19e32073-01e3-48d2-9d76-034d77bf73f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTEwMDcsIm5iZiI6MTcxMDM5MDcwNywicGF0aCI6Ii80MjcxNzQwMy8zMTI3MDAwNTMtMTllMzIwNzMtMDFlMy00OGQyLTlkNzYtMDM0ZDc3YmY3M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA0MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMjQxZjAzNmI0NzFjZTQ1YTk4ZTA3ODVlYjA4OTY3NjRlY2FjNzUwOTc3NTg0ZDQyYmY2ZTllNTI0N2FjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sp2-E2n6-nJDc00oQ_qAgcjKP4r8cncO75S73EvrWAI)

刚才瞬间 单进程就达到3G多

**Comment by CodFrm** [comment]
> > 刚刚用谷歌浏览器 内核版本：122.0.6261.95 ![微信截图_20240314123113](https://private-user-images.githubusercontent.com/42717403/312700053-19e32073-01e3-48d2-9d76-034d77bf73f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTEwMDcsIm5iZiI6MTcxMDM5MDcwNywicGF0aCI6Ii80MjcxNzQwMy8zMTI3MDAwNTMtMTllMzIwNzMtMDFlMy00OGQyLTlkNzYtMDM0ZDc3YmY3M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA0MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMjQxZjAzNmI0NzFjZTQ1YTk4ZTA3ODVlYjA4OTY3NjRlY2FjNzUwOTc3NTg0ZDQyYmY2ZTllNTI0N2FjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sp2-E2n6-nJDc00oQ_qAgcjKP4r8cncO75S73EvrWAI)
> 
> 
> 
> 刚才瞬间 单进程就达到3G多

主要看浏览器自带的任务管理，看那个的内存占用，浏览器总共占3G是正常现象

**Comment by visiLi** [comment]
使用别的Chromium结果如下图
123浏览器
内核： 117.0.5938.152
![000001111](https://github.com/scriptscat/scriptcat/assets/42717403/0ed6f066-b5e9-4614-b11e-8d0634cd50c7)
夸克浏览器
内核：112.0.5615.165
![1111111](https://github.com/scriptscat/scriptcat/assets/42717403/d0e3cd74-cc1a-4222-98f5-0733f0433a6c)

**Comment by visiLi** [comment]
> > > 刚刚用谷歌浏览器 内核版本：122.0.6261.95 ![微信截图_20240314123113](https://private-user-images.githubusercontent.com/42717403/312700053-19e32073-01e3-48d2-9d76-034d77bf73f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTEwMDcsIm5iZiI6MTcxMDM5MDcwNywicGF0aCI6Ii80MjcxNzQwMy8zMTI3MDAwNTMtMTllMzIwNzMtMDFlMy00OGQyLTlkNzYtMDM0ZDc3YmY3M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA0MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMjQxZjAzNmI0NzFjZTQ1YTk4ZTA3ODVlYjA4OTY3NjRlY2FjNzUwOTc3NTg0ZDQyYmY2ZTllNTI0N2FjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sp2-E2n6-nJDc00oQ_qAgcjKP4r8cncO75S73EvrWAI)
> > 
> > 
> > 刚才瞬间 单进程就达到3G多
> 
> 主要看浏览器自带的任务管理，看那个的内存占用，浏览器总共占3G是正常现象

我说的是单个当前进程

**Comment by visiLi** [comment]
> > > > 刚刚用谷歌浏览器 内核版本：122.0.6261.95 ![微信截图_20240314123113](https://private-user-images.githubusercontent.com/42717403/312700053-19e32073-01e3-48d2-9d76-034d77bf73f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTEwMDcsIm5iZiI6MTcxMDM5MDcwNywicGF0aCI6Ii80MjcxNzQwMy8zMTI3MDAwNTMtMTllMzIwNzMtMDFlMy00OGQyLTlkNzYtMDM0ZDc3YmY3M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA0MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMjQxZjAzNmI0NzFjZTQ1YTk4ZTA3ODVlYjA4OTY3NjRlY2FjNzUwOTc3NTg0ZDQyYmY2ZTllNTI0N2FjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sp2-E2n6-nJDc00oQ_qAgcjKP4r8cncO75S73EvrWAI)
> > > 
> > > 
> > > 刚才瞬间 单进程就达到3G多
> > 
> > 
> > 主要看浏览器自带的任务管理，看那个的内存占用，浏览器总共占3G是正常现象
> 
> 我说的是单个当前进程

![222222](https://github.com/scriptscat/scriptcat/assets/42717403/0c31e94c-826b-4776-b605-6108f657ec5c)

**Comment by CodFrm** [comment]
我今天拿到了台Windows机器进行测试，脚本对内存的影响确实很明显，不过没有出现哥哥那么异常的现象（都是播放了一小段时间的）

未开启任何脚本管理器扩展
![image](https://github.com/scriptscat/scriptcat/assets/22783163/c4bdaba3-db5c-4994-8888-9119d57405b9)

开启脚本猫扩展未开启脚本
![image](https://github.com/scriptscat/scriptcat/assets/22783163/11831269-4490-448c-9780-ee902a367035)

开启脚本猫开启Bilibili Evolved (Preview)脚本
![image](https://github.com/scriptscat/scriptcat/assets/22783163/1216c188-9f71-4642-bd23-84fd9f37d575)

安装了常用组件包
![image](https://github.com/scriptscat/scriptcat/assets/22783163/3c2f3e8a-2ccf-4c09-9e46-cc1e0e645932)

**Comment by CodFrm** [comment]
我只有疯狂浏览评论区，内存才会飙升很高

![image](https://github.com/scriptscat/scriptcat/assets/22783163/dbe6becb-d3d9-4c02-b80b-6148890158bf)

**Comment by CodFrm** [comment]
现在还有这个情况么？

**Comment by visiLi** [comment]
> 现在还有这个情况么？

不敢用在猫眼浏览器了。

**Comment by CodFrm** [comment]
那先关闭了，无法复现

**Comment by visiLi** [comment]
> 感觉和浏览器应该没关系，不太清楚，无法复现，先关闭了

好的 有问题再说吧
