### ISSUE TITLE
网站是被污染了吗

### ISSUE THREAD

**Issue by 5418541** [scriptscat/scriptcat#267]
比如油叉网站和脚本猫脚本站，同样是国内直连，我可以直接进油叉，脚本猫是加载好久，我是移动网络和广电网络都会这样

**Comment by CodFrm** [comment]
你是什么地区呢？可以ping一下看看解析到的ip吗？

**Comment by 5418541** [comment]
> 你是什么地区呢？可以ping一下看看解析到的ip吗？
> 
> 或者f12的network，看看时间线详情，和访问ip

是福建福州的，我用广电网络的两个DNS，ping网站，只有福建厦门有IP地址103.228.64.167，速度为88ms，其他的都访问失败
至于按f12的network，我是用手机上的x浏览器的开发者工具，network是空白的

**Comment by CodFrm** [comment]
反馈给服务商了，现在有好转么？

**Comment by 5418541** [comment]
> 反馈给服务商了，现在有好转么？

现在打开很快了，不过我现在就只试了广电的，移动的还不知道，可能是我把DNS改了的问题？要等会用移动ping吗
