### ISSUE TITLE
希望界面优化一下的地方

### ISSUE THREAD

**Issue by lysps** [scriptscat/scriptcat#269]
1、之前论坛说的那个好多脚本的选项干掉 
![105615qo17tciy5ikztsxc](https://github.com/scriptscat/scriptcat/assets/64192917/09a4cb81-0f11-4c6a-a893-f1c0865d7411)

2、就是能不能优化一下，这个宽窄。我的surface 屏幕很小。
我觉得脚本名字比其他都重要....
<img width="900" alt="Snipaste_2024-03-25_16-08-22" src="https://github.com/scriptscat/scriptcat/assets/64192917/2afc8542-29a1-46e0-8427-bd486247cf0c">

**Comment by CodFrm** [comment]
这确实短得过分了，后续考虑怎么优化

我自己屏幕也不算大，也就比哥哥好一点点

**Comment by CodFrm** [comment]
现在点击多选框，支持调整列了

<img width="1279" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/162acd2b-b7ae-40a0-97be-ea8e7d836e61">

**Comment by CodFrm** [comment]
现在支持菜单项隐藏配置了：

<img width="729" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/1b26ae12-1535-4c82-9838-b5e8b8518a89">

<img width="320" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/4cd67638-128c-4c3f-84e5-b77c7890eb12">
