### ISSUE TITLE
subscribe:1 error: Error: Network Error	

### ISSUE THREAD

**Issue by hsqoo** [scriptscat/scriptcat#27]
日志打印：subscribe:1 error: Error: Network Error	
内容：      check subscribe

**Comment by CodFrm** [comment]
订阅脚本的链接能正常访问吗？可以发出来我试试

**Comment by hsqoo** [comment]
打开浏览器的时候断网状态，如何让订阅自动更新？

**Comment by CodFrm** [comment]
断网这种情况也没办法，我增加一个重试逻辑吧

订阅现在是根据这个时间周期去自动更新的：
![image](https://user-images.githubusercontent.com/22783163/148710002-39f5e02c-ed19-4b18-950f-402794249ad9.png)

**Comment by hsqoo** [comment]
请问你这里的时间是服务器时间还是本地时间？

**Comment by CodFrm** [comment]
这里是一个时间周期，和服务器本地具体时间无关的
