### ISSUE TITLE
关于 Manifest V3 的疑惑

### ISSUE THREAD

**Issue by IAALAI** [scriptscat/scriptcat#271]
现在不是只有chrome一个在强推 Manifest V3 吗？它说它相比Manifest V2限制更多效果却没有变化，现在来看有必要切换到 V3 吗？我看V2在edge上还可以正常运行，同时也可以正常的上传到edge的扩展商店

**Comment by WindrunnerMax** [comment]
据我所知确实是这样

**Comment by CodFrm** [comment]
> 现在不是只有chrome一个在强推 Manifest V3 吗

我现在了解到的，Chromium内核的浏览器都是如此

> V2在edge上还可以正常运行

目前当然可以运行，但是在2024年6月的chrome 127起，将会停止不稳定版本的v2版本的扩展，什么时候停止稳定版本上的mv2虽然还没公布，但也看出是一个趋势了

https://developer.chrome.com/blog/resuming-the-transition-to-mv3?hl=zh-cn#the_phase-out_timeline

> 同时也可以正常的上传到edge的扩展商店

只能进行更新了，并不能上传，从前几年开始就是这样了，并且商店中的mv2扩展也会有一定限制


我也很不愿意切换到mv3，但目前看来大势所趋，功能上，对现有的大部分脚本应该影响不会很大，主要是GM_xhr的一些功能无法使用了（任意修改header请求），不过最恶心的一点是，使用userscript，必须用户手动开启开发者模式：
https://developer.chrome.com/docs/extensions/reference/api/userScripts?hl=zh-cn#developer_mode_for_extension_users

**Comment by WindrunnerMax** [comment]
不过话说回来，如果是谷歌直接在以后的浏览器内核级别上删除了`v2`的支持的话，那以后的以`chromium`为内核的浏览器支持就够呛了

**Comment by IAALAI** [comment]
v3不但没增强，还是纯倒退恶心人了啊。。。

**Comment by CodFrm** [comment]
一直很想上传一个beta版本，每次更新我都怕写了个啥严重的bug没发现，有beta版本的话就可以尽量缩小范围，但是因为mv2的原因，商店无法接受，只能手动下载扩展文件进行安装，导致实际的beta用户极少

**Comment by letterk** [comment]
v3就是针对广告拦截扩展的
