### ISSUE TITLE
grant unsafeWindow 后 window scope 问题

### ISSUE THREAD

**Issue by WindrunnerMax** [scriptscat/scriptcat#273]
在`grant unsafeWindow`后，即使使用`window`也可以访问`inject`页面本身的`window`对象，与油🐒脚本管理器的表现不一致，不知是否符合预期。

```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        https://quilljs.com/playground/snow
// @grant        unsafeWindow
// ==/UserScript==

(function() {
    'use strict';
    console.log(window === unsafeWindow);
    console.log("window", "------", window.Quill)
    console.log("unsafeWindow", "------", unsafeWindow.Quill)
    // Your code here...
})();
```

加入脚本后访问`https://quilljs.com/playground/snow`，即使`window`已经是被代理而非原始`window`，但仍可以发现在`window`上也可以访问到`Quill`对象。

<img width="685" alt="image" src="https://github.com/scriptscat/scriptcat/assets/33169019/a9d0b892-c645-4715-8ded-6b218814c9fb">

**Comment by CodFrm** [comment]
看起来是不符合预期的，沙盒模式下，不应该能通过window访问到Quill

**Comment by CodFrm** [comment]
刚刚试了一下，3个脚本管理器表示都不一样，不过我认为从设计上来说，tm的表现形式应该是正确的 (vm加上setTimeout后正确，难道是vm执行太快了？)

<img width="1413" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/fc5f7a37-38b8-43c7-b073-a368ab16780b">

**Comment by WindrunnerMax** [comment]
我感觉严格上来说，第二个表现应该是比较正确？

**Comment by WindrunnerMax** [comment]
funny

**Comment by CodFrm** [comment]
处理了，目前的表现形式与tm一致了，哥哥可以试试这个版本：https://github.com/scriptscat/scriptcat/actions/runs/8873074186

但是不知道会不会对其它内容产生影响，单元测试是通过了（

**Comment by WindrunnerMax** [comment]
ggnb

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptcat/actions/runs/8874658426
