### ISSUE TITLE
WebIDE鼠标侧键问题

### ISSUE THREAD

**Issue by ITBOYLIN** [scriptscat/scriptcat#277]
在WebIDE中，已经编写好的代码，未保存下按下鼠标侧键会直接返回到脚本主页，无任何提示，导致代码丢失

**Comment by CodFrm** [comment]
还有个脚本重载的功能吧

在这里记录一下，免得忘记

ScriptCat改进建议
https://bbs.tampermonkey.net.cn/thread-7031-1-1.html
(出处: 油猴中文网)

**Comment by CodFrm** [comment]
另外一个问题我新开了

https://github.com/scriptscat/scriptcat/issues/298
