### ISSUE TITLE
[疑问]通过GM_openInTab方法打开的页面，能否获取该页面的window对象

### ISSUE THREAD

**Issue by hsqoo** [scriptscat/scriptcat#28]

**Comment by CodFrm** [comment]
不能的，如果你想操作打开的页面，只能通过通信的方式去做。

可以使用[GM_add/removeValueChangeListener](https://docs.scriptcat.org/dev/api.html#gm-add-removevaluechangelistener)，来实现简单的通信，后续可能会增加专门的API来操作

一个例子：https://scriptcat.org/script-show-page/111/code   https://scriptcat.org/script-show-page/110/code

**Comment by CodFrm** [comment]
window.open 满足同源策略可以操作

https://developer.mozilla.org/zh-CN/docs/Web/API/Window/open

具体还没试过，哥哥可以看看
