### ISSUE TITLE
npm run pack 当前文件夹没有 script.pem 文件

### ISSUE THREAD

**Issue by T0205** [scriptscat/scriptcat#282]
请问 如何 在 dist目录下 生成 scriptcat.pem文件 ? ? ? 并运行 npm run pack.

**Comment by T0205** [comment]
当前的 dist/ext 的插件150mb, 从releases 中下载的只有 10mb左右, 所以想着如何减少一些体积

**Comment by CodFrm** [comment]
我一般都是手动用浏览器生成一下pem文件，再用npm run pack打包

话说哥哥不能从action里面下载么？

**Comment by T0205** [comment]
> 我一般都是手动用浏览器生成一下pem文件，再用npm run pack打包
> 
> 话说哥哥不能从action里面下载么？

因为需求需要将用户用不到的菜单给隐藏起来,  需要重新打包, 所以actions中下载的不能用 (●･̆⍛･̆●)

**Comment by CodFrm** [comment]
那需要哥哥自己生成pem文件了
