### ISSUE TITLE
能不能内置一个可打开的页面用来运行前台脚本，而不需要打开任何网站

### ISSUE THREAD

**Issue by chopins** [scriptscat/scriptcat#284]
在脚本管理页面，运行时，可以新开一个TAB，打开一个内置页面，用来运行该脚本

我最近写了一个TOTP的验证脚本，替代各种APP进行2FA验证，这样有浏览器后，就不需要另行安装程序。
而这个脚本并不需要打开任何特定网站，如果是PC还好，可以打开一个本地页面，手机端就很麻烦，必须要开一个网站页面。

**Comment by CodFrm** [comment]
可以用后台脚本，你可以参考我这个脚本，不过他好像有些性能问题

https://github.com/CodFrm/userscript/blob/main/topt-script/src/main.ts

他是为`vite-plugin-monkey`提交的，目前还没有合并

https://github.com/lisonge/vite-plugin-monkey/pull/151

**Comment by chopins** [comment]
似乎还无法满足需求，
/src/background.html 里面的 iframe 默认是隐藏的， 也不能修改这个iframe
另外 GM_registerMenuCommand 也是没有效果的

**Comment by CodFrm** [comment]
你为什么需要修改iframe？

如果是调试模式，GM_registerMenuCommand好像是没有效果的

**Comment by chopins** [comment]
修改iframe 是为了让脚本创建的内容显示出来
这样脚本能有丰富的交互能力

**Comment by CodFrm** [comment]
@chopins 你意思是想通过脚本来展示一个全新的页面？目前是没有这种API的，实现上好像也不太好说，后续可以看看

**Comment by chopins** [comment]
没那么复杂，也不是展示一个全新页面。
比如，目前是可以直接打开 /src/background.html, 然后控制台把 /src/sandbox.html 这个iframe 的显示，就能实现我的目的。

比如下面的例子：
```js
return new Promise((resolve, reject) => {
      GM_registerMenuCommand('test', ()=> {
          createBtn('添加', 'add', 'add', add);
      });
});
```
当点击注册的菜单后，看截图，页面内容，菜单，以及右边的开发工具

![Uploading 截图 2024-06-04 11-42-17.png…]()

**Comment by chopins** [comment]
@CodFrm 
我创建了一个PR #287

**Comment by CodFrm** [comment]
这样有什么问题吗？

<img width="816" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/9620f344-56e9-425c-b0af-abbc61794a73">

```js
// ==UserScript==
// @name         2fa 演示
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  一个演示
// @author       You
// @background
// @grant GM_registerMenuCommand
// @grant GM_setClipboard
// ==/UserScript==

return new Promise((resolve, reject) => {
    GM_registerMenuCommand("Github 2fa", () => {
        GM_setClipboard("123456")
    });
});
```

**Comment by CodFrm** [comment]
是还想要一个可以做一些操作的页面么？（例如备份、添加、导入）

**Comment by chopins** [comment]
其实主要是移动端的需求，
移动端对于文件访问限制太多，所以我想到了在扩展里内置一个页面办法

**Comment by CodFrm** [comment]
@chopins 还是和我上面说的一样的，并不需要扩展内置，打开一个属于你自己的页面，在那个页面上进行操作就好

**Comment by chopins** [comment]
@CodFrm  如果没网络的情况下，要怎么打开一个页面？特别是当手机没任何网络，而手机浏览器又不允许打开本地页面的时候。
其实这个功能本质就是让一个脚本成了一个特别的APP（与什么小程序，Electron类似）。现在scriptcat的后台脚本其实也是这么一个功能，只不过没有UI交互而已。
另外可以关闭这个issue了

**Comment by CodFrm** [comment]
@chopins  没有网络，那么也没太大意义了，脚本都无法工作
