### ISSUE TITLE
Firefox版脚本猫不支持搜索酱

### ISSUE THREAD

**Issue by YandLiu** [scriptscat/scriptcat#291]
我用Firefox+脚本猫安装搜索酱，是无法正常工作的，但是Edge+脚本猫+搜索酱正常
https://greasyfork.org/zh-CN/scripts/445274-searchjumper

**Comment by CodFrm** [comment]
GM_addElement 这个方法导致的，已修复：https://github.com/scriptscat/scriptcat/actions/runs/9835526969
