### ISSUE TITLE
Feature Request：希望脚本列表显示脚本图标

### ISSUE THREAD

**Issue by YandLiu** [scriptscat/scriptcat#292]
就像Violentmonkey和Tampermonkey那样，方便从脚本列表里找脚本

**Comment by CodFrm** [comment]
![12b406bb747e77e880811052cc726993](https://github.com/scriptscat/scriptcat/assets/22783163/36d29e44-ff3d-4ccc-9bc9-940b776c8ad2)

是这个弹出的列表嘛？

**Comment by YandLiu** [comment]
是的 也包括管理器页面希望能显示图标

**Comment by CodFrm** [comment]
![13cbf5360684dee9f955d0d254236df7](https://github.com/scriptscat/scriptcat/assets/22783163/7ac7dbea-1ce1-4e82-9220-bfaed539d45b)

![e2c0e0552f41b7aeafb0f224c55f92a6](https://github.com/scriptscat/scriptcat/assets/22783163/2aa6c164-c332-418e-9d3c-a51e13406535)

已增加
