### ISSUE TITLE
Extension dashboard layout slightly messed up with English as language

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [scriptscat/scriptcat#297]
The extension dashboard layout is slightly messed up when using English as a language, for example the `x minutes ago` characters are laid out vertically because of `word-break: break-all;` and some elements are overlapping. Not a huge issue (can just use Chinese instead) but this makes the table columns really high.

![msedge-2024-07-08-14-43-msedge_CSeu3Ls23v](https://github.com/scriptscat/scriptcat/assets/110549389/e98cc0dd-942a-4663-b8ce-365742e52ab7)

**Comment by henrikvilhelmberglund** [comment]
> What device are you using? Mine looks normal.

Interesting! I'm on PC (Windows), for me Chrome, Brave and Edge look the same. Not too sure why it happens then.
![image](https://github.com/scriptscat/scriptcat/assets/110549389/839079e6-a7eb-44fc-b8df-90a2405fe8d6)

**Comment by CodFrm** [comment]
![c5a4c2e5e8bb56bafdae11137103de98](https://github.com/scriptscat/scriptcat/assets/22783163/f8f88c41-bd6b-42e8-97ab-1bd49d37079c)

It appeared when there was no installation script. Thank you for your feedback.
