### ISSUE TITLE
控制台报错MutationEvent is not defined

### ISSUE THREAD

**Issue by MerielVaren** [scriptscat/scriptcat#299]
脚本地址：[更好的 Youtube Shorts](https://greasyfork.org/zh-CN/scripts/487271-better-youtube-shorts)

1. 运行环境为：Chrome Dev 128.0.6559.0
- 暴力猴 2.20.0：正常运行
- 脚本猫 0.16.3：控制台报错 MutationEvent is not defined

2. 运行环境为：Chrome 126.0.6478.127
- 暴力猴 2.20.0：正常运行
- 脚本猫 0.16.3：正常运行

MutationEvent从127开始被移除，但是我并没有使用MutationEvent，我在脚本中只使用了MutationObserver，而MutationObserver并没有被弃用

已知可以在用户端把[chrome://flags/#mutation-events](chrome://flags/#mutation-events)设置为Enabled解决这个问题，脚本猫是否可以像[https://github.com/Tampermonkey/tampermonkey/issues/2011#issuecomment-2022872478](https://github.com/Tampermonkey/tampermonkey/issues/2011#issuecomment-2022872478)一样在之后的版本中修复这个问题

**Comment by CodFrm** [comment]
![81e33ced68c2bc0f163e1a99fe1e6b95](https://github.com/scriptscat/scriptcat/assets/22783163/68302a09-2900-46f6-a8b7-8e56088c9b92)

啊，这个东西还挺重要的，影响有严重了，我研究一下

**Comment by CodFrm** [comment]
请问什么时候会触发？

我使用`128.0.6559.0（正式版本）dev (arm64)`，脚本猫 v0.16.4，运行上述脚本，暂未复现

**Comment by MerielVaren** [comment]
浏览器：Chrome Dev 128.0.6559.0
网址：[https://www.youtube.com/shorts/8Og5ZESMi8s](https://www.youtube.com/shorts/8Og5ZESMi8s)
脚本猫版本：0.16.4 (github release) / 0.16.3 (chrome网上应用商店)
插件地址：[https://greasyfork.org/zh-CN/scripts/487271-better-youtube-shorts](https://greasyfork.org/zh-CN/scripts/487271-better-youtube-shorts)
报错信息：MutationEvent is not defined

以上运行环境下稳定触发上述的报错 @CodFrm

**Comment by MerielVaren** [comment]
当我在相同的运行环境下使用另一个用到MutationObserver的插件[去除链接重定向](https://greasyfork.org/zh-CN/scripts/483475-%E5%8E%BB%E9%99%A4%E9%93%BE%E6%8E%A5%E9%87%8D%E5%AE%9A%E5%90%91)访问[bing - hello](https://www.bing.com/search?q=hello)时，Chrome Dev给出了更多的报错信息
我猜测，是因为MutationObeserver内部仍然使用了这些MutationEvent的事件导致报错？
希望对作者有所帮助
![屏幕截图 2024-07-11 161540](https://github.com/scriptscat/scriptcat/assets/76115617/ebae3671-4630-4c63-b487-c583bae01faa)

**Comment by MerielVaren** [comment]
> ![81e33ced68c2bc0f163e1a99fe1e6b95](https://private-user-images.githubusercontent.com/22783163/347674880-68302a09-2900-46f6-a8b7-8e56088c9b92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODYyODEsIm5iZiI6MTcyMDY4NTk4MSwicGF0aCI6Ii8yMjc4MzE2My8zNDc2NzQ4ODAtNjgzMDJhMDktMjkwMC00NmY2LWE4YjctOGU1NjA4OGM5YjkyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA4MTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZWJjMTI0NmQ1Zjc3YjU0N2Q0Nzc3NWRkMGI2YzRlMjZkMjUxYzBkODgwOWVlOWQzMzE3Yjk5YjUwNWEwYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CYzI94OwtLeRPJLAsx5Wqj54H7hx9no_Y-VhQk-OCBE)
> 
> 啊，这个东西还挺重要的，影响有点严重了，我研究一下
> 
> https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent
> 
> 主要是在脚本猫中的消息交互有用到

是的，我认为这个bug需要及时得到修复，因为根据[时间表](https://developer.chrome.com/blog/mutation-events-deprecation?hl=zh-cn)来看，Chrome稳定版将在7月23日升到v127，如果不修复的话彼时可能所有带有MutationObserver或MutationEvent的插件将不能正常工作

**Comment by CodFrm** [comment]
修复了，哥哥试试这个版本：https://github.com/scriptscat/scriptcat/actions/runs/9901910434

主要影响到使用了GM_addElement/addStyle的脚本

**Comment by MerielVaren** [comment]
我这边测了一下没有报错了
