### ISSUE TITLE
一些小建议...

### ISSUE THREAD

**Issue by zaaack** [scriptscat/scriptcat#3]
1. [x] 日志带时间
2. [x] 支持在网页上的点击右键菜单中运行
3. [x] 新建脚本之后默认开启
4. [ ] 保存之后列表自动刷新

**Comment by SSmJaE** [comment]
其它几条好说，第二条是指？

**Comment by CodFrm** [comment]
> 其它几条好说，第二条是指？

这个我知道,应该是油猴的 这个 [context-menu](https://www.tampermonkey.net/documentation.php#_run_at)

**Comment by zaaack** [comment]
@SSmJaE @CodFrm 额看起来有点不太一样，其实我想说的是加入到右键菜单里面，比如这样
<img src="https://user-images.githubusercontent.com/5233940/115329290-b1962080-a1c4-11eb-866f-edd2fda007d6.png" width=300 />

**Comment by CodFrm** [comment]
> @SSmJaE @CodFrm 额看起来有点不太一样，其实我想说的是加入到右键菜单里面，比如这样
> <img alt="" width="300" src="https://user-images.githubusercontent.com/5233940/115329290-b1962080-a1c4-11eb-866f-edd2fda007d6.png">

感觉是一样的😅，下个版本应该会实现，到时候再看看？

**Comment by CodFrm** [comment]
右键菜单: https://docs.scriptcat.org/dev/meta.html#run-at
一个demo: 
```js
// ==UserScript==
// @name         🌃右键demo
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  一个显示在github上的右键demo
// @author       You
// @match        https://github.com/*
// @run-at       document-menu
// @grant        unsafeWindow
// @grant GM_setValue
// @grant GM_listValues
// @grant CAT_click
// @supportURL   http://bbs.tampermonkey.net.cn/forum.php?mod=viewthread&tid=250
// @homepage     http://bbs.tampermonkey.net.cn/forum.php?mod=viewthread&tid=250
// ==/UserScript==

alert("右键点击");
```
