### ISSUE TITLE
对@match规则的处理问题

### ISSUE THREAD

**Issue by slightin** [scriptscat/scriptcat#30]
在tampermonkey中，@match “https://hostname” 规则仅会使脚本在该域名的主页运行，即pathname=="/"时运行
而在scriptcat中，@match “https://hostname” 规则会使脚本在该域名下的所有页面运行，和@match “https://hostname/*” 的效果相同

**Comment by CodFrm** [comment]
测试了一下，并没有出现，能给出一个具体的网址和截图吗？

```js
// ==UserScript==
// @name         Match test
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        https://bbs.tampermonkey.net.cn
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
})();
```

![image](https://user-images.githubusercontent.com/22783163/150263183-d593c732-ed72-4315-8758-389b3cf81c9a.png)

![image](https://user-images.githubusercontent.com/22783163/150263203-91ad53a6-78b5-466c-bb1b-b516fd005ead.png)

**Comment by slightin** [comment]
出现问题的网址是“http://IP地址：端口号/“格式的，当把端口号设置为通配时就会出现上述情况
网址为 http://27.188.65.169:9111/ 端口号为9111~9116 ，@match声明如下”http://27.188.65.169:*/“

**Comment by slightin** [comment]
```
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        http://27.188.65.169:*/
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
    alert("脚本被执行")
})();
```
![image](https://user-images.githubusercontent.com/67229521/150297462-534aa966-94c5-479e-b399-cfcc509205d8.png)
![image](https://user-images.githubusercontent.com/67229521/150297519-3fada4e1-2a80-46a2-b5ad-95ccadc0399e.png)
