### ISSUE TITLE
新建脚本通过设置添加match失败

### ISSUE THREAD

**Issue by bonaluo** [scriptscat/scriptcat#301]
新建脚本没有保存添加match失败
<img width="875" alt="image" src="https://github.com/user-attachments/assets/7f59eeb7-cc53-4aad-a54f-cdda756f5ec4">
新建脚本保存后添加match失败
<img width="851" alt="image" src="https://github.com/user-attachments/assets/3004f471-9625-451e-aeae-b97251a6cf2a">
保存并刷新页面后还是失败
<img width="862" alt="image" src="https://github.com/user-attachments/assets/a6f54815-5cee-4677-8e2f-d5ff7e5261fc">

**Comment by CodFrm** [comment]
需要先保存一下脚本
