### ISSUE TITLE
脚本丢失

### ISSUE THREAD

**Issue by mytokendemo** [scriptscat/scriptcat#304]
你好 我想咨询下  我每次新建的脚本  过两天在此打开就变成空的了 这个是什么原因呢

**Comment by CodFrm** [comment]
磁盘空间足够么？由于目前使用的indexedDB作为存储，在磁盘空间不够时会自动清理，后续考虑切换储存引擎

**Comment by mytokendemo** [comment]
好的  明白了  感谢回复
