### ISSUE TITLE
脚本猫下运行脚本有问题

### ISSUE THREAD

**Issue by YandLiu** [scriptscat/scriptcat#308]
测试页面：
https://seekingalpha.com/symbol/GLPG/news

脚本：
https://gist.github.com/YandLiu/4ffc391f5b66bf8479ca2ba45beed83e

期待表现（需要先访问过 xueqiu.com 确保能获取到雪球行情数据）：
![图片](https://github.com/user-attachments/assets/d18362ee-f5b1-4bce-b3cb-2b6f69287817)

问题：
用脚本猫的话，页面上并没有显示出来包含数据的表格

**Comment by CodFrm** [comment]
初步判断是脚本猫没有实现`await GM.xmlHttpRequest`导致的，没有阻塞住直接运行后续的逻辑了

![QQ_1725848957242](https://github.com/user-attachments/assets/450effff-b133-4997-9045-aab48a065e43)

**Comment by CodFrm** [comment]
修复了，试试这个版本：https://github.com/scriptscat/scriptcat/actions/runs/11491902568
