### ISSUE TITLE
开源请求

### ISSUE THREAD

**Issue by jks-liu** [scriptscat/scriptcat#31]
作者有考虑开源吗？

**Comment by CodFrm** [comment]
这不就是开源仓库么？

**Comment by jks-liu** [comment]
但好像除了config里面，没有相关的版权声明。

**Comment by CodFrm** [comment]
license这些的么？

还没有考虑好，最近也因为`faker.js`事件，对于license的选择也挺犹豫的

**Comment by CodFrm** [comment]
不过对于扩展源码，是会一直公开的

**Comment by CodFrm** [comment]
使用GPLv3 https://github.com/scriptscat/scriptcat/pull/32
