### ISSUE TITLE
脚本在edge浏览器不生效？

### ISSUE THREAD

**Issue by Alvin-Blithe** [scriptscat/scriptcat#313]
AC-baidu-重定向优化百度搜狗谷歌必应搜索；脚本链接：https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97?locale_override=1
该脚本在edge浏览器下不生效，我换回油猴可以生效；另外，我也测试过在Chrome下执行没有问题，但是就是在edge上执行有问题

**Comment by CodFrm** [comment]
我这边测试是可以的，哥哥可以提供一下浏览器版本和扩展版本么

![QQ_1728614225597](https://github.com/user-attachments/assets/b5ce346f-b034-4073-939e-d529f03d2df2)

**Comment by Alvin-Blithe** [comment]
> 我这边测试是可以的，哥哥可以提供一下浏览器版本和扩展版本么
> 
> ![QQ_1728614225597](https://private-user-images.githubusercontent.com/22783163/375607049-b5ce346f-b034-4073-939e-d529f03d2df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTYyMzQsIm5iZiI6MTcyODYxNTkzNCwicGF0aCI6Ii8yMjc4MzE2My8zNzU2MDcwNDktYjVjZTM0NmYtYjAzNC00MDczLTkzOWUtZDUyOWYwM2QyZGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAzMDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjYwZTJkY2JmMzQ2NjI1MGEyMDQ1ZjUzYjM0YTAxNmYyMjIxZDJiNzYwMTRhYjFiMzk0N2RiYzY2NGE1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xxPWcuNslT7H8lnmRjwWbQcxz8Ne8LdxPrAjga-tojA)

Microsoft Edge
版本 129.0.2792.79 (正式版本) (64 位)
脚本猫  0.16.5

**Comment by CodFrm** [comment]
我这里也是这个版本

Microsoft Edge
版本 129.0.2792.89 (正式版本) (arm64)

另外可以f12看看有没有报错信息么？页面上有没有脚本运行数量

**Comment by Alvin-Blithe** [comment]
![image](https://github.com/user-attachments/assets/6887ea82-0db6-479f-88be-8686eb97322e)
![image](https://github.com/user-attachments/assets/2e4755c3-a435-4594-8710-fb7c35cc65ab)
我不太懂怎么用kongzhi控制台看报错，我把它截图给你看看

**Comment by Alvin-Blithe** [comment]
![image](https://github.com/user-attachments/assets/d634d847-57da-4da9-bcbf-f33b4508b05b)
脚本是开着的

**Comment by CodFrm** [comment]
看起来是其他bug问题导致的，有点像这个

https://github.com/scriptscat/scriptcat/issues/306

哥哥试试重新安装脚本呢？

**Comment by Alvin-Blithe** [comment]
> 看起来是其他bug问题导致的，有点像这个
> 
> #306
> 
> 哥哥试试重新安装脚本呢？

还是不行，重装和复制脚本再重新写一遍也不行

**Comment by CodFrm** [comment]
百度能否使用呢？你这里的google的网站可以发我看一下吗？

**Comment by Alvin-Blithe** [comment]
![image](https://github.com/user-attachments/assets/b29a2dc2-7a77-4b24-89d2-4c1842023e89)
所有的so搜索网站都不行，谷歌网址是https://www.google.com/search?q=%E6%B2%B9%E5%8F%89

**Comment by Alvin-Blithe** [comment]
> 百度能否使用呢？你这里的google的网站可以发我看一下吗？
> 
> 可以再尝试重启浏览器试试，注意右下角要完全退出

已经完全退出了

**Comment by Alvin-Blithe** [comment]
> 百度能否使用呢？你这里的google的网站可以发我看一下吗？
> 
> 可以再尝试重启浏览器试试，注意右下角要完全退出

噢噢，我找到问题所在了，是任务管理器卡住后台，无论是重启电脑还是重装脚本，右下角退出没有用，都没有真正退出；你提醒了我后台的问题，刚刚我强制从任务栏结束了所有有关于edge的进程后可以了

**Comment by Alvin-Blithe** [comment]
> 百度能否使用呢？你这里的google的网站可以发我看一下吗？
> 
> 可以再尝试重启浏览器试试，注意右下角要完全退出

现在可以用了，但这似乎应该也是一个bug，因为在油猴上不需要这样也能运行此脚本
