### ISSUE TITLE
OneDrive 备份失败

### ISSUE THREAD

**Issue by altair441n** [scriptscat/scriptcat#329]
报错：备份失败: {"error":{"code":"unauthenticated","message":"Unauthenticated"}}
插件同步失败，脚本同步点击保存，会在 OneDrive/Applications/ 下生成一个 Graph/sync/ 空目录，没有导入的插件
取消 OneDrive 授权并卸载重装插件重新授权后依旧复现

Chrome v131.0.6778.109
ScriptsCat v0.16.6
Windows 和 MacOS 结果一致

**Comment by CodFrm** [comment]
是什么类型的账号？

**Comment by CodFrm** [comment]
进入页面f12在console执行：delete localStorage['netdisk:token:onedrive']，然后再 脚本猫-工具-备份至OneDrive，备份列表看看，会不会出错

**Comment by altair441n** [comment]
> 进入页面f12在console执行：delete localStorage['netdisk:token:onedrive']，然后再 脚本猫-工具-备份至OneDrive，备份列表看看，会不会出错

查看备份列表不出错了，但是备份还是会失败，设置页面脚本同步点击保存只更新了下 Graph/sync 空文件夹

**Comment by altair441n** [comment]
> 开启开发者选项，点击备份后，看看background里的网络请求，看看哪个API失败了，我这里没复现出来 ![image](https://private-user-images.githubusercontent.com/22783163/393769849-9e87480f-776e-47b3-84cd-988b7bebd0a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3Mzg2MTIsIm5iZiI6MTczMzczODMxMiwicGF0aCI6Ii8yMjc4MzE2My8zOTM3Njk4NDktOWU4NzQ4MGYtNzc2ZS00N2IzLTg0Y2QtOTg4YjdiZWJkMGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA5NTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmM2NmMTI3ZjY5NTdiY2I3YTdmYmVlYjZmMTg1YjU1Yjk2MDkwYjY3N2VkYTA4OWYwMWY1M2E5NWNjM2FkZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vZFytoDAxOh4mMCEcd_ub0b8ePJ2oIyxNtiiiLGX8LE)
> 
> ![image](https://private-user-images.githubusercontent.com/22783163/393769137-2c2490a1-9ca0-4343-81c2-3da428e12585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3Mzg2MTIsIm5iZiI6MTczMzczODMxMiwicGF0aCI6Ii8yMjc4MzE2My8zOTM3NjkxMzctMmMyNDkwYTEtOWNhMC00MzQzLTgxYzItM2RhNDI4ZTEyNTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA5NTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOWYzZDNjMmFjMDcyOTU3Y2ZlNDdjNThhOTlhMzQ4YjJlZDAzZjQ2MzFjNTRmNWQyN2VkMWQwYzlkNjk5YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NW8NPkMbI2uMM2F92vM3MoJs46SFmkfW3wRnhCI1yUw)


![image](https://github.com/user-attachments/assets/29e1549b-d770-4b1c-80f2-f5d518147a96)

**Comment by CodFrm** [comment]
@altair441n 可以把返回的详细的内容发一下么？我看看有没有具体的错误码

**Comment by altair441n** [comment]
@CodFrm 我试了下在 Koofr 上也上传不到 OneDrive，感觉是 OneDrive 的问题，我已经联系微软客服了，先看看他们技术人员怎么说吧。

**Comment by CodFrm** [comment]
@altair441n 哥哥也可以发一下错误码之类的信息，自查一下

**Comment by altair441n** [comment]
@CodFrm 重新授权了下，有两个接口报错
[请求错误.txt](https://github.com/user-attachments/files/18143950/default.txt)

**Comment by CodFrm** [comment]
console中执行一下这个：`delete localStorage['netdisk:token:onedrive']` 再重新授权，点备份列表就行

这好像是另外一个问题了

**Comment by altair441n** [comment]
@CodFrm 重新授权后，点备份列表提示没有备份文件，点击备份是同样的 uploadSession 接口报错

**Comment by altair441n** [comment]
@CodFrm httpcode : 401 Unauthorized，response : {"error":{"code":"unauthenticated","message":"Unauthenticated"}}

**Comment by CodFrm** [comment]
az，没有任何有效信息，只能问问微软的人员了

**Comment by altair441n** [comment]
@CodFrm 嗯，用暴力猴试了下也同步不了，应该是 OneDrive 的问题

**Comment by kun2001github** [comment]
[我找到了一篇文章，不知道是否有所帮助](https://learn.microsoft.com/en-us/answers/questions/2157674/how-to-fix-((error-((code-unauthenticated-message)
