### ISSUE TITLE
油猴脚本不能加载

### ISSUE THREAD

**Issue by leafmoes** [scriptscat/scriptcat#36]
脚本[派派助手](https://greasyfork.org/zh-CN/scripts/438022-%E6%B4%BE%E6%B4%BE%E5%8A%A9%E6%89%8B-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E5%B7%A5%E5%85%B7%E7%AE%B1%E7%9B%B4%E9%93%BE%E8%A7%A3%E6%9E%90-%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0)无法加载

**Comment by CodFrm** [comment]
@\match 匹配实现问题 已修复
