### ISSUE TITLE
ui添加页面按钮位置能否调整？

### ISSUE THREAD

**Issue by ChitaGideon** [scriptscat/scriptcat#37]
<img width="152" alt="image" src="https://user-images.githubusercontent.com/1167456/153702523-323c8dbe-f345-4984-b4c1-4da500d322ce.png">

这个按钮位置能不能调整下，比如可以拖动；页面拖到最下面经常遮挡后面的按钮，用起来很不方便

**Comment by CodFrm** [comment]
![image](https://user-images.githubusercontent.com/22783163/153747208-adc73bbd-581f-4d10-a345-718139f5371b.png)

添加了一个这个按钮
