### ISSUE TITLE
[BUG]x-javascript的脚本加载为空

### ISSUE THREAD

**Issue by joriscai** [scriptscat/scriptcat#38]
我想接入腾讯云的前端监控，来做一些日志上报。脚本链接为：https://cdn-go.cn/aegis/aegis-sdk/latest/aegis.min.js

测试时，发现脚本的响应头类型为：application/x-javascript。导出加载时，content为空，如下图

<img width="721" alt="image" src="https://user-images.githubusercontent.com/17852005/155450507-95425cfa-9da2-4ce4-8ecc-3f17708482e8.png">

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/17852005/155450193-7e758ccc-bb9e-4c89-ba0c-74ec30bd7520.png">

调试发现，代码中有判断响应头返回的类型。在这个map中加上application/x-javascript则可以正常了。

![image](https://user-images.githubusercontent.com/17852005/155451876-3632967b-ef74-432a-8f75-f948a62606d8.png)

建议加上application/x-javascript这个响应类型。

**Comment by CodFrm** [comment]
感谢反馈，已合并
