### ISSUE TITLE
每次Edge自动更新后，脚本猫内存储的所有内容都会消失

### ISSUE THREAD

**Issue by LazzyFatty** [scriptscat/scriptcat#40]
当前edge版本为98.0.1108.62 (官方内部版本) (64 位)
脚本猫版本为0.9.0
每次Edge自动更新后，脚本猫内存储的所有内容都会消失，包括登录状态、已安装脚本及脚本设置内容

**Comment by CodFrm** [comment]
是通过市场更新的么？应该不会出现这种问题才是

之前的版本也会这样么？

**Comment by LazzyFatty** [comment]
edge的更新是自动完成的，脚本猫是从edge的商店里安装的。这个情况已经出现过好几次了，只是之前我没找到原因，因为edge的更新没有任何的通知和提醒，直到昨天我发现edge多了个新功能，同时脚本猫又被清空了，我才意识到这件事

**Comment by CodFrm** [comment]
其它插件呢？好奇怪呀，我只能看我下次更新会不会了

**Comment by LazzyFatty** [comment]
浏览器上的其他插件都没有发现有类似情况

**Comment by CodFrm** [comment]
这次更新之后有再出现么？

**Comment by LazzyFatty** [comment]
截止到目前，edge还没有推送最新版本插件的更新，因此我的插件版本仍然是0.9.0。但是在此之前我想提交一个新的问题，目前我的edge版本已经自动更新到了101.0.1210.32 (正式版本) (64 位)，目前我的脚本猫的主页中的脚本列表里显示我未安装任何插件，但是在浏览网页时，点击插件图标可以看到有插件正在运行，这些插件也确实生效了。刚刚，我还尝试了通过greasyfork安装新的插件，点击安装按钮后，长时间无响应。
![image](https://user-images.githubusercontent.com/45315173/166813028-da0c022d-ea98-4246-b5dd-4a68d0a67389.png)
![image](https://user-images.githubusercontent.com/45315173/166813132-3a540f05-c1d3-4d92-b787-224c6168e402.png)
![image](https://user-images.githubusercontent.com/45315173/166813203-bcd99a53-8c8a-41d8-acbc-36c4b8dfac6a.png)
edge推送新版本插件后，我再向您反馈

**Comment by LazzyFatty** [comment]
今天早上收到了edge的插件更新，插件更新完成的时候，突然开始检查脚本更新，检查了一下，上一条中提到的问题都被更新修复了。
等edge自动更新后，我再向您反馈

**Comment by CodFrm** [comment]
电影信息查询 那个脚本安装很慢应该是最近jsdelivr被屏蔽了原因，挂梯子安装试试

**Comment by CodFrm** [comment]
哥哥的系统是Mac么？

**Comment by CodFrm** [comment]
https://answers.microsoft.com/zh-hans/microsoftedge/forum/all/edge%E6%B5%8F%E8%A7%88%E5%99%A82021%E5%B9%B412/a8ddeb18-11b7-40b4-9785-224a9e0f462a

https://www.cnblogs.com/chenmoran/p/3374194.html

试试类似的操作

**Comment by CodFrm** [comment]
无法追踪问题
