### ISSUE TITLE
反馈集合

### ISSUE THREAD

**Issue by yjgame-mark** [scriptscat/scriptcat#46]
建议：GM_setValue储存的数据建议增加一栏，不要在数据前用数据类型英文首字母标注，手动修改时容易出错
建议：设置增加开关脚本时自动刷新当前网页功能，Tampermonkey 和暴力猴都有的，调试时挺有用的
bug：打开脚本列表主页后，拉动主页标签成独立窗口后，此时点击插件图标当前页运行脚本处会出现多个同名历史代码在同时运行，此bug我不知道什么操作引起的，你可以尝试复现

**Comment by yjgame-mark** [comment]
建议：GM_setValue储存的数据建议增加一栏，不要在数据前用数据类型英文首字母标注，手动修改时容易出错 
建议：设置增加开关脚本时自动刷新当前网页功能，Tampermonkey 和暴力猴都有的，调试时挺有用的 
bug：打开脚本列表主页后，拉动主页标签成独立窗口后，此时点击插件图标当前页运行脚本处会出现多个同名历史代码在同时运行，此bug我不知道什么操作引起的，你可以尝试复现
bug：手动新建脚本，ctrl+s保存后，无法再手动修改

**Comment by CodFrm** [comment]
bug：手动新建脚本，ctrl+s保存后，无法再手动修改 这个我没有复现，可以给个复现的流程么？

**Comment by CodFrm** [comment]
bug：打开脚本列表主页后，拉动主页标签成独立窗口后，此时点击插件图标当前页运行脚本处会出现多个同名历史代码在同时运行，此bug我不知道什么操作引起的，你可以尝试复现

这还能复现么？按理说拉动主页标签成独立窗口应该是不会有影响的

**Comment by CodFrm** [comment]
建议1已经在v0.10.x优化

建议2后续可以加入
> 增加开关脚本时自动刷新当前网页功能
