### ISSUE TITLE
无法使用EhSyringe脚本

### ISSUE THREAD

**Issue by JiaoYeTan** [scriptscat/scriptcat#47]
https://sleazyfork.org/zh-CN/scripts/407833-ehsyringe
用油猴能正常使用,scriptcat则不行

**Comment by CodFrm** [comment]
alpha版本测试可以了

<img width="634" alt="image" src="https://user-images.githubusercontent.com/22783163/199409030-62841809-f0e5-420f-bb10-0dd056080b0f.png">
