### ISSUE TITLE
GM_addValueChangeListener逻辑问题

### ISSUE THREAD

**Issue by Hangover1230** [scriptscat/scriptcat#48]
脚本猫侦听到两次值的更改，开始侦听到一次，3秒后再侦听到一次值的更改，但旧值与新值获取逻辑有问题

![This is an image](https://gitee.com/MarHangover/images/raw/master/image/QQ图片20220316135127.png)

同样的代码油猴只侦听3秒后的更改值，运行如下：

三秒后输出
![This is an image](https://gitee.com/MarHangover/images/raw/master/image/QQ图片20220316135135.png)

**Comment by CodFrm** [comment]
alpha已优化
