### ISSUE TITLE
登录状态丢失

### ISSUE THREAD

**Issue by lawchou** [scriptscat/scriptcat#50]
每次登录以后，关闭浏览器过一段时间打开浏览器，插件的登录状态丢失，导致云同步经常失败。
操作系统：win7 、win11、UOS
浏览器：360极速浏览器、EDGE

**Comment by CodFrm** [comment]
一段时间是多久呢？

**Comment by lawchou** [comment]
> 一段时间是多久呢？

没具体留意过， 体会到的是上午登录了   下午登录状态就没了

**Comment by CodFrm** [comment]
还会出现么？

**Comment by lawchou** [comment]
您好，您的邮件我已收到！
