### ISSUE TITLE
每次关闭chrome的时候重新进入chrome都会把脚本猫关闭，需要手动进管理拓展程序开启

### ISSUE THREAD

**Issue by Kingxs840** [scriptscat/scriptcat#55]
每次关闭chrome的时候重新进入chrome都会把脚本猫关闭，需要手动进管理拓展程序开启

**Comment by CodFrm** [comment]
这个问题应该是和代理扩展冲突了，代理扩展会把脚本猫关闭掉

现在已经处理了。。。但也只是只能提示。这直接关闭太可恶了。。。。

**Comment by YogurtGuo** [comment]
这个问题在chrome内核系的浏览器都有，目前在360极速x、edge和chrome上都有出现，火狐上因为没有安装代理扩展，不清楚是否有这个问题

**Comment by CodFrm** [comment]
处理了 https://github.com/scriptscat/scriptcat/issues/60
