### ISSUE TITLE
脚本列表的设计小瑕疵

### ISSUE THREAD

**Issue by YogurtGuo** [scriptscat/scriptcat#58]
脚本列表里的最后一个脚本，它的编辑按钮——一个笔一样的icon，被那个大的加号“+”挡住了

**Comment by CodFrm** [comment]
加号里有隐藏的选项

**Comment by CodFrm** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/22783163/164885109-5e9ea90a-71ae-4da5-918b-22923fe67c5b.png">

**Comment by YogurtGuo** [comment]
> 加号里有隐藏的选项

哦，我的锅，哈哈哈
