### ISSUE TITLE
多个浏览器同步脚本时，同一个脚本出现多个

### ISSUE THREAD

**Issue by YogurtGuo** [scriptscat/scriptcat#59]
电脑上有火狐、edge、360极速和chrome，都装了脚本猫，然后同步的时候，同一个脚本就变成了多个脚本
<img width="924" alt="image" src="https://user-images.githubusercontent.com/90633457/164885346-a657b492-d783-4bd2-aba1-0ec29abbc878.png">

**Comment by CodFrm** [comment]
最新版本已经取消云同步，增加webdav 详情请看：https://github.com/scriptscat/scriptcat/issues/99

同时已经移除账号登录功能
