### ISSUE TITLE
脚本猫插件被异常禁用

### ISSUE THREAD

**Issue by slightin** [scriptscat/scriptcat#63]
最近edge浏览器上，脚本猫插件会被自动禁用（大概两三天就会出现），出现条件不明

**Comment by CodFrm** [comment]
什么版本呢？

**Comment by slightin** [comment]
0.9.0

**Comment by slightin** [comment]
以下是edge的报错
![image](https://user-images.githubusercontent.com/67229521/166625813-311a2254-500e-4206-b759-ae9948188ff0.png)

![image](https://user-images.githubusercontent.com/67229521/166625751-e9938e59-a80d-4080-8ef6-2b3e63c63dd0.png)

**Comment by CodFrm** [comment]
这报错应该是运行时的一些报错

升级到0.9.1应该可以解决 这个问题与 https://github.com/scriptscat/scriptcat/issues/55 类似
