### ISSUE TITLE
可以增加自动更新吗

### ISSUE THREAD

**Issue by JackeyLovez** [scriptscat/scriptcat#64]

**Comment by CodFrm** [comment]
有的呀，是更新脚本还是更新扩展？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JackeyLovez ***@***.***&gt;
发送时间: 2022年5月7日 13:42
收件人: scriptscat/scriptcat ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [scriptscat/scriptcat] 可以增加自动更新吗 (Issue #64)

**Comment by 2482188189** [comment]
怎么更新0.9.1脚本哇 不可以自动更新吗

**Comment by CodFrm** [comment]
你之前是怎么安装的？如果是从edge/chrome商店安装的会自动更新，否则需要自己下载扩展zip文件更新

**Comment by JackeyLovez** [comment]
我在Vivaldi上的chrome商店下载的 我卸载了重新安装试试

**Comment by 2482188189** [comment]
不行 重新卸载 还是安装的0.9.0的

**Comment by 2223040848** [comment]
edge商店的还是0.9.0版本的并没有自动更新。

**Comment by CodFrm** [comment]
已过审核 应该自动更新了
