### ISSUE TITLE
qq浏览器【当前页脚本】没反应

### ISSUE THREAD

**Issue by yzjn6** [scriptscat/scriptcat#66]
![image](https://user-images.githubusercontent.com/71960835/168071652-0fd9505e-f721-4e65-8218-0fd0954d5524.png)
![image](https://user-images.githubusercontent.com/71960835/168072783-0fc0c26a-a88f-4cc1-bede-b9bf6a7ed89d.png)

安装各种脚本都没用，插件中心会提示错误
后台类的脚本正常

**Comment by CodFrm** [comment]
可以给一下浏览器版本么？上次更新之后好像有不少用户出现这种情况。。。。

**Comment by yzj957x** [comment]
感觉不需要了，qq浏览器内核好像从来没有升级过。。。

**Comment by CodFrm** [comment]
v0.10.0尝试使用babel做兼容吧，后续再观察
