### ISSUE TITLE
能否考虑添加一个“为当前网站寻找脚本”的功能？类似暴力猴插件里的那种

### ISSUE THREAD

**Issue by bling-yshs** [scriptscat/scriptcat#69]
如题
![Snipaste_2022-05-19_20-30-39](https://user-images.githubusercontent.com/41812674/169293698-5260e427-2421-4aad-83c5-8398d3fdf547.jpg)
点击以后可以自动跳转到脚本站搜索可以在当前网站使用的脚本（网站可以换成脚本猫自己的脚本站）
![Snipaste_2022-05-19_20-31-13](https://user-images.githubusercontent.com/41812674/169293849-c9b8ddaa-bf0a-4023-b09e-24a5e9316ca7.jpg)

**Comment by CodFrm** [comment]
有想做过，但是我觉得最好的形式应该是下面这个脚本的样子

Userscript+ : Show Site All UserJS
https://scriptcat.org/script-show-page/320

**Comment by bling-yshs** [comment]
> 

确实确实，这种更是方便

**Comment by bling-yshs** [comment]
> 有想做过，但是我觉得最好的形式应该是下面这个脚本的样子
> 
> Userscript+ : Show Site All UserJS https://scriptcat.org/script-show-page/320

确实确实，这种更是方便
