### ISSUE TITLE
手动终止后台脚本后仍在运行

### ISSUE THREAD

**Issue by slightin** [scriptscat/scriptcat#70]
在options.html中手动停止后台脚本后在background.html的控制台中仍可看到脚本在运行
![image](https://user-images.githubusercontent.com/67229521/169850550-3efe7ed8-bf6b-4769-b9f3-ba7c0dfabc06.png)
![image](https://user-images.githubusercontent.com/67229521/169850813-a9d9c761-c29c-4c4a-90ab-b97df50ab0e7.png)
![image](https://user-images.githubusercontent.com/67229521/169850740-cb7dd688-bdbe-4a03-a2f9-b111a27a8e0e.png)

**Comment by CodFrm** [comment]
现在的机制，停止后只是不再接收脚本的GM API请求，后续做些优化，劫持setTimeout之类的，停止后清理掉脚本资源吧。

主要是不希望让脚本作者去控制这个运行时

**Comment by LiangShangQing** [comment]
// @name         🔥🔥🔥【免梯子+免翻墙+免科学上网工具/国内直连】HTML5视频播放器YouTube油管增强脚本
// @version      2.2.3
这个脚本也是，我删除了还是会回来 。代码删光保存， 一会打开又还原了，严重影响体验。
有啥解决办法吗 不想卸载脚本猫

**Comment by CodFrm** [comment]
@LiangShangQing 确定正确的删除了么？

删除的时候有没有报错？

**Comment by CodFrm** [comment]
考虑引入`AbortController `，可以看看这篇文章，大伙可以讨论一下

https://mp.weixin.qq.com/s/liTMB0sTcl6jkEjUPzCUjA

**Comment by CodFrm** [comment]
目前已实现setTimeout/Interval的资源回收，后续再考虑实现AbortController主动通知
