### ISSUE TITLE
扩展不定期崩溃, 内存溢出

### ISSUE THREAD

**Issue by hhuimie** [scriptscat/scriptcat#71]
浏览器版本: Edge 101.0.1210.32 (正式版本) (64 位)
Scriptcat版本: 0.9.1
脚本数量3-5个, 可能每小时运行, 数据量大概几万条, 有些脚本会做成爬虫, 基本几天会崩溃一次
但是之前用油猴是没这问题的

**Comment by CodFrm** [comment]
方便发一下脚本看看么？

**Comment by CodFrm** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/22783163/170412534-13a8baca-ead4-4317-b226-42309a27b472.png">
这个页面有些什么报错没？

**Comment by hhuimie** [comment]
没看到什么特别的报错, 不过我在一个新的Edge浏览器, 只安装了scriptcat和油猴(版本4.16.1), 同时测试了一下, 脚本如下

Scriptcat脚本
```
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @require      https://cdn.jsdelivr.net/npm/scriptcat-lib@1.1.1/dist/gm.js
// @definition   https://cdn.jsdelivr.net/npm/scriptcat-lib@1.1.1/src/types/gm.d.ts
// @grant        GM_xmlhttpRequest
// @grant        GM_log
// @grant        GM_setValue
// @grant        GM_getValue
// @crontab      */1 * * * *
// @connect      https://s1.ax1x.com
// ==/UserScript==

let done;
gm.ajax({method:'get',url:'https://s1.ax1x.com/2022/05/26/XEW4te.png'})
    .then(resp=>{
        let count = GM_getValue('count',0);
        GM_log(count++);
        GM_setValue('count',count);
        GM_log(JSON.stringify(resp).substr(0,1000));
        console.log(resp);
        done();
    }).catch(e=>{
        let count = GM_getValue('count',0);
        GM_log(count++);
        GM_setValue('count',count);
        done();
    });
return new Promise((resolve, reject) => {
    // Your code here...
    done = resolve;
});

```

油猴脚本
```
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @grant        GM_xmlhttpRequest
// @grant        GM_setValue
// @grant        GM_getValue
// @include      https://www.baidu.com/
// ==/UserScript==

setInterval(function(){
    GM_xmlhttpRequest({
        method:'get',
        url:'https://s1.ax1x.com/2022/05/26/XEW4te.png',
        onload:function(resp){
            let count = GM_getValue('count',0);
            console.log(count++);
            GM_setValue('count',count);
            console.log(JSON.stringify(resp).substr(0,1000));
            console.log(resp);
        }
    });
},60*1000);

```


结果如下:
scriptcat运行了167次后崩溃, 显示内存溢出
![image](https://user-images.githubusercontent.com/4830177/170668458-414e16d0-4523-41cb-bc05-9559c60858a2.png)


油猴运行到200+都没事

**Comment by hhuimie** [comment]
请问还有什么需要我提供的吗?
目前还是会崩溃
![3CCF88E1](https://user-images.githubusercontent.com/4830177/172757923-2773ac6a-6c35-403c-b1c1-2446849b4520.png)

**Comment by hhuimie** [comment]
扩展不稳定, 真是挺难受的.
不知道能不能先用一些其他野路子解决这个问题呢?
现在我是直接用ahk每天重启一遍edge.....
https://stackoverflow.com/questions/13104360/how-to-restart-a-chrome-extension-automatically

**Comment by CodFrm** [comment]
不清楚op还关注这个么？今天测试了一下，代码中有将日志打到控制台 console.log(resp); 这个也会导致内存过大，我删除这一行后，使用下面的代码测试，发现确实是有内存泄漏问题，当停用脚本时内存恢复正常，这个问题会在最新版本去尝试修复

```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @require      https://cdn.jsdelivr.net/npm/scriptcat-lib@1.1.1/dist/gm.js
// @definition   https://cdn.jsdelivr.net/npm/scriptcat-lib@1.1.1/src/types/gm.d.ts
// @grant        GM_xmlhttpRequest
// @grant        GM_log
// @grant        GM_setValue
// @grant        GM_getValue
// @crontab      */5 * * * * *
// @connect      https://s1.ax1x.com
// ==/UserScript==

let done;
gm.ajax({method:'get',url:'https://s1.ax1x.com/2022/05/26/XEW4te.png'})
    .then(resp=>{
        let count = GM_getValue('count',0);
        GM_log(count++);
        GM_setValue('count',count);
        GM_log(JSON.stringify(resp).substr(0,1000));
        // console.log(resp);
        done();
    }).catch(e=>{
        let count = GM_getValue('count',0);
        GM_log(count++);
        GM_setValue('count',count);
        done();
    });
return new Promise((resolve, reject) => {
    // Your code here...
    done = resolve;
});

```

**Comment by CodFrm** [comment]
<img width="196" alt="image" src="https://user-images.githubusercontent.com/22783163/200878332-38786656-fe9b-4f0d-bc87-0265bf49d287.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/22783163/200878400-f13e7eaf-8391-4b6f-92f2-0f7be1d68c28.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/22783163/200878500-65ac3808-d483-49b5-bb66-930d164db0ee.png">

执行若干次后，内存波动正常

**Comment by hhuimie** [comment]
> <img alt="image" width="196" src="https://user-images.githubusercontent.com/22783163/200878332-38786656-fe9b-4f0d-bc87-0265bf49d287.png">
> 
> <img alt="image" width="480" src="https://user-images.githubusercontent.com/22783163/200878400-f13e7eaf-8391-4b6f-92f2-0f7be1d68c28.png">
> 
> <img alt="image" width="323" src="https://user-images.githubusercontent.com/22783163/200878500-65ac3808-d483-49b5-bb66-930d164db0ee.png">
> 
> 执行若干次后，内存波动正常
> 
> 不过内存占用挺高的，后续继续优化

测试了下0.10.x版本, 比0.9.x的稳定, 但是依然会内存溢出
![image](https://user-images.githubusercontent.com/4830177/202356087-c07e8b55-bbae-4562-9432-05a7c0579d52.png)

**Comment by CodFrm** [comment]
可以给一下脚本，或者执行频率么？

**Comment by hhuimie** [comment]
> 可以给一下脚本，或者执行频率么？

脚本不太方便给, 好多个脚本, 10分钟左右运行一次, 会下载, 处理xlsx/json, 然后上传
我用上面简单的脚本貌似也没法快速复现问题, 我也有点无奈
6点开始运行的脚本, 到现在3g了
![image](https://user-images.githubusercontent.com/4830177/202611090-8442c562-8e2a-40b9-b194-f81bfa287b0b.png)

**Comment by CodFrm** [comment]
有类似的脚本么？使用下面代码执行会有这个问题么？没有的话，比较难判断是不是脚本的内存泄漏问题

```js
// ==UserScript==
// @name         New Userscript
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @require      https://cdn.jsdelivr.net/npm/scriptcat-lib@1.1.1/dist/gm.js
// @definition   https://cdn.jsdelivr.net/npm/scriptcat-lib@1.1.1/src/types/gm.d.ts
// @grant        GM_xmlhttpRequest
// @grant        GM_log
// @grant        GM_setValue
// @grant        GM_getValue
// @crontab      */5 * * * * *
// @connect      https://s1.ax1x.com
// ==/UserScript==

let done;
gm.ajax({method:'get',url:'https://s1.ax1x.com/2022/05/26/XEW4te.png'})
    .then(resp=>{
        let count = GM_getValue('count',0);
        GM_log(count++);
        GM_setValue('count',count);
        GM_log(JSON.stringify(resp).substr(0,1000));
        // console.log(resp);
        done();
    }).catch(e=>{
        let count = GM_getValue('count',0);
        GM_log(count++);
        GM_setValue('count',count);
        done();
    });
return new Promise((resolve, reject) => {
    // Your code here...
    done = resolve;
});

```

**Comment by CodFrm** [comment]
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/22783163/204950867-9ce97c96-57e4-41ae-8465-4882c0d26721.png">

上述脚本执行600次后，内存情况

<img width="484" alt="image" src="https://user-images.githubusercontent.com/22783163/204951470-c87a5c68-490e-4dbf-ba45-752d87afe895.png">

我觉得大概率还是哥哥的代码问题，写后台脚本的时候确实要注意这内存释放的问题

哥哥也可以去油猴中文网贴一下相关代码或者关键代码https://bbs.tampermonkey.net.cn/，社区还是挺活跃的
