### ISSUE TITLE
脚本运行不了

### ISSUE THREAD

**Issue by wqasde21** [scriptscat/scriptcat#72]
进入脚本运行页面不显示脚本，点了也没有反应

**Comment by CodFrm** [comment]
可以把脚本和页面的url发出来嘛？

**Comment by wqasde21** [comment]
http://i.mooc.chaoxing.com/space/index?t=1653552146650

moz-extension://07353882-979f-416b-8663-4bc939dddfdb/install.html?uuid=4636606f-b1c3-50f8-ac18-8f1c3b581154
是这两个吗

**Comment by CodFrm** [comment]
> http://i.mooc.chaoxing.com/space/index?t=1653552146650
> 
> moz-extension://07353882-979f-416b-8663-4bc939dddfdb/install.html?uuid=4636606f-b1c3-50f8-ac18-8f1c3b581154 是这两个吗

网站好像是的，但是脚本呢？你想在这个页面运行那个脚本

**Comment by CodFrm** [comment]
> http://i.mooc.chaoxing.com/space/index?t=1653552146650
> 
> moz-extension://07353882-979f-416b-8663-4bc939dddfdb/install.html?uuid=4636606f-b1c3-50f8-ac18-8f1c3b581154 是这两个吗

网站好像是的，但是脚本呢？你想在这个页面运行那个脚本

**Comment by CodFrm** [comment]
> http://i.mooc.chaoxing.com/space/index?t=1653552146650
> 
> moz-extension://07353882-979f-416b-8663-4bc939dddfdb/install.html?uuid=4636606f-b1c3-50f8-ac18-8f1c3b581154 是这两个吗

网站好像是的，但是脚本呢？你想在这个页面运行那个脚本

**Comment by wqasde21** [comment]
https://scriptcat.org/script-show-page/365z这个这个

**Comment by CodFrm** [comment]
你的浏览器版本是多少呢？

**Comment by wqasde21** [comment]
是最新版的火狐

**Comment by jhin3** [comment]
请问有解决吗，我也是一样的问题

**Comment by CodFrm** [comment]
> 请问有解决吗，我也是一样的问题

脚本问题，找脚本作者吧，去脚本页面反馈

**Comment by jhin3** [comment]
我用的是火狐的网课小工具，搜题没有通知条，不能搜题

**Comment by CodFrm** [comment]
脚本问题
