### ISSUE TITLE
点开通知后再点新建脚本 被遮挡

### ISSUE THREAD

**Issue by mydebug** [scriptscat/scriptcat#73]
![image](https://user-images.githubusercontent.com/13099303/171082466-297bb1b4-81cb-4c15-a754-cc2173fa1a1e.png)

**Comment by CodFrm** [comment]
应该是有个优先级的问题，问题不大。

不过这么一说，感觉新建脚本哪里也应该往下弹一些，不然不好消掉这个菜单栏。

**Comment by CodFrm** [comment]
0.10.0已重构
