### ISSUE TITLE
【功能建议】希望在脚本安装页/管理器页面增加存储到本地功能

### ISSUE THREAD

**Issue by IamApoorStudent** [scriptscat/scriptcat#75]
如题，当我打开脚本安装页后可以在安装脚本/关闭后再加一个下载文件到本地的按钮，在管理器内也加一个存储选中脚本到本地的功能

**Comment by CodFrm** [comment]
感觉不太必要，可以直接复制粘贴代码保存文件

现在也可以选择单个脚本文件进行导出了

<img width="674" alt="image" src="https://github.com/scriptscat/scriptcat/assets/22783163/1bc8027d-1ec5-4208-b2a6-f708ccaed817">
