### ISSUE TITLE
脚本全部丢失了，日志也是

### ISSUE THREAD

**Issue by ChitaGideon** [scriptscat/scriptcat#76]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1167456/172513185-f112db22-037f-40a3-a4b5-fe785556a979.png">
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1167456/172513213-8cec4f0d-10b7-4b56-9262-5de6cd4315d8.png">

好像某个脚本报错，我想进日志看下，就看见全部没了。。。

**Comment by CodFrm** [comment]
控制面板页 f12 看看有没有报错？

**Comment by ChitaGideon** [comment]
我已经重启chrome了，看了是真的找不回来了。

**Comment by ChitaGideon** [comment]
没有吧，最近一两天没怎么操作过；现在看是0.9.1；

**Comment by CodFrm** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/22783163/172513972-3161be3a-7dc1-446a-862a-e604b15abad4.png">

脚本的信息储存是使用的IndexDB，哥哥看看这里还有没有数据

**Comment by CodFrm** [comment]
最近有用过数据清理之类的软件么？不知道360那些会不会当垃圾文件清理掉

**Comment by ChitaGideon** [comment]
我已经导入半年前的备份了；丢了点这半年的脚本吧；数据清理不应该，我用的mac，没装360，昨晚盖上电脑休眠，早上起来看到有个脚本报错，想看看手动跑跑，就发现列表里没东西了，但当时脚本应该还在内存里，因为页面脚本在对应页面还是有显示的，重启chrome就彻底没了，页面脚本在对应页面也没显示了。
看了之后还是多做本地备份好些

**Comment by ChitaGideon** [comment]
chrome 版本是 102.0.5005.61（正式版本） (x86_64)
不知道半夜有没有自动更新

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptcat/issues/40

好像和这个问题类似，但是我从来没有遇到过

**Comment by CodFrm** [comment]
扩展层想不到会有什么操作导致这个问题，如果是浏览器的话，也不好解决了

**Comment by CodFrm** [comment]
https://answers.microsoft.com/zh-hans/microsoftedge/forum/all/edge%E6%B5%8F%E8%A7%88%E5%99%A82021%E5%B9%B412/a8ddeb18-11b7-40b4-9785-224a9e0f462a

https://www.cnblogs.com/chenmoran/p/3374194.html

试试类似的操作

**Comment by ChitaGideon** [comment]
居然又遇到一次；刚才在写脚本，想把之前的一些脚本补上，然后保存不上了；刷新下，脚本没了。

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/1167456/173041202-a73b2200-7bad-4154-87b9-641f58c8a38a.png">


但页面还有
<img width="44" alt="image" src="https://user-images.githubusercontent.com/1167456/173041409-4d26a36b-d356-4c7f-94ac-84d7eb054179.png">

**Comment by CodFrm** [comment]
> 居然又遇到一次；刚才在写脚本，想把之前的一些脚本补上，然后保存不上了；刷新下，脚本没了。
> 
> <img alt="image" width="1210" src="https://user-images.githubusercontent.com/1167456/173041202-a73b2200-7bad-4154-87b9-641f58c8a38a.png">
> 
> 但页面还有 <img alt="image" width="44" src="https://user-images.githubusercontent.com/1167456/173041409-4d26a36b-d356-4c7f-94ac-84d7eb054179.png">

有办法复现么？

**Comment by CodFrm** [comment]
其他的储存项有没有数据

**Comment by CodFrm** [comment]
无法追踪问题

**Comment by CodFrm** [comment]
近期也有用户反馈，是由这个问题导致的

<img width="543" alt="image" src="https://user-images.githubusercontent.com/22783163/197397313-ec73ff6d-e48d-4f33-bf54-592f4758b9e6.png">

不清楚此问题是不是同一个问题，后续再遇到可以访问此页面，将数据库文件上传上来：edge://indexeddb-internals/
