### ISSUE TITLE
能添加OneDrive这样的第三方同步方式吗

### ISSUE THREAD

**Issue by Nine1MrSu** [scriptscat/scriptcat#80]
![image](https://user-images.githubusercontent.com/92510447/177752808-5918ee6d-0067-4c96-8d07-9abd87da0a84.png)

**Comment by CodFrm** [comment]
可以的，相当于就是把脚本打包上传上去一次，这个有计划

**Comment by CodFrm** [comment]
最新alpha版本已支持webdav同步，onedrive后面继续规划

https://github.com/scriptscat/scriptcat/issues/99
