### ISSUE TITLE
建议涉及删除操作前提示一下用户

### ISSUE THREAD

**Issue by ViCrack** [scriptscat/scriptcat#81]
我在这个地方本来是要点击编辑的，不小心点到了删除，脚本没了...
![图片](https://user-images.githubusercontent.com/18179821/178636116-a7315a02-3ea0-4231-b82d-963d93ae5c56.png)

**Comment by CodFrm** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/22783163/198817916-5a45d6e3-d445-411d-9fed-e0d714951800.png">
<img width="241" alt="image" src="https://user-images.githubusercontent.com/22783163/198817923-29025d51-3803-44af-a0e5-faaa2b1ef3d6.png">

新版本已进行优化
