### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Roiyaru** [scriptscat/scriptcat#82]
开发者你好，方便做一个“为当前网站寻找脚本”的功能吗？谢谢。

**Comment by CodFrm** [comment]
我觉得这种方式才是正解

[搬运]Userscript+ : 显示当前网站所有可用的UserJS脚本 Jaeger
https://bbs.tampermonkey.net.cn/thread-1797-1-1.html
(出处: 油猴中文网)

**Comment by Roiyaru** [comment]
> 我觉得这种方式才是正解
> 
> [搬运]Userscript+ : 显示当前网站所有可用的UserJS脚本 Jaeger https://bbs.tampermonkey.net.cn/thread-1797-1-1.html (出处: 油猴中文网)

这个要另外装插件，如果能集成还是挺好的。

**Comment by CodFrm** [comment]
> 

后面会考虑考虑吧，如果集成的话，应该也只会集成scriptcat.org这个市场，感觉还是脚本灵活

**Comment by CodFrm** [comment]
> > 我觉得这种方式才是正解
> > [搬运]Userscript+ : 显示当前网站所有可用的UserJS脚本 Jaeger https://bbs.tampermonkey.net.cn/thread-1797-1-1.html (出处: 油猴中文网)
> 
> 这个要另外装插件，如果能集成还是挺好的。

不用另外安装插件，这个就是脚本，哥哥可以试试

**Comment by Roiyaru** [comment]
> > 
> 
> 后面会考虑考虑吧，如果集成的话，应该也只会集成scriptcat.org这个市场，感觉还是脚本灵活

好，我先试试这个。
