### ISSUE TITLE
希望能够支持Bilibili Evolved脚本

### ISSUE THREAD

**Issue by Dopamine2333** [scriptscat/scriptcat#83]
B站重度用户，用的最多的脚本就是Bilibili Evolved。Bilibili Evolved脚本作者说明中写道支持油猴和暴力猴，但不支持greasymonkey，希望作者大大能够兼容此脚本。感谢！

**Comment by CodFrm** [comment]
支持的呀，我可以正常使用

**Comment by CodFrm** [comment]
应该是当时cdn.jsdelivr.net网络的问题
