### ISSUE TITLE
edge 兼容有问题？

### ISSUE THREAD

**Issue by ChitaGideon** [scriptscat/scriptcat#86]
```
// ==UserScript==
// @name         mytest for edge
// @namespace    https://bbs.tampermonkey.net.cn/
// @version      0.1.0
// @description  try to take over the world!
// @author       You
// @match        https://www.baidu.com/
// @require     https://cdn.bootcdn.net/ajax/libs/jszip/3.10.0/jszip.min.js
// @require    https://cdn.bootcdn.net/ajax/libs/lodash.js/4.17.15/lodash.js
// @require    https://cdn.bootcdn.net/ajax/libs/moment.js/2.18.1/moment.js
// ==/UserScript==

(function() {
    'use strict';
    console.log('xxxxx',_,JSzip)

    // Your code here...
})();
```
访问不到对象`xxxxx undefined undefined`

Microsoft Edge
版本 103.0.1264.62 (正式版本) (64 位)

scriptcat 0.9.1

**Comment by CodFrm** [comment]
没问题，我猜测是网络问题，@require加载失败了

<img width="544" alt="image" src="https://user-images.githubusercontent.com/22783163/180359551-7ef692b4-52b3-40ee-b25e-b51fb0f12751.png">

可以查看此处，判断是否成功加载了

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/22783163/180359658-7219bff0-81ac-4ef1-b0e9-e49786d5602e.png">

**Comment by ChitaGideon** [comment]
额 为啥我没有 

![image](https://user-images.githubusercontent.com/1167456/180361046-dbaa292c-f662-48e5-a07c-cebe8a1add0f.png)

**Comment by CodFrm** [comment]
indexdb中 不是这里



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ChitaGideon ***@***.***&gt;
发送时间: 2022年7月22日 12:13
收件人: scriptscat/scriptcat ***@***.***&gt;
抄送: 王一之 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [scriptscat/scriptcat] edge 兼容有问题？ (Issue #86)





 
额 为啥我没有

**Comment by ChitaGideon** [comment]
扩展里的indexdb有
编辑里的资源页还报错
![image](https://user-images.githubusercontent.com/1167456/180365794-47864f1f-4cae-42ce-8c1b-91ac0a8411ed.png)

**Comment by CodFrm** [comment]
> 扩展里的indexdb有 编辑里的资源页还报错 ![image](https://user-images.githubusercontent.com/1167456/180365794-47864f1f-4cae-42ce-8c1b-91ac0a8411ed.png)

资源页还没实现，试试重新加载浏览器或扩展能不能解决

**Comment by ChitaGideon** [comment]
不行，删了scriptcat重装都不行；换tampermonkey就行

**Comment by CodFrm** [comment]
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/22783163/180389663-98b7d3ec-4b35-431f-b734-da5f5571bef4.png">

这是我的到的结果，应该是正常运行吧，不太清楚楼主是不是因为其他环境影响的

Microsoft Edge
版本 103.0.1264.62 (正式版本) (arm64)

**Comment by ChitaGideon** [comment]
搞出来了，我把链接换了个版本，就成功了。
```
// @require    https://cdn.jsdelivr.net/npm/jszip@3.10.0/dist/jszip.min.js
// @require    https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
// @require    https://cdn.bootcdn.net/ajax/libs/moment.js/2.17.1/moment.js
```

**Comment by CodFrm** [comment]
这。。。可以看看是不是缓存问题

在扩展背景页中可以查看网络请求

**Comment by ChitaGideon** [comment]
![image](https://user-images.githubusercontent.com/1167456/180445725-0ae0750f-3f90-4c43-b33d-d78313850935.png)
现在才有这个日志，之前添加好像没日志
