### ISSUE TITLE
脚本无法删除

### ISSUE THREAD

**Issue by MINGBOOK** [scriptscat/scriptcat#88]
如题所述

**Comment by CodFrm** [comment]
什么意思呢？

**Comment by MINGBOOK** [comment]
抱歉，是插件反应有点慢，现在好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月24日(星期天) 晚上10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scriptscat/scriptcat] 脚本无法删除 (Issue #88)





 
什么意思呢？

**Comment by CodFrm** [comment]
不至于吧，很多脚本么？0.0

**Comment by MINGBOOK** [comment]
已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月25日(星期一) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scriptscat/scriptcat] 脚本无法删除 (Issue #88)





 
不至于吧，很多脚本么？0.0
