### ISSUE TITLE
“解除B站区域限制”脚本无效

### ISSUE THREAD

**Issue by Roiyaru** [scriptscat/scriptcat#89]
如题，应该是插件兼容性问题，麻烦开发者看看，如果是脚本问题我去脚本那边反馈。
脚本链接
https://github.com/ipcjs/bilibili-helper
https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6

**Comment by CodFrm** [comment]
确实是插件兼容性的问题

没有在@grant none中注入GM_info信息

**Comment by BoBppy** [comment]
啥时候能修复

**Comment by CodFrm** [comment]
> 啥时候能修复

😭最近还在准备重构的事情，哥哥先与tampermoneky或者其他类似扩展共用吧

**Comment by CodFrm** [comment]
修复，@grant none情况下没有注入GM_info

**Comment by CodFrm** [comment]
> 啥时候能修复

<img width="750" alt="image" src="https://user-images.githubusercontent.com/22783163/194884201-e7356dc1-cff6-4e93-919d-f8c77aabfedb.png">

@BoBppy 可以打开这个窗口，但是我不知道能不能正常使用，不确定有没有其它兼容问题
