### ISSUE TITLE
设置里的所有功能无法使用

### ISSUE THREAD

**Issue by Rainer0328** [scriptscat/scriptcat#9]

**Comment by Rainer0328** [comment]
如题

**Comment by CodFrm** [comment]
是的。。。还没完成，这是画的饼😂

下个版本会处理一下

**Comment by Rainer0328** [comment]
> 是的。。。还没完成，这是画的饼😂
> 
> 下个版本会处理一下

哈哈哈好的，加油加油

**Comment by CodFrm** [comment]
https://github.com/scriptscat/scriptcat/releases/tag/v0.6.0
