### ISSUE TITLE
不支持油猴脚本：字体渲染

### ISSUE THREAD

**Issue by geeklihui** [scriptscat/scriptcat#93]
脚本链接：https://greasyfork.org/zh-CN/scripts/416688
安装后没有设置页面，也不生效
![image](https://user-images.githubusercontent.com/28993319/190904555-4c4848e3-f5c8-4d50-a096-55c06ef4ea31.png)
对比油猴：
![image](https://user-images.githubusercontent.com/28993319/190904575-a3540e78-1cb8-4d7a-9c73-55b0b94cc254.png)

**Comment by CodFrm** [comment]
GM_info问题已修复
