### ISSUE TITLE
为何账号不能一直登录

### ISSUE THREAD

**Issue by Jeremy-stu** [scriptscat/scriptcat#98]
登上账号过一段时间就没了，还要重新登陆

**Comment by CodFrm** [comment]
有隔很久没有使用么？

**Comment by Jeremy-stu** [comment]
> 有隔很久没有使用么？

每天都用也会有这种情况，大概四五天就没了，每次重新登录后又会把我已经更新的脚本给同步成旧版，这也是个问题

**Comment by CodFrm** [comment]
最新版本已经取消云同步，增加webdav 详情请看：https://github.com/scriptscat/scriptcat/issues/99

同时已经移除账号登录功能
